### ISSUE TITLE
Translation of Log Analytics

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#1325]
"Log Analytics" is left as is here but it is translated as ログの分析 in the actual Portal. I actually think it's better to have the Portal translation changed to "Log Analytics", but can you discuss with the Portal localization team possibly?
If we're sticking with the current translation, the docs will need updating since they are indicating how to find things in the UI and you can't find them in the Japanese portal using "Log Analytics".
Thanks!

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4bb1685a-5439-034b-7668-f970390a940e
* Version Independent ID: 1dd1d6ed-e465-d9a8-1679-5f9ca37d5e6f
* Content: [OMS ポータルから Azure portal への切り替えに関する Log Analytics ユーザーの一般的な質問](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/oms-portal-faq#how-do-i-manage-permissions)
* Content Source: [articles/azure-monitor/platform/oms-portal-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-monitor/platform/oms-portal-faq.md)
* Service: **log-analytics**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by CeciAc** [comment]
Hello, @dcbrown16 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @dcbrown16

Our engineer team reviewed your suggestions and implemented them.

Kind regards,
Microsoft DOCS International Team
