### ISSUE TITLE
「アクション」への用語統一

### ISSUE THREAD

**Issue by ahf0124** [MicrosoftDocs/azure-docs.ja-jp#1326]
文章中に「ステートメント」と「アクション」が混在している。「アクション」に統一するのがよいと思う。

"Statement" and "action" are mixed in sentences. I think that it is better to unify it to "action".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dc9cd33d-4d2e-c6cf-e6cf-4ac65cc1aaf1
* Version Independent ID: 941d0646-2a17-c56d-9ae4-a474ebddc6cb
* Content: [条件付きステートメントをワークフローに追加する - Azure Logic Apps](https://docs.microsoft.com/ja-jp/azure/logic-apps/logic-apps-control-flow-conditional-statement)
* Content Source: [articles/logic-apps/logic-apps-control-flow-conditional-statement.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/logic-apps/logic-apps-control-flow-conditional-statement.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by CeciAc** [comment]
こんにちは、@ahf0124

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #21037](https://github.com/MicrosoftDocs/azure-docs/issues/21037) via [**ZenHub**](https://www.zenhub.com/)
