### ISSUE TITLE
ネットワーク接続プロパティのVM内での直接編集について

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#1422]
DNS サーバーの IP などのネットワーク接続プロパティは、Windows VM 内で直接編集しないでください。
との事ですが、Linux VMでも同様でしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a7b1b215-0434-145b-cd11-95d0f32bc015
* Version Independent ID: d328a868-a151-1985-2b62-f3884f7ad76c
* Content: [Azure 仮想ネットワーク内のリソースの名前解決](https://docs.microsoft.com/ja-jp/azure/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances#specify-dns-servers)
* Content Source: [articles/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-network/virtual-networks-name-resolution-for-vms-and-role-instances.md)
* Service: **virtual-network**
* GitHub Login: @subsarma
* Microsoft Alias: **subsarma**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
