### ISSUE TITLE
mistranslation

### ISSUE THREAD

**Issue by nakamacchi** [MicrosoftDocs/azure-docs.ja-jp#1430]
Wrong : ファイアウォールの内側にある Azure Key Vault へのアクセス
Correct : ファイアウォールの向こう側（外側）にある Azure Key Vault へのアクセス

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7072527d-caa0-ca36-408c-1b9b841dc2a6
* Version Independent ID: a03a9bb0-9882-607d-557f-114cfb7ea8e5
* Content: [ファイアウォールの内側にある Key Vault へのアクセス](https://docs.microsoft.com/ja-jp/azure/key-vault/key-vault-access-behind-firewall)
* Content Source: [articles/key-vault/key-vault-access-behind-firewall.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/key-vault/key-vault-access-behind-firewall.md)
* Service: **key-vault**
* GitHub Login: @amitbapat
* Microsoft Alias: **ambapat**

**Comment by CeciAc** [comment]
こんにちは、@nakamacchi

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@nakamacchi

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by nakamacchi** [comment]
ありがとうございます。全く意味が異なるため、早めに修正いただければ幸いです。誤訳の原因は、おそらくタイトルとその後の Q. における "behind" の文脈を混同しているためです。（原文も少しわかりにくいです）

Access Azure Key Vault behind a firewall
→ （自分のアプリケーションから見て）Firewall の向こう側（＝インターネット側）にある Azure KeyVault へのアクセス

My key vault client application needs to be behind a firewall.
→ 自分のクライアントアプリケーションは、（Azure Key Vault が存在するインターネットから見て）ファイアウォールの向こう側（すなわちファイアウォールの内側）に配置する必要があります。

**Comment by CeciAc** [comment]
こんにちは、@nakamacchi

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/key-vault/key-vault-access-behind-firewall

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
