### ISSUE TITLE
office345

### ISSUE THREAD

**Issue by tsucca** [MicrosoftDocs/azure-docs.ja-jp#1594]
[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a8ac7d3d-bae3-53d3-9dd0-f2696d90a979
* Version Independent ID: 778a0db8-de4d-e292-ad07-90db68eddff5
* Content: [パスワードのリセットの概要 - Azure Active Directory](https://docs.microsoft.com/ja-jp/azure/active-directory/user-help/user-help-password-reset-overview#BKMK_2)
* Content Source: [articles/active-directory/user-help/user-help-password-reset-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/user-help/user-help-password-reset-overview.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by tsucca** [comment]
comment

**Comment by tsucca** [comment]
Leave a comment

**Comment by CeciAc** [comment]
The feedback is empty. I'm closing this issue.
