### ISSUE TITLE
記載されているPowerShellスクリプトはAzure Cloud Shellで動作しません

### ISSUE THREAD

**Issue by gentksb** [MicrosoftDocs/azure-docs.ja-jp#1649]
【対象】
ダウンロード センターからセルフホステッド IR をインストールして登録する
手順9

【内容】
Azure PowerShell を使用した認証キーの取得は、Azure Cloud Shellで動作しません。
DataFactoryのGUIを用いて認証キーを取得する方法に変更したほうがハウツーガイドとして適切です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 32785d15-8202-6e44-f1d2-420ef0600f3f
* Version Independent ID: 3af5fa49-7bd4-18ce-f8dc-aa4a2b8c6478
* Content: [Azure Data Factory でセルフホステッド統合ランタイムを作成する](https://docs.microsoft.com/ja-jp/azure/data-factory/create-self-hosted-integration-runtime#installation-best-practices)
* Content Source: [articles/data-factory/create-self-hosted-integration-runtime.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/data-factory/create-self-hosted-integration-runtime.md)
* Service: **data-factory**
* GitHub Login: @nabhishek
* Microsoft Alias: **abnarain**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #22187](https://github.com/MicrosoftDocs/azure-docs/issues/22187) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@gentksb
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/22187) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
