### ISSUE TITLE
Regarding Japanese translation String 

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#1846]
https://docs.microsoft.com/ja-jp/azure/security/azure-infrastructure-components#types-of-users

日本語翻訳の際に必要な事ではあるとは認識しておりますが、
役割項目の横幅をある程度広げる事は可能でしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6926e3a7-f22e-53e2-7529-488c816bb69f
* Version Independent ID: 97657465-220f-736d-ef0e-1670c0a064fb
* Content: [Azure 情報システムのコンポーネントと境界](https://docs.microsoft.com/ja-jp/azure/security/azure-infrastructure-components#types-of-users)
* Content Source: [articles/security/azure-infrastructure-components.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/security/azure-infrastructure-components.md)
* Service: **security**
* GitHub Login: @TerryLanfear
* Microsoft Alias: **terrylan**

**Comment by CeciAc** [comment]
@KeiroKamioka0000  様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by LisandroSu** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @ishasahni1 @SunnyDeng 

The contributor asks if there's a way for us to adjust the width of some of the columns of table in this document. It looks pretty weird in all browsers:

Firefox
![image](https://user-images.githubusercontent.com/39163942/51852782-8da94480-2305-11e9-9629-4192d158383b.png)

Chrome
![image](https://user-images.githubusercontent.com/39163942/51852815-a31e6e80-2305-11e9-9cfd-75ebf930fe75.png)

How should we proceed with this issue?

Thanks!

**Comment by ishasahni1** [comment]
@LisandroSu can you kindly inform the customer that we are looking into this issue and we appreciate their valuable feedback.

**Comment by SunnyDeng** [comment]
Hi @bodhigautam, could you escalate to DOCS team? when you have ticket, please let us know here. Thanks

**Comment by bodhigautam** [comment]
@SunnyDeng yes, I will update once we start working to resolve this permanently. Thanks for flagging this :)

**Comment by SunnyDeng** [comment]
Hi @KeiroKamioka0000
I am sorry that it takes some time that we respond here. The fix rolled out in late Feb. Our feature team also verified and confirmed the fix on this page too. 
![image](https://user-images.githubusercontent.com/8811264/53765584-4d4d6100-3e85-11e9-9e76-3b7c0b593766.png)
I am closing this thread. But please feel free to re-opn if there is further feedback.
