### ISSUE TITLE
Please consider to change "○" to "X" on Exchange Online - msExchMailboxGuid column as same as other attributes.

### ISSUE THREAD

**Issue by M365SupportJapan** [MicrosoftDocs/azure-docs.ja-jp#1853]
On Japanese page (https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized), "○" is marked instead of "X" on Exchange Online - msExchMailboxGuid column.
As it seems no specific reason for that, please consider to change it to "X" as same as other attributes.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e7abde7c-df25-bd14-574c-92858daed39d
* Version Independent ID: 6652a5bc-4985-d45e-36fb-54da408e5e54
* Content: [Azure AD Connect によって同期される属性](https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized)
* Content Source: [articles/active-directory/hybrid/reference-connect-sync-attributes-synchronized.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/hybrid/reference-connect-sync-attributes-synchronized.md)
* Service: **active-directory**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by CeciAc** [comment]
Hello, @M365SupportJapan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @M365SupportJapan

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-sync-attributes-synchronized. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by M365SupportJapan** [comment]
Thank you for reviewing. Confirmed the information has been updated as I requested!
