### ISSUE TITLE
message stripped

### ISSUE THREAD

**Issue by kkamegawa** [MicrosoftDocs/azure-docs.ja-jp#187]
Message stripped in 1st paragraph.

>コンピューターを Azure に、またはオンプレミスのセカンダリ データ センターにレプリケートできます。 簡単な概要については、「 Site Recovery とは (stripped)

more better

> コンピューターを Azure または、オンプレミスのセカンダリ データ センターにレプリケートできます。 簡単な概要については、「 [Site Recovery とは](https://docs.microsoft.com/ja-jp/azure/site-recovery/site-recovery-overview)」を参照してください。

**Comment by SunnyDeng** [comment]
Double check with the work item in a new bug system. https://ceapex.visualstudio.com/CEINTL/_workitems/edit/8440

**Comment by SunnyDeng** [comment]
@kkamegawa thank you very much for the suggestion! You suggestion is accepted. We fixed in Translation Memory. 
Close the thread.
