### ISSUE TITLE
Translation suggestion

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#1940]
日本語：gzip テキスト ファイルを使用する場合にスループットを最大限引き上げるには、ファイルを 60 個以上に分割して、読み込みの並列処理を最大化します。
英語：To maximize throughput when using gzip text files, break files up into 60 or more files to maximize parallelism of your load.

日本語の文面では指示であることが伝わりません（仕様を述べているようです）。
スタイルガイド的に難しいかもしれませんが、お客様に混乱を招いているので、「最大化してください」など、お客様が実施することであることを明確にしてください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0b3d99f8-96b8-b31a-d6d3-868fa4614242
* Version Independent ID: 965ea5f3-ae07-3701-b49b-828170670631
* Content: [Azure SQL Data Warehouse のベスト プラクティス](https://docs.microsoft.com/ja-jp/azure/sql-data-warehouse/sql-data-warehouse-best-practices)
* Content Source: [articles/sql-data-warehouse/sql-data-warehouse-best-practices.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-data-warehouse/sql-data-warehouse-best-practices.md)
* Service: **sql-data-warehouse**
* GitHub Login: @ronortloff
* Microsoft Alias: **rortloff**

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/sql-data-warehouse/sql-data-warehouse-best-practices

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
