### ISSUE TITLE
Please add translation strings for Connections

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#1949]
It seems like current Japanese Version does not contains about Metric ; Connections.

https://docs.microsoft.com/en-us/azure/app-service/web-sites-monitor#understand-metrics
Connections	The number of bound sockets existing in the sandbox (w3wp.exe and its child processes). A bound socket is created by calling bind()/connect() APIs and remains until said socket is closed with CloseHandle()/closesocket().

Please update the Japanese Document Please.

英語原文ドキュメント側で更新が入ったのか、一部記載が日本語版に適用されていないように見受けられます。
ご確認いただけたら幸いです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2550993f-34f1-d963-3ee5-3dcebe2a64d7
* Version Independent ID: 3da9bc96-6e24-54fa-bd99-6a6a704f583a
* Content: [アプリを監視する - Azure App Service](https://docs.microsoft.com/ja-jp/azure/app-service/web-sites-monitor#understand-metrics)
* Content Source: [articles/app-service/web-sites-monitor.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/app-service/web-sites-monitor.md)
* Service: **app-service**
* GitHub Login: @btardif
* Microsoft Alias: **byvinyal**

**Comment by btardif** [comment]
This article was recently modified, so my guess is its pending localization pass.

**Comment by LisandroSu** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
Most likely the localized version is not up to date yet. But I will check to see when it will.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
This is now fixed and live.

Kind regards,
Microsoft DOCS International Team
