### ISSUE TITLE
Regarding Japanese Localized String of Sand Box

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2024]
Hello, there is two types for Sand Box for Japanese Translated Strings
[サンドボックス]
&
[サンド ボックス]

One have the half-space between the [サンド] and [ボックス], please consider to use one of them 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bf4da869-3f32-d2bb-d804-62679c1c3cbd
* Version Independent ID: 49ec3073-a31e-a0ab-882d-17d3a7a420b0
* Content: [Azure Automation での Runbook の実行](https://docs.microsoft.com/ja-jp/azure/automation/automation-runbook-execution#fair-share)
* Content Source: [articles/automation/automation-runbook-execution.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/automation/automation-runbook-execution.md)
* Service: **automation**
* GitHub Login: @georgewallace
* Microsoft Alias: **gwallace**

**Comment by v-maudel** [comment]
Hello, @KeiroKamioka0000 , 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/automation/automation-runbook-execution#fair-share. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
