### ISSUE TITLE
Authorization is not translated in Japanese properly.

### ISSUE THREAD

**Issue by anishi1222** [MicrosoftDocs/azure-docs.ja-jp#2037]
Hi,

The original document title is "Authentication and authorization in Azure App Service", and it is translated into "Azure App Service での認証および承認" in Japanese. But "認可" is more proper translation of the word "Authorization" in Japanese than "承認" in this context.
I would like to ask you guys to consider correction of translation.
Thanks in advance.

Thanks and regards,
Akihiro

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 75e17529-8b8a-1d67-f0e1-840d1d3ca990
* Version Independent ID: 265645df-ef21-4631-1744-7014b3ee681a
* Content: [認証と承認 - Azure App Service](https://docs.microsoft.com/ja-jp/azure/app-service/overview-authentication-authorization#feedback)
* Content Source: [articles/app-service/overview-authentication-authorization.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/app-service/overview-authentication-authorization.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **mahender,cephalin**

**Comment by CeciAc** [comment]
Hello, @anishi1222 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/app-service/overview-authentication-authorization#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
