### ISSUE TITLE
「BLOB をダウンロードする」の説明内容に関して

### ISSUE THREAD

**Issue by daiKoizumi** [MicrosoftDocs/azure-docs.ja-jp#2108]
段落の「5.」内で
&gt;完成した ListBlobs メソッド (作成されるローカル ファイルの完全修飾パス指定あり) を次に示します。
と記載されていますが、おそらく「ListBlobs メソッド 」の部分は「DownloadBlobメソッド」と記述される箇所かと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e04001d4-d217-ca0c-e57f-da721ebee268
* Version Independent ID: 3d49b777-6953-c0e5-3f30-8feefb22fa14
* Content: [Azure Blob Storage と Visual Studio 接続済みサービスの概要 (ASP.NET)](https://docs.microsoft.com/ja-jp/azure/visual-studio/vs-storage-aspnet-getting-started-blobs#upload-a-blob-into-a-blob-container)
* Content Source: [articles/visual-studio/vs-storage-aspnet-getting-started-blobs.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/visual-studio/vs-storage-aspnet-getting-started-blobs.md)
* Product: **visual-studio-dev15**
* GitHub Login: @ghogen
* Microsoft Alias: **ghogen**

**Comment by LisandroSu** [comment]
こんにちは、@daiKoizumi

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: [Azure Blob Storage と Visual Studio 接続済みサービスの概要 (ASP.NET)](https://docs.microsoft.com/ja-jp/azure/visual-studio/vs-storage-aspnet-getting-started-blobs#upload-a-blob-into-a-blob-container)

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
こんにちは、@daiKoizumi

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
Linguistic - Accepted Feedback 

こんにちは、@<共同作成者の GITHUB 名>  

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/visual-studio/vs-storage-aspnet-getting-started-blobs#upload-a-blob-into-a-blob-container  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
