### ISSUE TITLE
Not need to translate ”ホスティング” on table of expose the endpoint

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/azure-docs.ja-jp#2113]
[フィードバックをこちらに入力してください]
Hosting is translated to Japanese by machine translation. It is the endpoint of user extension host, so that on the following table ”ホスティング” should be in English as "Hosting". 

https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-extension-host-prepare#publish-new-endpoints

**エンドポイント (VIP)	             Protocol  	    ポート**
AdminHosting	                             HTTPS                443
**"ホスティング" --> "Hosting"**     HTTPS                443

#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c3b84311-7c1e-bc20-70e1-9e812ff27824
* Version Independent ID: c33812da-28e5-639b-dbf2-ccf8ab413309
* Content: [Azure Stack の拡張機能ホストを準備する](https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-extension-host-prepare)
* Content Source: [articles/azure-stack/azure-stack-extension-host-prepare.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-stack/azure-stack-extension-host-prepare.md)
* Service: **azure-stack**
* GitHub Login: @mattbriggs
* Microsoft Alias: **mabrigg**

**Comment by v-maudel** [comment]
こんにちは、@mattu0119

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-extension-host-prepare  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
