### ISSUE TITLE
脱字（日本語）「チュートリアル:Azure Machine Learning service でイメージ分類モデルをトレーニングする」

### ISSUE THREAD

**Issue by ftnext** [MicrosoftDocs/azure-docs.ja-jp#2116]
[モデルの構築](https://docs.microsoft.com/ja-jp/azure/machine-learning/service/tutorial-train-models-with-aml#register-model)の日本語版の脱字に気づきました。

現状：トレーニング クリプトの最後のステップでは、
修正提案：トレーニングスクリプトの最後のステップでは、

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4bee4b9a-ce0f-f98b-3160-d6c4a40ef3ac
* Version Independent ID: a0475a9e-47f6-2803-8707-fac54ba898dd
* Content: [イメージの分類チュートリアル:モデルをトレーニングする - Azure Machine Learning service](https://docs.microsoft.com/ja-jp/azure/machine-learning/service/tutorial-train-models-with-aml)
* Content Source: [articles/machine-learning/service/tutorial-train-models-with-aml.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/machine-learning/service/tutorial-train-models-with-aml.md)
* Service: **machine-learning**
* GitHub Login: @hning86
* Microsoft Alias: **haining**

**Comment by CeciAc** [comment]
こんにちは、@ftnext

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@<共同作成者の GITHUB 名>  

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/machine-learning/service/tutorial-train-models-with-aml

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
