### ISSUE TITLE
AzureCloudeServiceにデプロイした後にエラーが発生

### ISSUE THREAD

**Issue by kazamachan** [MicrosoftDocs/azure-docs.ja-jp#2125]
ドキュメントに従って作成しましたが、デプロイ後に該当URLに接続すると「500」エラーが表示されます。考えられる原因は何でしょうか。ちなみに「Node.jsアプリケーションの作成とデプロイ」はドキュメントに従って作成した結果、問題なく表示されました。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 51fa6592-d9d4-37e7-1d7b-90e0d39716ef
* Version Independent ID: 681707f2-0fa0-4d7a-e754-04261aad4309
* Content: [Node.js Express アプリをビルドして Azure Cloud Services にデプロイする](https://docs.microsoft.com/ja-jp/azure/cloud-services/cloud-services-nodejs-develop-deploy-express-app)
* Content Source: [articles/cloud-services/cloud-services-nodejs-develop-deploy-express-app.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cloud-services/cloud-services-nodejs-develop-deploy-express-app.md)
* Service: **cloud-services**
* GitHub Login: @jpconnock
* Microsoft Alias: **jeconnoc**

**Comment by CeciAc** [comment]
こんにちは、@kazamachan
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
