### ISSUE TITLE
Cannot edit report

### ISSUE THREAD

**Issue by kenzoohba80** [MicrosoftDocs/azure-docs.ja-jp#2133]
cannot edit report as this page said.
is there any step to enable editing Azure AD Activity logs report?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fb954f67-e65e-9bbe-701e-de1eafe8e26f
* Version Independent ID: 39d9b1d9-8074-12c7-7a04-fb9d545fdb04
* Content: [Azure Active Directory Power BI コンテンツ パックの使用方法](https://docs.microsoft.com/ja-jp/azure/active-directory/reports-monitoring/howto-power-bi-content-pack)
* Content Source: [articles/active-directory/reports-monitoring/howto-power-bi-content-pack.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/reports-monitoring/howto-power-bi-content-pack.md)
* Service: **active-directory**
* GitHub Login: @priyamohanram
* Microsoft Alias: **priyamo**

**Comment by CeciAc** [comment]
Hello, @kenzoohba80 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
