### ISSUE TITLE
Please update Japanese document

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2191]
Such as fact of 'One HTML file is generated for each error (in D:\LogFiles\DetailedErrors by default), and up to 50 errors (files) are retained. When the number of HTML files exceed 50, the oldest 26 files are automatically deleted.' written in English Document;

Some of important information doesn't mentioned in Japanese Translated Document.
Please consider to update it please.

Thanks

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bfc316af-0d30-b449-a04f-3019b7a16bc1
* Version Independent ID: 01c4c435-fda9-374a-70b3-f1d7f13c7651
* Content: [アプリの診断ログの有効化 - Azure App Service](https://docs.microsoft.com/ja-jp/azure/app-service/troubleshoot-diagnostic-logs?toc=%2Fazure%2Fapp-service-mobile%2Ftoc.json)
* Content Source: [articles/app-service/troubleshoot-diagnostic-logs.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/app-service/troubleshoot-diagnostic-logs.md)
* Service: **app-service**
* GitHub Login: @cephalin
* Microsoft Alias: **cephalin**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/app-service/troubleshoot-diagnostic-logs?toc=%2Fazure%2Fapp-service-mobile%2Ftoc.json

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
