### ISSUE TITLE
detailed steps in Japanese

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2192]
Please localize 'detailed steps' which is written in Japanese Document.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 27a5f434-01e8-7819-bdc6-52b2f9d4699a
* Version Independent ID: 23c3494f-3b6a-f429-e5d8-fe592ec33c82
* Content: [Azure Virtual Machines に対するネットワーク インターフェイスの追加と削除](https://docs.microsoft.com/ja-jp/azure/virtual-network/virtual-network-network-interface-vm)
* Content Source: [articles/virtual-network/virtual-network-network-interface-vm.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-network/virtual-network-network-interface-vm.md)
* Service: **virtual-network**
* GitHub Login: @jimdial
* Microsoft Alias: **jdial**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/virtual-network/virtual-network-network-interface-vm 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
