### ISSUE TITLE
Information that is still existing in Japanese version. 

### ISSUE THREAD

**Issue by v-maroge** [MicrosoftDocs/azure-docs.ja-jp#2204]
[フィードバックをこちらに入力してください]

Under "Run an on-demand backup" in this Japanese version,
while it says, "The retention range for an on-demand backup is the retention value that you specify when you trigger the backup.", the bottom of the section also says that the retention will follow the Backup policy set for the VM(復旧ポイントのリテンション期間は、仮想マシンに関連付けられているポリシーで指定されるリテンション期間と同じです。), which is a sentence that does not exist in the English version of the document.

These statements are controversial to each other, and since the later statement does not exist in the English version, it is probably wrong information that has to be taken away.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5b71eb75-6ec4-2647-c3bd-2d7822704346
* Version Independent ID: 0e174420-da45-5d9a-4a8e-81ea00f316a4
* Content: [Azure Backup サービスで Azure VM のバックアップを管理および監視する](https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-manage-vms#run-an-on-demand-backup)
* Content Source: [articles/backup/backup-azure-manage-vms.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/backup/backup-azure-manage-vms.md)
* Service: **backup**
* GitHub Login: @Sogup
* Microsoft Alias: **sogup**

**Comment by CeciAc** [comment]
Hello, @v-maroge 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @v-maroge
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-manage-vms#run-an-on-demand-backup

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
