### ISSUE TITLE
Not unified ja-jp translation for "logical" in en-us

### ISSUE THREAD

**Issue by hoisjp** [MicrosoftDocs/azure-docs.ja-jp#2216]
### current:
Kubernetes の名前空間では、ワークロードとリソースの倫理的な分離境界を形成します。

### suggestion:
Kubernetes の名前空間では、ワークロードとリソースの**論理的な**分離境界を形成します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 31b0e393-0006-ffdc-e2a9-382598c8d760
* Version Independent ID: 6a37cabc-14f9-e30a-3102-1757bda0e0c1
* Content: [オペレーターのベスト プラクティス - Azure Kubernetes Services (AKS) でのクラスターの分離](https://docs.microsoft.com/ja-jp/azure/aks/operator-best-practices-cluster-isolation#feedback)
* Content Source: [articles/aks/operator-best-practices-cluster-isolation.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/aks/operator-best-practices-cluster-isolation.md)
* Service: **container-service**
* GitHub Login: @iainfoulds
* Microsoft Alias: **iainfou**

**Comment by CeciAc** [comment]
Hello, @hoisjp 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/aks/operator-best-practices-cluster-isolation

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
