### ISSUE TITLE
Unnecessary sentences

### ISSUE THREAD

**Issue by tomonarikubo** [MicrosoftDocs/azure-docs.ja-jp#2217]
No.8 and 10 contain the following incorrect sentences. Tableau has nothing to do with this document.
[Tableau Server return URL]: Tableau Server ユーザーがアクセスする URL。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8fa5814d-91e2-2f75-77e7-62a8597f340c
* Version Independent ID: 458e93d7-a180-4c2f-5077-9b9d124d726a
* Content: [チュートリアル:Azure Active Directory とアマゾン ウェブ サービス (AWS) の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/amazon-web-service-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/amazon-web-service-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/saas-apps/amazon-web-service-tutorial.md)
* Service: **azure-active-directory**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by CeciAc** [comment]
Hello, @tomonarikubo 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by jeevansd** [comment]
@tomonarikubo Thanks for reporting the issue. @CeciAc I dont see this 8.d and 10.d Tableau step in our oroiginal documentaiton here https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/amazon-web-service-tutorial So can you please fix it?

**Comment by CeciAc** [comment]
That's correct, @jeevanbisht the error is just in the ja-JP locale, we are working on it :)

**Comment by jeevansd** [comment]
@CeciAc This is @jeevansd and not Jeevan Bisht. He is my another colleague.

**Comment by CeciAc** [comment]
Hello, @tomonarikubo 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/amazon-web-service-tutorial

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
