### ISSUE TITLE
「署名キーを作成します。」部分の項5の名称が異なります。

### ISSUE THREAD

**Issue by tsukatoh** [MicrosoftDocs/azure-docs.ja-jp#2219]
ポータルで記載されている名称と異なる名称が記載されています。
【5.[キー使用法] には [シークレット] を選択します。】
正しくは以下と思われます。
【5.[キー使用法] には [署名] を選択します。】

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bee63035-00ee-f7fd-97a1-69dae5f808ef
* Version Independent ID: a3447928-73cc-0290-6d46-b89234757e3b
* Content: [Azure Active Directory B2C のカスタム ポリシーの概要](https://docs.microsoft.com/ja-jp/azure/active-directory-b2c/active-directory-b2c-get-started-custom#feedback)
* Content Source: [articles/active-directory-b2c/active-directory-b2c-get-started-custom.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory-b2c/active-directory-b2c-get-started-custom.md)
* Service: **active-directory**
* GitHub Login: @davidmu1
* Microsoft Alias: **davidmu**

**Comment by CeciAc** [comment]
こんにちは、@tsukatoh

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@tsukatoh

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/active-directory-b2c/active-directory-b2c-get-started-custom

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
