### ISSUE TITLE
プログラムリストに足りない行があります。

### ISSUE THREAD

**Issue by linyixian** [MicrosoftDocs/azure-docs.ja-jp#2223]
モデルとラベルを読み込む際にファイル名を代入する部分が抜けています。

filename = "model.pb"
labels_filename = "labels.txt"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 754dd7d5-dd8b-4a75-5d79-0ba621a847cd
* Version Independent ID: 3cca3535-1c16-2da1-46c6-421cbf808bc3
* Content: [チュートリアル:Python での TensorFlow モデルの実行 - Custom Vision Service](https://docs.microsoft.com/ja-jp/azure/cognitive-services/custom-vision-service/export-model-python#feedback)
* Content Source: [articles/cognitive-services/Custom-Vision-Service/export-model-python.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cognitive-services/Custom-Vision-Service/export-model-python.md)
* Service: **cognitive-services**
* GitHub Login: @areddish
* Microsoft Alias: **areddish**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #27433](https://github.com/MicrosoftDocs/azure-docs/issues/27433) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@linyixian
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/azure-docs/issues/27433 を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
