### ISSUE TITLE
Regarding the Limitation of Azure Managed Disk

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2228]
Azure Managed Disks の場合:の箇所は英語側ドキュメントで更新がございましたので、日本語版での反映をよろしくお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1cd57b6d-3c6f-e546-b3ea-f83892f4c23d
* Version Independent ID: 27aecc7b-f107-96d4-b044-ae026bca2727
* Content: [Azure サブスクリプションの制限とクォータ](https://docs.microsoft.com/ja-jp/azure/azure-subscription-service-limits)
* Content Source: [articles/azure-subscription-service-limits.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-subscription-service-limits.md)
* Service: **billing**
* GitHub Login: @rothja
* Microsoft Alias: **byvinyal**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by ishasahni1** [comment]
@CeciAc this file has been updated 8 days ago and we will be pushing this file out for localization today, so hopefully file will be localized and handed back by April 1st week.

**Comment by SunnyDeng** [comment]
@ishasahni1  please add the #please-translate in the comment. Only in this way, MOR can automate this tranlation. thanks.

**Comment by CeciAc** [comment]
@ishasahni1 commented on 3/20:

@CeciAc  this file has been updated 8 days ago and we will be pushing this file  out for localization today, so hopefully file will be localized and  handed back by April 1st week.
#please-translate

**Comment by CeciAc** [comment]
3月２０日付の @ishasahni1 さんのコメントより：

@CeciAc さん、
このファイルは８日前に更新されており、本日ローカライズする方向で進めておりますので、４月の第１週目までにはローカライズされたファイルをお渡しする事ができると思います。どうぞよろしくお願い致します。
