### ISSUE TITLE
Deadlink

### ISSUE THREAD

**Issue by masashimi** [MicrosoftDocs/azure-docs.ja-jp#2230]
https://blogs.msdn.microsoft.com/sqlcat/2016/09/08/connect-to-azure-sql-database-v12-via-redirection/ 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7fb994ad-e2aa-f7a9-6472-749d257639ae
* Version Independent ID: 7f128e8b-8698-08ab-4d2e-47c4d6f60e1a
* Content: [SQL Database における 1433 以外のポート](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-develop-direct-route-ports-adonet-v12)
* Content Source: [articles/sql-database/sql-database-develop-direct-route-ports-adonet-v12.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-database/sql-database-develop-direct-route-ports-adonet-v12.md)
* Service: **sql-database**
* GitHub Login: @MightyPen
* Microsoft Alias: **genemi**

**Comment by MightyPen** [comment]
#please-close
.
@masashimi Hello masashimi,
.
In the English edition of this article, I find no such link.  Instead, I find the updated similar link:
- [https://techcommunity.microsoft.com/t5/DataCAT/Connect-to-Azure-SQL-Database-V12-via-Redirection/ba-p/305362](https://techcommunity.microsoft.com/t5/DataCAT/Connect-to-Azure-SQL-Database-V12-via-Redirection/ba-p/305362)
This change in the English edition was merged on 2019-02-27, which was less than one month ago.

.
It takes weeks for our Localization systems to make the same changes in all the non-English editions of the same article.  I presume that sometimes it can take longer, depending on a lot of factors.  I have reason to expect that the changed link is coming to the Japanese article fairly soon.
I now consider this Issue 2230 to be Completed, and now Close-able.
.
I will notify our Localization team about this Issue 2230, just in case there is more to say about this Issue.
.
@nokura If anything I have said here about our Localization is incorrect, feel free to add a comment to 'masashimi' to clarify.
.
Thank you for noticing the link problem, and for communication with us!   :-) 
.
#please-close
