### ISSUE TITLE
typo: Set-AStorageAccount

### ISSUE THREAD

**Issue by ypresto** [MicrosoftDocs/azure-docs.ja-jp#2238]
Set-AStorageAccountはSet-AzStorageAccountの誤りのようです

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 78396448-24ca-f8ee-c53e-0ed5cef029d1
* Version Independent ID: eb7557bb-546b-b044-19c2-cf9e3bd82272
* Content: [Azure Storage アカウントのカスタム ドメイン名の構成](https://docs.microsoft.com/ja-jp/azure/storage/blobs/storage-custom-domain-name#feedback)
* Content Source: [articles/storage/blobs/storage-custom-domain-name.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/storage/blobs/storage-custom-domain-name.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by CeciAc** [comment]
こんにちは、@ypresto

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@ypresto

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/storage/blobs/storage-custom-domain-name#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
