### ISSUE TITLE
Out of date information

### ISSUE THREAD

**Issue by JasonWHowell** [MicrosoftDocs/azure-docs.ja-jp#2243]
From public feedback, we learned this page is out of date from the English version. Especially the table entry on Apache Kafka has incorrect version numbers. Can this page please be synchronized with the En-us version?

For example, this line is different, as 0.10.1 is no longer supported.
Japanese:
> Apache Kafka | 1.1 | 1.1、1.0、0.10.1

English:
> Apache Kafka | 1.1 | 1.1, 1.0 * (See Note below)
>
> Note:
> Due to system performance considerations, support for Kafka version 0.10 was expired in March 2019.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: af6ae544-80bf-209a-9de5-63153fd47ab5
* Version Independent ID: c70f7c14-6c10-a3e3-8593-8ec63b7fabe2
* Content: [Apache Hadoop コンポーネントおよびバージョン - Azure HDInsight](https://docs.microsoft.com/ja-jp/azure/hdinsight/hdinsight-component-versioning?toc=%2Fja-jp%2Fazure%2Fhdinsight%2Fkafka%2FTOC.json&bc=%2Fja-jp%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [articles/hdinsight/hdinsight-component-versioning.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/hdinsight/hdinsight-component-versioning.md)
* Service: **hdinsight**
* GitHub Login: @kkampf
* Microsoft Alias: **kakampf**

**Comment by CeciAc** [comment]
Hello, @JasonWHowell 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by JasonWHowell** [comment]
@CeciAc any updates? Is this a sync issue for one file, or all files perhaps?

**Comment by CeciAc** [comment]
Hello, @JasonWHowell

Thank you for your feedback.

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by ishasahni1** [comment]
@JasonWHowell this file is under localization and will be back on April 5th. 

@CeciAc FYI

**Comment by CeciAc** [comment]
Hello, @JasonWHowell 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/hdinsight/hdinsight-component-versioning?toc=%2Fja-jp%2Fazure%2Fhdinsight%2Fkafka%2FTOC.json&bc=%2Fja-jp%2Fazure%2Fbread%2Ftoc.json

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
