### ISSUE TITLE
Translation Issue

### ISSUE THREAD

**Issue by nmikuni** [MicrosoftDocs/azure-docs.ja-jp#2252]
https://docs.microsoft.com/ja-jp/azure/virtual-machines/troubleshooting/reset-network-interface#for-vms-deployed-in-resource-group-model
9. マシンへの RDP を試します。 成功した場合は、いつでも元のプライベート IP アドレスに戻すことができます。 それ以外の場合は、そのまま保持できます。

とありますが、「それ以外の場合は」の意味が不明瞭です。原文の意味を踏襲すると「戻す必要のない場合は」が適切かと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3e8d339-e4ac-d208-fc3a-871d453e0694
* Version Independent ID: 884970d8-fe56-1d5a-8e4f-85ca5e23edad
* Content: [Azure Windows VM のネットワーク インターフェイスをリセットする方法](https://docs.microsoft.com/ja-jp/azure/virtual-machines/troubleshooting/reset-network-interface#for-vms-deployed-in-resource-group-model)
* Content Source: [articles/virtual-machines/troubleshooting/reset-network-interface.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/troubleshooting/reset-network-interface.md)
* Service: **virtual-machines-windows**
* GitHub Login: @genlin
* Microsoft Alias: **genli**

**Comment by CeciAc** [comment]
こんにちは、@nmikuni 

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-machines/troubleshooting/reset-network-interface#for-vms-deployed-in-resource-group-model

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
