### ISSUE TITLE
Typo in Japanese Document

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2259]
Please fix to Azure

Microsoft には、【Azur】 をサポートしている物理的な施設の設計、建設、および運営を一手に引き受けている部門があります。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bc69e9dd-1b65-97c9-eb81-445dc21a3e2b
* Version Independent ID: 48e0aa8e-507c-5793-9ae0-83c9081022db
* Content: [Azure の施設、建物、および物理上のセキュリティ](https://docs.microsoft.com/ja-jp/azure/security/azure-physical-security)
* Content Source: [articles/security/azure-physical-security.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/security/azure-physical-security.md)
* Service: **security**
* GitHub Login: @TerryLanfear
* Microsoft Alias: **terrylan**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/security/azure-physical-security

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
