### ISSUE TITLE
Please fix some typo for Japanese document

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2279]
Please consider to fix the Japanese translation of following part
https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-restore-files-from-vm#dynamic-disks

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 142ddb2b-65ef-10f4-0e68-f9af6f0e3d52
* Version Independent ID: 74e33ef9-9a43-8ae6-abbd-a84f1cf91a25
* Content: [Azure Backup: Azure VM のバックアップからファイルとフォルダーを回復する](https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-restore-files-from-vm#dynamic-disks)
* Content Source: [articles/backup/backup-azure-restore-files-from-vm.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/backup/backup-azure-restore-files-from-vm.md)
* Service: **backup**
* GitHub Login: @pvrk
* Microsoft Alias: **pvrk**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-restore-files-from-vm#dynamic-disks

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
