### ISSUE TITLE
Overview diagram in Japanese

### ISSUE THREAD

**Issue by satonaoki** [MicrosoftDocs/azure-docs.ja-jp#231]
https://docs.microsoft.com/ja-jp/azure/machine-learning/machine-learning-studio-overview-diagram

There is an image of the overview diagram in Japanese:

https://docs.microsoft.com/ja-jp/azure/machine-learning/media/machine-learning-studio-overview-diagram/ml_studio_overview_v1.1.png

However, download link is for the diagram in English:

http://download.microsoft.com/download/C/4/6/C4606116-522F-428A-BE04-B6D3213E9E52/ml_studio_overview_v1.1.pdf

**Comment by ericvt** [comment]
the localized diagrams are not uploaded to the download center - @SunnyDeng please close
