### ISSUE TITLE
The table in the bindings section is broken

### ISSUE THREAD

**Issue by geforce-hisa0904** [MicrosoftDocs/azure-docs.ja-jp#2333]
The table in the bindings section is broken.
Could you confirm it?

![bind_table](https://user-images.githubusercontent.com/41225399/55376964-e7203080-554d-11e9-9d63-842bc6937522.PNG)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7aff040c-9c09-c184-d0e7-fb3bbb80ceec
* Version Independent ID: 68d924e7-7b32-fb1b-44eb-efc116da63ab
* Content: [Azure Functions の開発に関するガイダンス](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-reference)
* Content Source: [articles/azure-functions/functions-reference.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-functions/functions-reference.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by CeciAc** [comment]
Hello, @geforce-hisa0904 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@ishasahni1 I'm assigning this to you since it's the same issue we had with https://github.com/MicrosoftDocs/azure-docs.nl-nl/issues/233
Kind regards,
Microsoft DOCS International Team

**Comment by ishasahni1** [comment]
@geforce-hisa0904 @CeciAc  we are going to work on getting this file localized and address the format issue. Thank you so much for reporting this issue.

**Comment by geforce-hisa0904** [comment]
Hello, @CeciAc, @ishasahni1 
I found that this page is already fixed. (I don't know when fixed.) Therefore, I guess that this issues can close. May I close this issue?
Thanks,

**Comment by ishasahni1** [comment]
@geforce-hisa0904 this page has been localized and published yesterday. Thank you for keeping a track on it. Once again really appreciate all your feedback.

@CeciAc please feel free to close this issue.
