### ISSUE TITLE
TOC for Congitive Services

### ISSUE THREAD

**Issue by satonaoki** [MicrosoftDocs/azure-docs.ja-jp#240]
TOCs for Cognitive Services are missing:

https://docs.microsoft.com/ja-jp/azure/cognitive-services/academic-knowledge/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/bing-autosuggest/get-suggested-search-terms
https://docs.microsoft.com/ja-jp/azure/cognitive-services/bing-image-search/search-the-web
https://docs.microsoft.com/ja-jp/azure/cognitive-services/bing-news-search/search-the-web
https://docs.microsoft.com/ja-jp/azure/cognitive-services/speech/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/bing-spell-check/proof-text
https://docs.microsoft.com/ja-jp/azure/cognitive-services/bing-video-search/search-the-web
https://docs.microsoft.com/ja-jp/azure/cognitive-services/bing-web-search/search-the-web
https://docs.microsoft.com/ja-jp/azure/cognitive-services/computer-vision/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/content-moderator/overview
https://docs.microsoft.com/ja-jp/azure/cognitive-services/emotion/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/entitylinking/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/face/overview
https://docs.microsoft.com/ja-jp/azure/cognitive-services/kes/overview
https://docs.microsoft.com/ja-jp/azure/cognitive-services/linguisticanalysisapi/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/luis/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/qnamaker/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/recommendations/overview
https://docs.microsoft.com/ja-jp/azure/cognitive-services/speaker-recognition/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/text-analytics/overview
https://docs.microsoft.com/ja-jp/azure/cognitive-services/translator/translator-info-overview
https://docs.microsoft.com/ja-jp/azure/cognitive-services/video/home
https://docs.microsoft.com/ja-jp/azure/cognitive-services/web-language-model/home

**Comment by SunnyDeng** [comment]
@satonaoki, could you please check again? If repro, please reactivate it.
