### ISSUE TITLE
Japanese translation error

### ISSUE THREAD

**Issue by mattu0119** [MicrosoftDocs/azure-docs.ja-jp#2400]
[フィードバックをこちらに入力してください]
Azure Stack multi node miss-translated to ”Azure Stack マルチモード”. Correct word is "Azure Stack マルチノード".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b14e407-99cc-16f2-2adc-06cc32694bc1
* Version Independent ID: 0a4c4efa-4979-f7d0-9711-3afeb246072d
* Content: [Azure Stack 使用状況データの Azure への報告](https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-usage-reporting#feedback)
* Content Source: [articles/azure-stack/azure-stack-usage-reporting.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-stack/azure-stack-usage-reporting.md)
* Service: **azure-stack**
* GitHub Login: @sethmanheim
* Microsoft Alias: **sethm**

**Comment by CeciAc** [comment]
Hello, @mattu0119 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @mattu0119 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/azure-stack/azure-stack-usage-reporting

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
