### ISSUE TITLE
<insert-key> is not found in interactiveSearch.html

### ISSUE THREAD

**Issue by anishi1222** [MicrosoftDocs/azure-docs.ja-jp#2468]
Hi,

&lt;Your Azure Maps Key&gt; instead of &lt;insert-key&gt; is found in interactiveSearch.html.
Japanese translation might be based on out of date content.
Could you please catch up with the latest content?

Background of this report
The 3rd statement in the following URL says like this.
https://docs.microsoft.com/ja-jp/azure/azure-maps/quick-demo-map-app#download-the-application

"&lt;insert-key&gt; という文字列を検索します。"

But, the same statement in English version says correctly.
https://docs.microsoft.com/en-us/azure/azure-maps/quick-demo-map-app#download-the-application

"Search for the string &lt;Your Azure Maps Key&gt;. "

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3d455c9-d5c7-3a9e-5de5-b16072f3c77e
* Version Independent ID: d0f120b2-5ef9-9112-d17f-e8b2275ed5b4
* Content: [Azure Maps を使った対話型のマップ検索](https://docs.microsoft.com/ja-jp/azure/azure-maps/quick-demo-map-app#download-the-application)
* Content Source: [articles/azure-maps/quick-demo-map-app.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-maps/quick-demo-map-app.md)
* Service: **azure-maps**
* GitHub Login: @walsehgal
* Microsoft Alias: **v-musehg**

**Comment by CeciAc** [comment]
Hello, @anil0225 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @anil0225

Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/azure-maps/quick-demo-map-app#download-the-application

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
