### ISSUE TITLE
Image not displayed

### ISSUE THREAD

**Issue by konabuta** [MicrosoftDocs/azure-docs.ja-jp#2473]
Image is not displayed in Japanese page. Please check this.

[![M機械学習解釈可能性のアーキテクチャ](./media/machine-learning-interpretability-explainability/interpretability-architecture.png)](./media/machine-learning-interpretability-explainability/interpretability-architecture.png#lightbox)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4b7a36f9-6a41-1105-2853-9353a64fac16
* Version Independent ID: ab8c2ae0-b280-0b45-31a0-a6b313e8195d
* Content: [モデルの解釈可能性 - Azure Machine Learning service](https://docs.microsoft.com/ja-jp/azure/machine-learning/service/machine-learning-interpretability-explainability?view=azuremgmtcompute-fluent-1.0.0)
* Content Source: [articles/machine-learning/service/machine-learning-interpretability-explainability.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/machine-learning/service/machine-learning-interpretability-explainability.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @mesameki
* Microsoft Alias: **mesameki**

**Comment by CeciAc** [comment]
Hello, @konabuta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @konabuta

Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/machine-learning/service/machine-learning-interpretability-explainability?view=azuremgmtcompute-fluent-1.0.0

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
