### ISSUE TITLE
Mismatch between English and Japanese

### ISSUE THREAD

**Issue by kenzoohba80** [MicrosoftDocs/azure-docs.ja-jp#2474]
Feedback for translation from English to Japanese

冒頭の "開始する前に" の項目にある 2 行目は、英語では以下の記載があり、
　An Azure AD directory - either synchronized with an on-premises directory or a cloud-only directory.
日本語訳では以下のとおりであった。
　オンプレミス ディレクトリまたはクラウド専用ディレクトリのいずれかと同期されている Azure AD ディレクトリ 。

こちら、確認したところ真意としては、オンプレミスから同期された Azure AD、もしくは 同期がされていないクラウド環境のみの Azure AD であるということなので、日本語の修正をして頂きますよう、お願い申し上げます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 765c2f63-0de1-9283-b9dd-8fda690b0765
* Version Independent ID: 18c8f603-7953-7885-4ff5-6bd63cb4994e
* Content: [Azure Active Directory Domain Services:はじめに](https://docs.microsoft.com/ja-jp/azure/active-directory-domain-services/active-directory-ds-getting-started)
* Content Source: [articles/active-directory-domain-services/active-directory-ds-getting-started.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory-domain-services/active-directory-ds-getting-started.md)
* Service: **active-directory**
* Sub-service: **domain-services**
* GitHub Login: @eringreenlee
* Microsoft Alias: **ergreenl**

**Comment by CeciAc** [comment]
こんにちは、@kenzoohba80

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@kenzoohba80
フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/active-directory-domain-services/active-directory-ds-getting-started 

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
