### ISSUE TITLE
Japanese Title

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2475]
I think just add '-(dash)' between the JPN and ENG title would be fine personally.....
Currently, localized title contains the Original English title with localized title.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0f2b93a5-28b8-db4a-ab64-6342d3aafc63
* Version Independent ID: 245586f2-63e1-1e78-a5dd-21e8fa2cc5d3
* Content: [Azure Cosmos のコンテナーとデータベースでスループットをプロビジョニングする](https://docs.microsoft.com/ja-jp/azure/cosmos-db/set-throughput)
* Content Source: [articles/cosmos-db/set-throughput.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cosmos-db/set-throughput.md)
* Service: **cosmos-db**
* GitHub Login: @rimman
* Microsoft Alias: **rimman**

**Comment by rimman** [comment]
@KeiroKamioka0000 I am not sure I understand the ask here. @SnehaGunda could you please help here. thank you.

**Comment by KeiroKamioka0000** [comment]
@rimman 
Please check actual localized document please.
The current title is "コンテナーとデータベースのスループットのプロビジョニングProvision throughput on containers and databases"

Which is form of <LocalizedTitle><OriginalTitle> without the space between.

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/cosmos-db/set-throughput

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
