### ISSUE TITLE
Typo in Japanese Localized String

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2478]
"セールス エーエージェント" should be "セールス エージェント"
Strongly assumed to be typo.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: edda1fe4-6ce9-ccf2-bc1b-65e9818b1060
* Version Independent ID: 5151901d-a4d3-1148-811f-8c9a959608a3
* Content: [前払いで Azure 仮想マシンのコストを削減する](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/prepay-reserved-vm-instances#change-a-reservation-after-purchase)
* Content Source: [articles/virtual-machines/windows/prepay-reserved-vm-instances.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/prepay-reserved-vm-instances.md)
* Service: **virtual-machines-windows**
* GitHub Login: @yashar
* Microsoft Alias: **banders**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000

Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/prepay-reserved-vm-instances#change-a-reservation-after-purchase

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
