### ISSUE TITLE
Japanese Localized Title contains the Original English Title

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2480]
As I can see in every Japanese localized Document, the title within the document is followed by Original English Title.
As example "Azure セキュリティの概要Introduction to Azure Security"

Please consider to fix

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ce94e95d-f2df-72de-66d0-56930547ee98
* Version Independent ID: 8d258a24-3bd7-dd4e-db41-9cfea8d077ee
* Content: [Azure Security の概要](https://docs.microsoft.com/ja-jp/azure/security/azure-security)
* Content Source: [articles/security/azure-security.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/security/azure-security.md)
* Service: **security**
* GitHub Login: @unifycloud
* Microsoft Alias: **TomSh**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/security/azure-security

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
