### ISSUE TITLE
Managed Disk and Japanese Localize name for Managed Disk

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2483]
マネージドディスクの日本語訳として管理ディスクという呼称が用いられておりますが……
ドキュメントによって、マネージドディスクと管理ディスクの両方の呼称が用いられている状況です。

どちらかに呼称を統一する事は可能でしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 263abdef-3478-8261-6c4c-5d608698ba4e
* Version Independent ID: 61ef3094-fda7-d7b9-e19c-4e8f6a5b2f2d
* Content: [Azure IaaS Windows VM ディスクについてよく寄せられる質問 (FAQ)](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/faq-for-disks#new-disk-sizes-managed-and-unmanaged)
* Content Source: [articles/virtual-machines/windows/faq-for-disks.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/faq-for-disks.md)
* Service: **virtual-machines-windows**
* Sub-service: **disks**
* GitHub Login: @roygara
* Microsoft Alias: **rogarana**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000
フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました:  https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/faq-for-disks#new-disk-sizes-managed-and-unmanaged

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
