### ISSUE TITLE
docker login error on PowerShell

### ISSUE THREAD

**Issue by ssashir06** [MicrosoftDocs/azure-docs.ja-jp#2489]
```
$creds.Password | docker login $registry.LoginServer -u $creds.Username --password-stdin
```
This line fails on PowerShell with "unauthorized: incorrect username or password" error.

```
docker login $registry.LoginServer -u $creds.Username -p $creds.Password
```
Instead, this line successes (with a warning "WARNING! Using --password via the CLI is insecure. Use --password-stdin.")

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a14aeed3-ac3d-10b7-6810-9480d13b3169
* Version Independent ID: c7868ac5-369f-8e8b-1339-af040cd9e5c7
* Content: [クイック スタート - Azure でのプライベート Docker レジストリの作成 - PowerShell](https://docs.microsoft.com/ja-jp/azure/container-registry/container-registry-get-started-powershell#feedback)
* Content Source: [articles/container-registry/container-registry-get-started-powershell.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/container-registry/container-registry-get-started-powershell.md)
* Service: **container-registry**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #29824](https://github.com/MicrosoftDocs/azure-docs/issues/29824) via [**ZenHub**](https://www.zenhub.com/)
