### ISSUE TITLE
「管理ID」と「マネージドID」

### ISSUE THREAD

**Issue by 4416km** [MicrosoftDocs/azure-docs.ja-jp#2495]
意図的に使い分けているのでしょうか？とても分かりにくく感じます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f3dc128b-0ee5-1344-0034-2fce6960daa4
* Version Independent ID: b2499482-1101-4937-7f34-ad7b9fd9fdc4
* Content: [Azure リソースの Azure Active Directory 管理 ID を持つ blob およびキューへのアクセスの認証 - Azure Storage](https://docs.microsoft.com/ja-jp/azure/storage/common/storage-auth-aad-msi?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json#feedback)
* Content Source: [articles/storage/common/storage-auth-aad-msi.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/storage/common/storage-auth-aad-msi.md)
* Service: **storage**
* Sub-service: **common**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by CeciAc** [comment]
こんにちは、@4416km

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@4416km

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@4416km

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/storage/common/storage-auth-aad-msi?toc=%2Fazure%2Fstorage%2Fblobs%2Ftoc.json  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
