### ISSUE TITLE
named location

### ISSUE THREAD

**Issue by selmertsx** [MicrosoftDocs/azure-docs.ja-jp#2503]
「名前付きの場所」という言葉はいささか分かりにくいので、英語版のドキュメントと同じように 「named location」という言葉を使われてはいかがでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 85e48aef-a7bc-38e2-f762-0162e154a6c4
* Version Independent ID: 6f37ac44-d5b8-5cce-ee0e-e31d1d6c863a
* Content: [Azure Active Directory で名前付きの場所を構成する](https://docs.microsoft.com/ja-jp/azure/active-directory/reports-monitoring/quickstart-configure-named-locations)
* Content Source: [articles/active-directory/reports-monitoring/quickstart-configure-named-locations.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/reports-monitoring/quickstart-configure-named-locations.md)
* Service: **active-directory**
* Sub-service: **report-monitor**
* GitHub Login: @MarkusVi
* Microsoft Alias: **markvi**

**Comment by selmertsx** [comment]
フィードバックフォームについてのフィードバックです。

日本語のタイトルでは送信ができず、また「指定されている形式で入力してください」とのことですが、形式が指定されている場所が見当たりませんでした。なので、日本語のタイトルは受け付けていないという旨を記載していただけるとありがたいです！

<img width="968" alt="スクリーンショット 2019-04-24 16 15 14" src="https://user-images.githubusercontent.com/1563239/56639791-75e71f80-66ac-11e9-9c3e-903ac2761be1.png">

**Comment by CeciAc** [comment]
こんにちは、@selmertsx

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @ishasahni1 
We are working on the localization issue on the page, but please check the second comment from the user. They report they cannot place the Issue's title in Japanese.

**Comment by CeciAc** [comment]
こんにちは、@selmertsx

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

Hi @ishasahni1
We are working on the localization issue on the page, but please check the second comment from the user. They report they cannot place the Issue's title in Japanese.

**Comment by ishasahni1** [comment]
@bodhigautam can you kindly look into the second comment from customer. The comment is about the GitHub Issues functionality, which apparently doesn’t allow to enter a full Japanese title for the issue with a message that says the format is wrong but they cannot fin anywhere instructions about the required format.

**Comment by bodhigautam** [comment]
@ishasahni1 @CeciAc Thanks for adding me. Can you tell me the title in Japanese that they are entering and the repro steps ?

**Comment by CeciAc** [comment]
Hi @bodhigautam 
I tried myself and any Japanese text shows the error message. (unless you also add non-japanese text)
![imagen](https://user-images.githubusercontent.com/26746247/57798992-73646c80-7724-11e9-9e3b-3b7e1ab80460.png)

We already fixed the Localization issue, should I leave this open so you can work on that technical issue or will you move it somewhere else?

**Comment by CeciAc** [comment]
こんにちは、@selmertsx

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/active-directory/reports-monitoring/quickstart-configure-named-locations 

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team

**Comment by ishasahni1** [comment]
@CeciAc please keep this issue open as we would like to address the engineering issue here itself.

@bodhigautam please let us know if you need further info. You can find some details in screenshot above in this issue.

**Comment by bodhigautam** [comment]
@ishasahni1 @CeciAc I just now created an issue with Japanese title and content and it got create successfully. Can you tell me the repro steps so that I can produce it on my end ? https://github.com/MicrosoftDocs/azure-docs.ja-jp/issues/2531

**Comment by ishasahni1** [comment]
@selmertsx can you kindly provide the steps as to in what step you are not able to create Title so we can try those steps on our end and see if issue repros.

@CeciAc @bodhigautam

**Comment by CeciAc** [comment]
@bodhigautam 
1. At the bottom on the page, click on the right button:
![imagen](https://user-images.githubusercontent.com/26746247/57886267-33c08200-7803-11e9-866b-9bacf42d6cb3.png)

2. Write any text in japanese or copy paste from the page and click on the button to create the ticket
![imagen](https://user-images.githubusercontent.com/26746247/57886452-a0d41780-7803-11e9-897d-12ff1de0d543.png)

3. The "title" field highlights with a red border and the ticket is not created unless you add non-japanese text.

**Comment by bodhigautam** [comment]
@CeciAc thanks so much. I can repro it now. I will open a bug for the engineering team.

**Comment by bodhigautam** [comment]
@CeciAc @ishasahni1 This has been resolved now. Please verify and close this thread at your convenience.

**Comment by CeciAc** [comment]
こんにちは、@selmertsx
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/active-directory/reports-monitoring/quickstart-configure-named-locations 
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team

**Comment by selmertsx** [comment]
@CeciAc 
遅くなりましたが、フィードバックを採用していただきましてありがとうございました！
