### ISSUE TITLE
オンプレミスのActiveDirectoryが存在しない環境での、オンプレミスのWindowsサーバーOSへのログインID認証

### ISSUE THREAD

**Issue by taclow** [MicrosoftDocs/azure-docs.ja-jp#2504]
オンプレミスのActiveDirectoryが存在しない環境で、オンプレミスのWindowsサーバーOSへログインするID管理Azure Active Directoryを使用することは可能でしょうか？このページの記述はオンプレミスのActive Directoryが存在する前提で記述されている気がするのですが、左記のようなことができるのか、やるとしたらオンプレミスとAzureの間でどのような接続の仕方が必要か、教えていただけますでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 278fd397-b3b7-5192-47ff-b5c9edfa44b4
* Version Independent ID: 9ca42ebd-4ff2-226f-8bae-74fc8973a825
* Content: [Azure Active Directory とは - Azure Active Directory](https://docs.microsoft.com/ja-jp/azure/active-directory/fundamentals/active-directory-whatis#feedback)
* Content Source: [articles/active-directory/fundamentals/active-directory-whatis.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/fundamentals/active-directory-whatis.md)
* Service: **active-directory**
* GitHub Login: @eross-msft
* Microsoft Alias: **lizross**

**Comment by CeciAc** [comment]
こんにちは、@taclow
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
