### ISSUE TITLE
Inconsistent description

### ISSUE THREAD

**Issue by github129** [MicrosoftDocs/azure-docs.ja-jp#2509]
[フィードバックをこちらに入力してください]
Hello
Description of dataUriToBinary() and decodeDataUri() is inconsistent
Should we choose dataUriToBinary() or decodeDataUri()?

>dataUriToBinary
Return the binary version for a data uniform resource identifier (URI). Use this function rather than decodeDataUri(). Although both functions work the same way, decodeDataUri() is preferred.

>decodeDataUri
Return the binary version for a data uniform resource identifier (URI). Consider using dataUriToBinary(), rather than decodeDataUri(). Although both functions work the same way, dataUriToBinary() is preferred.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 03aa9e88-7fa0-56ab-f794-58f0c37b6d7a
* Version Independent ID: 25c5ef5c-6ba4-f5ff-f94b-8f2818ec2feb
* Content: [ワークフロー定義言語の関数のリファレンス - Azure Logic Apps と Microsoft Flow](https://docs.microsoft.com/ja-jp/azure/logic-apps/workflow-definition-language-functions-reference#feedback)
* Content Source: [articles/logic-apps/workflow-definition-language-functions-reference.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/logic-apps/workflow-definition-language-functions-reference.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30101](https://github.com/MicrosoftDocs/azure-docs/issues/30101) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @github129 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/30101

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
