### ISSUE TITLE
日本語ドキュメントにHTMLエラーか

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2516]
修正をお願いします。

https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-backup-faq#if-each-recovery-point-is-like-a-full-point-does-it-impact-the-total-billable-backup-storage

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: efe1b860-8d24-1742-4f20-c3e75cacbba3
* Version Independent ID: 2ac226c0-df97-f729-fe09-3d51d61b9083
* Content: [Azure Backup の FAQ](https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-backup-faq#if-each-recovery-point-is-like-a-full-point-does-it-impact-the-total-billable-backup-storage)
* Content Source: [articles/backup/backup-azure-backup-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/backup/backup-azure-backup-faq.md)
* Service: **backup**
* GitHub Login: @rayne-wiselman
* Microsoft Alias: **raynew**

**Comment by CeciAc** [comment]
@KeiroKamioka0000  様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
@KeiroKamioka0000 様、
先にお送りしたコメントについてさらにお知らせいたします。お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by CeciAc** [comment]
@KeiroKamioka0000 様、
再度コメントをいただき、ありがとうございます。
大変申し訳ございませんが、いただいたフィードバックを処理するには、依然として情報が不足しております。この度いただいた GitHub の問題はここで終了とさせていただきますが、今後とも、さらにフィードバックをお寄せいただきますよう、お願い申し上げます。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by KeiroKamioka0000** [comment]
@CeciAc 

I assume these parts supposed HTML error or something.

![image](https://user-images.githubusercontent.com/37641695/57736775-1605e800-765e-11e9-8418-7c8305cfab2e.png)

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #31512](https://github.com/MicrosoftDocs/azure-docs/issues/31512) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (XXX) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
