### ISSUE TITLE
「Splunk と Azure Monitor ログ クエリ」のリンク間違い

### ISSUE THREAD

**Issue by ypresto** [MicrosoftDocs/azure-docs.ja-jp#2520]
「SQL と Azure Monitor ログ クエリ」の方にリンクされています

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2f2a1786-eaa0-89da-d3e2-bf5eddad50ec
* Version Independent ID: e490f534-b0ce-612a-2bbb-3532326879e4
* Content: [Azure Monitor ログ クエリ](https://docs.microsoft.com/ja-jp/azure/azure-monitor/log-query/query-language#feedback)
* Content Source: [articles/azure-monitor/log-query/query-language.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/log-query/query-language.md)
* Service: **log-analytics**
* GitHub Login: @bwren
* Microsoft Alias: **bwren**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #30990](https://github.com/MicrosoftDocs/azure-docs/issues/30990) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@ypresto
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/azure-docs/issues/30990 を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
