### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by kinoshitahiroyuki** [MicrosoftDocs/azure-docs.ja-jp#2521]
左上の「Durable Functionsのドキュメント」がリンク切れしています。
URLを確認したところローカライズの部分が2重になっているようです。
https://docs.microsoft.com/ja-jp/ja-jp/azure/azure-functions/durable/durable-functions-overview

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b934ad1d-aabb-707d-d296-02cfbb22ec5c
* Version Independent ID: 5d8f8cfb-be79-fac8-62ef-3a396a3be3e8
* Content: [Durable Functions の概要 - Azure](https://docs.microsoft.com/ja-jp/azure/azure-functions/durable/durable-functions-overview)
* Content Source: [articles/azure-functions/durable/durable-functions-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/durable/durable-functions-overview.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **azfuncdf, glenga**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #31114](https://github.com/MicrosoftDocs/azure-docs/issues/31114) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@kinoshitahiroyuki
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/azure-docs/issues/31114 を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
