### ISSUE TITLE
入力イベントに関して情報が不足している-Lack of localization string

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2526]
入力イベントに関して、英語原文で存在する情報が欠落しているため修正を要請いたします。

For the Japanese Input Events localized String, it lack of information exist in Original English Strings.
Information of above is missing.
"This count does not include incoming events that result in deserialization errors."

Number of records deserialized from the input events. This count does not include incoming events that result in deserialization errors.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 329b82e4-391b-f1c1-21f7-03eff5635145
* Version Independent ID: acda621d-0edd-0525-4365-d3ff9db3f458
* Content: [Azure Stream Analytics でのジョブ監視について](https://docs.microsoft.com/ja-jp/azure/stream-analytics/stream-analytics-monitoring#metrics-available-for-stream-analytics)
* Content Source: [articles/stream-analytics/stream-analytics-monitoring.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/stream-analytics/stream-analytics-monitoring.md)
* Service: **stream-analytics**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by KeiroKamioka0000** [comment]
<Input Source Received>に関しても英語版と比べ情報が欠落しているようです。

よろしくお願いいたします。

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/stream-analytics/stream-analytics-monitoring#metrics-available-for-stream-analytics 
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
