### ISSUE TITLE
az postgres server create

### ISSUE THREAD

**Issue by utopianf** [MicrosoftDocs/azure-docs.ja-jp#2527]
az postgres server create --resource-group myResourceGroup --name &lt;postgresql-name&gt; --location "West Europe" --admin-user &lt;admin-username&gt; --admin-password &lt;admin-password&gt; --sku-name B_Gen4_1

で
Deployment failed. Correlation ID: fde44886-a838-4b8e-bf25-45c98fb2aa97. Gen4 hardware is not supported for this region.
が出てきます。sku-nameの候補を見るにはどうすれば良いんですか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 791bd216-532f-7f28-fa51-d95798397310
* Version Independent ID: 4f7ff676-e4a5-cc41-6a43-ecb8fa1095fb
* Content: [Linux 上の PostgreSQL を使用した Python (Django) - Azure App Service](https://docs.microsoft.com/ja-jp/azure/app-service/containers/tutorial-python-postgresql-app#feedback)
* Content Source: [articles/app-service/containers/tutorial-python-postgresql-app.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/app-service/containers/tutorial-python-postgresql-app.md)
* Service: **app-service-web**
* GitHub Login: @cephalin
* Microsoft Alias: **beverst;cephalin**

**Comment by CeciAc** [comment]
こんにちは、@utopianf
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
