### ISSUE TITLE
Wrong translation for "Storage Spaces"

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#2528]
Currently "Storage Spaces" in the table in "Replicated machines - storage" section is translated to "記憶域" - the current translation means "storage". Actually its source "(Windows) Storage Spaces" is a feature of Windows so the current translation is wrong and it should be translated as the feature name ("記憶域スペース").  

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 34d0f2df-de85-c6ab-eb01-f8e028b7f108
* Version Independent ID: 5acb187c-f280-5c7d-14fc-7f07160cd50b
* Content: [Azure Site Recovery を使用した Azure リージョン間での Azure VM のディザスター リカバリーに関するサポート マトリックス](https://docs.microsoft.com/ja-jp/azure/site-recovery/azure-to-azure-support-matrix#replicated-machines---storage)
* Content Source: [articles/site-recovery/azure-to-azure-support-matrix.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/site-recovery/azure-to-azure-support-matrix.md)
* Service: **site-recovery**
* GitHub Login: @rayne-wiselman
* Microsoft Alias: **raynew**

**Comment by CeciAc** [comment]
Hello, @kazshi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kazshi
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/site-recovery/azure-to-azure-support-matrix#replicated-machines---storage

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
