### ISSUE TITLE
Please fix Japanese Localized String Please

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2530]
以下項目は機械翻訳の影響か日本語の文法としては少々おかしくなっておりますので修正をお願いします。
最後にアラートの１文字のみの文章等が見受けられます。

新旧のアラート機能
https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/alerts-classic.overview#old-and-new-alerting-capabilities

Azure Monitor、Application Insights、Log Analytics、Service Health のアラート機能は以前は別々でした。 Azure では、ユーザー インターフェイスとさまざまなアラート方法が時間と共に統合され、改善されました。 この統合は現在も継続中です。 アラート

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5387f7e8-e928-4728-0990-69da374e1a96
* Version Independent ID: d7eaf979-56d4-73b8-a8f8-9cbb4fb0f3c6
* Content: [Microsoft Azure と Azure Monitor でのクラシック アラートの概要](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/alerts-classic.overview#old-and-new-alerting-capabilities)
* Content Source: [articles/azure-monitor/platform/alerts-classic.overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/alerts-classic.overview.md)
* Service: **azure-monitor**
* GitHub Login: @rboucher
* Microsoft Alias: **robb**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #31498](https://github.com/MicrosoftDocs/azure-docs/issues/31498) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (XXX) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
