### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2532]
ステップ倍ステップ is typo
It should be ステップ・バイ・ステップ or ステップバイステップ or Aleternate Appropriate Japannese word.

Thanks,

-Keiro

カスタム ロールの作成手順
https://docs.microsoft.com/ja-jp/azure/role-based-access-control/custom-roles#steps-to-create-a-custom-role

カスタム ロールの作成方法に関するステップ倍ステップのチュートリアルが必要な場合は、「チュートリアル: Azure PowerShell を使用してカスタム ロールを作成する」か「チュートリアル: Azure CLI を使用してカスタム ロールを作成する」を参照してください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: eac44e5e-65e1-d989-4afe-0463e8ff51d0
* Version Independent ID: 5665dd03-d06e-ca29-668f-7cb91e5f9ffd
* Content: [Azure リソースのカスタム ロール](https://docs.microsoft.com/ja-jp/azure/role-based-access-control/custom-roles#steps-to-create-a-custom-role)
* Content Source: [articles/role-based-access-control/custom-roles.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/role-based-access-control/custom-roles.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/role-based-access-control/custom-roles#steps-to-create-a-custom-role

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
