### ISSUE TITLE
Descriptions of the items for Azure portal and Developer portal in Overview section are difficult to understand

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#2536]
That's because of translation issue:
"Use it to:" and "...where they can:" and the following descriptions are not translated accurately, so they don't make sense as feature descriptions.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e4e98f59-eb03-4692-db13-ac0c61a6dd3c
* Version Independent ID: 55059f88-2aa2-b916-03e7-0589cc166555
* Content: [Azure API Management の概要と主な概念](https://docs.microsoft.com/ja-jp/azure/api-management/api-management-key-concepts#overview)
* Content Source: [articles/api-management/api-management-key-concepts.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/api-management/api-management-key-concepts.md)
* Service: **api-management**
* GitHub Login: @vladvino
* Microsoft Alias: **apimpm**

**Comment by CeciAc** [comment]
Hello, @kazshi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kazshi
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/api-management/api-management-key-concepts#overview

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
