### ISSUE TITLE
チェックマークやマイナス記号が表示されていません

### ISSUE THREAD

**Issue by yoichinak** [MicrosoftDocs/azure-docs.ja-jp#2537]
`:heavy_check_mark:` や `:heavy_minus_sign:` を記号に置き換えてください。azure ドキュメント全体でこの問題が発生しているようです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1dde985d-e35f-83a6-2765-252a0fa4fa66
* Version Independent ID: 4cd65ebc-55c0-79bf-dd13-401df5cd2aef
* Content: [言語のサポート - Cognitive Services - Azure](https://docs.microsoft.com/ja-jp/azure/cognitive-services/language-support#feedback)
* Content Source: [articles/cognitive-services/language-support.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cognitive-services/language-support.md)
* Service: **cognitive-services**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by CeciAc** [comment]
こんにちは、@yoichinak

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hi @ishasahni1 
I'm assigning this to you since it's related with **Loc Issue 91004**

**Comment by ishasahni1** [comment]
@CeciAc our engineering team is looking into this issue and will be addressed in this sprint in 1-2 weeks. Will keep you posted once Bug is resolved.

**Comment by ishasahni1** [comment]
@yoichinak this issue has been addressed now , you can see the fix reflecting live https://docs.microsoft.com/ja-jp/azure/cognitive-services/language-support

@CeciAc fyi
