### ISSUE TITLE
page title

### ISSUE THREAD

**Issue by hidwatanabe** [MicrosoftDocs/azure-docs.ja-jp#2548]
There is an incorrect kanji in this page title tag. It's not "機会学習" but "機械学習".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c8fc8bdb-1ee0-b978-e42f-de875b8cb50f
* Version Independent ID: dbad235e-f8d6-361b-d337-f9d2a3573059
* Content: [パイプライン: 機会学習ワークフローの最適化 - Azure Machine Learning service](https://docs.microsoft.com/ja-jp/azure/machine-learning/service/concept-ml-pipelines)
* Content Source: [articles/machine-learning/service/concept-ml-pipelines.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/machine-learning/service/concept-ml-pipelines.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @sanpil
* Microsoft Alias: **sanpil**

**Comment by CeciAc** [comment]
Hello, @hidwatanabe 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hidwatanabe
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/machine-learning/service/concept-ml-pipelines

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
