### ISSUE TITLE
iotedgeにおけるenvの設定について

### ISSUE THREAD

**Issue by sahya** [MicrosoftDocs/azure-docs.ja-jp#2554]
(english follows after japanese)
この手順の書き方ですと、iotedgeのConfig.yamlもしくはiothubやjsonのenvのどちらかに書けばいいように見落としてしまうため、プロキシ設定・UpstreamProtocolのセクションを作成したうえでその下に、iotedgeのConfig.yamlとiothubやjsonのenvの記載が必要と記載するか。もしくは冒頭で下記のように表組形式で事前に視覚的に伝えたほうが良いと思います。

| 設定項目    | 要設定項目1  | 要設定項目2 |
| ---------- | -------- | -------- |
| プロキシ設定 | iotedgeのConfig.yaml     | iothubやjsonのenv    |
| UpstreamProtocol | iotedgeのConfig.yaml     | iothubやjsonのenv    |

一つ、質問ですが、iothubやjsonもしくはiotedgeのなかいずれかでEnvは反映されます。
そのため、この手順で２重に設定は必要ないように感じます。最終的には、混乱を招くため１つの場所(configやjson)で設定するという手順に改善したほうが良いと思います。(英語バージョンを含む)
もし２重に設定する必要がある場合はどんなことを想定されているか、可能であればご教示いただけると幸いです。

---

In this procedure of writing, iotedge's Config.yaml has missed it on iothub and json's env, so after creating proxy settings and UpstreamProtocol settings, in iotedge's config, iotedge settings Do you need the following description of .yaml and iothub or json env? At the beginning, I think it is better to visually communicate in the form of expression as follows at the beginning.

| Setting items    | Required Setting item 1 | Required Setting item 2 |
| ---------- | -------- | -------- |
| Proxy settings| iotedge's Config.yaml    | iothub or json env  |
| UpstreamProtocol | iotedge's Config.yaml   | iothub or json env   |

One question is, Env is reflected in either iothub, json or iotedge.
Therefore, it feels like there is no need to do double setting in this procedure. In the end, I think it is better to improve on the procedure of setting in one place (config or json) to cause confusion. (Including English version)
If you need to do it in duplicate, it would be nice if you could tell us what it is supposed to do, if possible.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 69c0d8c2-ea63-1b11-d855-bc1f6108cf62
* Version Independent ID: 7c2c7ceb-ed80-f507-0c63-280720e9768d
* Content: [ネットワーク プロキシ対応のデバイスを構成する - Azure IoT Edge](https://docs.microsoft.com/ja-jp/azure/iot-edge/how-to-configure-proxy-support#feedback)
* Content Source: [articles/iot-edge/how-to-configure-proxy-support.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-edge/how-to-configure-proxy-support.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32273](https://github.com/MicrosoftDocs/azure-docs/issues/32273) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/32273

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

**Comment by sahya** [comment]
Hi @CeciAc 
Thank you for raise global issue.
> Please review the status of the issue here - MicrosoftDocs/azure-docs#32273
Its was verry good. If I feel to need more infomation. I add more information.
