### ISSUE TITLE
機械翻訳による誤訳があるので修正してください。

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2555]
以下URL箇所が参照して下さい。を参照して下さいなど、
機械翻訳の影響か非常に不明瞭な内容となっているで修正をお願いいたします。

Due to machine translation, the localized test become very strange, please fix ASAP.

フェールオーバーは自動で行われますか。
https://docs.microsoft.com/ja-jp/azure/site-recovery/site-recovery-faq#is-failover-automatic

自動化するには、オンプレミスの Orchestrator または Operations Manager を使用すると、仮想マシンのエラーを監視し、SDK を使用してフェールオーバーをトリガーできます。
こちら を参照してください。
詳細については、こちらを参照してください。 をご覧ください。
詳細については、こちらを参照してください。 を参照してください

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7a8f2ca3-19b1-330d-8dd3-6dcdce38c8d4
* Version Independent ID: 700335aa-c802-0314-1579-3493918f5000
* Content: [Azure Site Recovery:よく寄せられる質問](https://docs.microsoft.com/ja-jp/azure/site-recovery/site-recovery-faq#is-failover-automatic)
* Content Source: [articles/site-recovery/site-recovery-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/site-recovery/site-recovery-faq.md)
* Service: **site-recovery**
* GitHub Login: @rayne-wiselman
* Microsoft Alias: **raynew**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/site-recovery/site-recovery-faq#is-failover-automatic

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
