### ISSUE TITLE
誤字 Typo

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2573]
前提条件記載の文章内に誤字がございます。
本来「管理者」である必要の箇所が「理者」と文字が一時抜けております。
「グローバル管理者」へ変更いただきますようにお願いいたします。

前提条件
グローバル理者またはセキュリティ管理者のアクセス許可を持つユーザー

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f58d2fcb-0f3a-e016-e545-e3fd06e7c145
* Version Independent ID: fc638c9e-5f2b-975a-fcf9-3ea19a92fb11
* Content: [Azure Sentinel Preview に Azure アクティビティ データを接続する](https://docs.microsoft.com/ja-jp/azure/sentinel/connect-azure-activity)
* Content Source: [articles/sentinel/connect-azure-activity.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/sentinel/connect-azure-activity.md)
* Service: **sentinel**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@<共同作成者の GITHUB 名>  

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/sentinel/connect-azure-activity

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
