### ISSUE TITLE
Product name is "direct", not "Direct".

### ISSUE THREAD

**Issue by hikariru** [MicrosoftDocs/azure-docs.ja-jp#2583]
Hi.

What I want to say has been already described on #685.
Seems not the all of the "Direct" on the page replaced into "direct".

To avoid making our users confused,
would you please write "direct" with the correct case on the WHOLE page?

Thanks.

お世話になっております。

#685 にて修正依頼した際、すべての"Direct"が"direct"に置き換わっていなかったようです。

ユーザーの混乱を避けるためにもページ内すべてで正しい表記をしていただけると幸いです。

よろしくお願い申し上げます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1a402f6f-9c49-50ec-df27-fce8a17c5d44
* Version Independent ID: 960a880a-9d7a-d1f1-96cc-cf8dbe9c6c15
* Content: [チュートリアル:Azure Active Directory と Direct の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/direct-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/direct-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/saas-apps/direct-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #32879](https://github.com/MicrosoftDocs/azure-docs/issues/32879) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @hikariru 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by jeevansd** [comment]
@chetansriv and @v-viinde Can you please fix this?

**Comment by chetansriv** [comment]
@hikariru I don't see any reference of "Direct" on the page. Can you please exactly specify where do you see incorrect casing?

**Comment by hikariru** [comment]
@chetansriv 

Thank you for replying. 

You can see some "Direct" words on the "Content Source" as well.
Could you please fix the lines below?

- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L2-L3
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L27-L28
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L30-L31
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L39
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L42
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L48
https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L50
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L52
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L54
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L70
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L74-L75
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L77
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L80
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L83
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L90
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L92
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L106
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L120
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L130
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L132
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L160
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L168
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L184
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L186
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L186
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L194
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L200
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L202

Thanks.

**Comment by CeciAc** [comment]
Hello, @hikariru
Thank you for your feedback.
 
We implemented your feedback and published to the updated articles on the Docs site to the following pages .

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
