### ISSUE TITLE
AKS リージョンの可用性

### ISSUE THREAD

**Issue by 0giso** [MicrosoftDocs/azure-docs.ja-jp#2584]
URL が誤っている
https://www.azure.cn/zh-cn/home/features/products-by-region
正しくは
https://azure.microsoft.com/ja-jp/global-infrastructure/services/?products=kubernetes-service

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 18e73ba6-a06d-9bc4-fef6-6ece8a166e84
* Version Independent ID: a9efcfab-f4c5-969b-4cd4-aa86ebd80534
* Content: [Azure Kubernetes Service (AKS) のクォータ、SKU、およびリージョンの可用性](https://docs.microsoft.com/ja-jp/azure/aks/quotas-skus-regions#feedback)
* Content Source: [articles/aks/quotas-skus-regions.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/aks/quotas-skus-regions.md)
* Service: **container-service**
* GitHub Login: @rockboyfor
* Microsoft Alias: **v-yeche**

**Comment by CeciAc** [comment]
こんにちは、@0giso

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@0giso
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/aks/quotas-skus-regions#feedback
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
