### ISSUE TITLE
Line feed codes mixed in articles

### ISSUE THREAD

**Issue by shibayan** [MicrosoftDocs/azure-docs.ja-jp#259]
Line feed code is mixed in articles with LF and CR+LF.
Therefore, if I modify on github, can not see the difference.

example: https://github.com/Microsoft/azure-docs.ja-jp/pull/33/files

the original documents seems to be unified in LF, please consider it.

**Comment by SunnyDeng** [comment]
@shibayan -san, the fix was accepted and merged, please check, if it still reactivate. Thasnk!
