### ISSUE TITLE
表現を変えて欲しい

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2590]
現在、24時間体制の対応を意味している者と思われる箇所「エンジニアのチームは 24 時間休みなしで作業して、サービスを永続的に使用できることを保証します。」の表現を変えて欲しいです。
これだと、なんとなく、印象が悪く感じられます……

「休みなしで作業」以外の表現への修正を何卒ご検討お願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 172f9700-14a2-b2bc-290b-538647853c2d
* Version Independent ID: cebfcdcb-3839-9b32-70e0-49fc6cfdc69d
* Content: [Azure インフラストラクチャの可用性 - Azure セキュリティ](https://docs.microsoft.com/ja-jp/azure/security/azure-infrastructure-availability)
* Content Source: [articles/security/azure-infrastructure-availability.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/security/azure-infrastructure-availability.md)
* Service: **security**
* GitHub Login: @TerryLanfear
* Microsoft Alias: **terrylan**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/security/azure-infrastructure-availability

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
