### ISSUE TITLE
Incorrect case "Direct" is still on this page

### ISSUE THREAD

**Issue by hikariru** [MicrosoftDocs/azure-docs.ja-jp#2596]
Last time I pointed out on this comment:
https://github.com/MicrosoftDocs/azure-docs.ja-jp/issues/2583#issuecomment-499759203

Can you fix this? Correct case is "direct";
https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L83

Hope we won't be bothered by this kind of issue any more.
Thanks. 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1a402f6f-9c49-50ec-df27-fce8a17c5d44
* Version Independent ID: 960a880a-9d7a-d1f1-96cc-cf8dbe9c6c15
* Content: [チュートリアル:Azure Active Directory と Direct の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/direct-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/direct-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/saas-apps/direct-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by CeciAc** [comment]
Hello, @hikariru
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hikariru
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/master/articles/active-directory/saas-apps/direct-tutorial.md#L83

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
