### ISSUE TITLE
refresh_token が取得でき兄

### ISSUE THREAD

**Issue by ishida0219** [MicrosoftDocs/azure-docs.ja-jp#2611]
Microsoft API OAuth 2.0 を使用して @outlook.jp のアカウントの access_token を取得しているのですが、 refresh_token が取得できません。（nullになっている）。
Azure AD というのを使用しないと refresh_token は取得できないのでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2471c08b-befe-8e1a-df08-f13e116c231e
* Version Independent ID: 0d827d33-2906-6352-9398-13863def9354
* Content: [Microsoft ID プラットフォーム アクセス トークン リファレンス](https://docs.microsoft.com/ja-jp/azure/active-directory/develop/access-tokens#feedback)
* Content Source: [articles/active-directory/develop/access-tokens.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/develop/access-tokens.md)
* Service: **active-directory**
* Sub-service: **develop**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by CeciAc** [comment]
こんにちは、@ishida0219
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
