### ISSUE TITLE
感情検出のロジックが動かない

### ISSUE THREAD

**Issue by piyonakajima** [MicrosoftDocs/azure-docs.ja-jp#2658]
以下が実行できませんでした。Preview版となっており現行のバージョンで実施できていないのではないかと推測しています。

センチメントの検出を追加する
4.次に、テキスト ボックスに「Tweet Text」と入力し、[新しいステップ] をクリックします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ae1a4055-33b7-eead-6eb4-0092b7112567
* Version Independent ID: 7b866c4b-46d2-d420-278e-f49ec05e5d0d
* Content: [Azure Logic Apps と統合される関数を作成する](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-twitter-email#add-sentiment-detection)
* Content Source: [articles/azure-functions/functions-twitter-email.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-twitter-email.md)
* Service: **azure-functions**
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by CeciAc** [comment]
こんにちは、@piyonakajima
 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 
 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 
 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
