### ISSUE TITLE
Question regarding how to interpret "can add bob@contoso.com as Service Administrator" 

### ISSUE THREAD

**Issue by v-pethur** [MicrosoftDocs/azure-docs.ja-jp#2686]
Hello, in Limitations for changing the Service Administrator section, it states: 
"can add bob@contoso.com as Service Administrator"  I understand that traditionally, there can only be 1 Service Administrator per account.   I would just like to confirm this means, "The one and only Service Administrator can add user bob@contoso.com" to the tenant.  And not "bob@contoso.com" can be added to the tenant as a Service Administrator.
 Confirmation is greatly appreciated.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 25dd53de-a48b-5cc3-4af3-2bc27d26efe4
* Version Independent ID: 41c7fe08-42bb-8b32-c7d7-845d6bb39209
* Content: [Azure の従来のサブスクリプション管理者](https://docs.microsoft.com/ja-jp/azure/role-based-access-control/classic-administrators#feedback)
* Content Source: [articles/role-based-access-control/classic-administrators.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/role-based-access-control/classic-administrators.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by srvbpigh** [comment]
Hello, @v-pethur
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @v-pethur

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
