### ISSUE TITLE
誤字を修正してください。

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2691]
以下の文章末尾が「できです」となっておりますが、明らかにtypoですので「できます」と修正いただきますようにお願いいたします。

https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-powershell#enable-accelerated-networking-on-existing-vms
高速ネットワークを有効にしないで VM を作成した場合は、既存の VM に対してこの機能を有効にすることができです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e4be8e45-460a-fab4-519b-32d83382005c
* Version Independent ID: 36a002a6-5813-da00-0a57-068eeaf491cf
* Content: [高速ネットワークを使った Azure 仮想マシンの作成](https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-powershell#enable-accelerated-networking-on-existing-vms)
* Content Source: [articles/virtual-network/create-vm-accelerated-networking-powershell.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-network/create-vm-accelerated-networking-powershell.md)
* Service: **virtual-network**
* GitHub Login: @gsilva5
* Microsoft Alias: **gsilva**

**Comment by srvbpigh** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-powershell#enable-accelerated-networking-on-existing-vms

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
