### ISSUE TITLE
リンク修正希望

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2708]
冒頭の[ Azure アプリケーションのディザスター リカバリーと高可用性]のテキストに記載されているURLがデッドリンクになっています。
修正お願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a6874376-9df5-65b7-6908-eaaba67992d0
* Version Independent ID: c76d243b-a9a0-d37d-6cc5-53eb1bf589d2
* Content: [Azure IoT Hub の高可用性とディザスター リカバリー](https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-ha-dr#cross-region-dr)
* Content Source: [articles/iot-hub/iot-hub-ha-dr.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-hub/iot-hub-ha-dr.md)
* Service: **iot-hub**
* GitHub Login: @rkmanda
* Microsoft Alias: **philmea**

**Comment by srvbpigh** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #36321](https://github.com/MicrosoftDocs/azure-docs/issues/36321) via [**ZenHub**](https://www.zenhub.com/)
