### ISSUE TITLE
Sample Script Error (Japanese Docs)

### ISSUE THREAD

**Issue by gutzeit1106** [MicrosoftDocs/azure-docs.ja-jp#271]
次の箇所のサンプルスクリプトが英語版と異なっており、正常に動作しないと思われます。
The following sample PowerShell scripts are different from English ver. And The scripts doesn't work correctly.

複数の NIC を持つ Windows VM の作成　 > 既存の VM からの NIC の削除
https://github.com/Microsoft/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/multiple-nics.md

Create a Windows virtual machine that has multiple NICs > Remove a NIC from an existing VM
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/multiple-nics#remove-a-nic-from-an-existing-vm

**Comment by SunnyDeng** [comment]
@gutzeit1106 -san, the JPN version is up to date as EN currently, could you please check again?
