### ISSUE TITLE
機械翻訳による誤訳か

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2710]
誤訳
機械翻訳の影響で低頻度のアラートと記載されておりますが、原文では having alerts with frequency as low as 1 minute. とニュアンスが違っております。
翻訳文の修正をお願いいたします。

Log Analytics のメトリック アラートの作成
https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/alerts-metric-logs#creating-metric-alert-for-log-analytics

(1 分という低頻度のアラートの使用など) 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fb45c876-8b2a-5e69-3745-5ee47f2bb27d
* Version Independent ID: 4ace419b-24da-a3ef-0839-78a2d815cfb8
* Content: [Azure Monitor でのログのメトリック アラートの作成](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/alerts-metric-logs#creating-metric-alert-for-log-analytics)
* Content Source: [articles/azure-monitor/platform/alerts-metric-logs.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/alerts-metric-logs.md)
* Service: **azure-monitor**
* Sub-service: **alerts**
* GitHub Login: @msvijayn
* Microsoft Alias: **vinagara**

**Comment by srvbpigh** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/alerts-metric-logs#creating-metric-alert-for-log-analytics

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
