### ISSUE TITLE
Typo at first section in this article

### ISSUE THREAD

**Issue by hidwatanabe** [MicrosoftDocs/azure-docs.ja-jp#2711]
There is a type in the first section, "THDInsight". It should be "HDInsight". This seems to be only in ja-jp document.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 020ae447-3bf7-73f8-926a-29e05a1ae671
* Version Independent ID: 6c7c4685-d7d7-569c-b43b-4c4dc71dd453
* Content: [Azure HDInsight の Hadoop で Data Lake Storage Gen1 を使用する](https://docs.microsoft.com/ja-jp/azure/hdinsight/hdinsight-hadoop-use-data-lake-store?toc=https%3A%2F%2Fdocs.microsoft.com%2Fja-jp%2Fazure%2Fhdinsight%2Fhadoop%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fja-jp%2Fazure%2Fbread%2Ftoc.json)
* Content Source: [articles/hdinsight/hdinsight-hadoop-use-data-lake-store.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/hdinsight/hdinsight-hadoop-use-data-lake-store.md)
* Service: **hdinsight**
* GitHub Login: @hrasheed-msft
* Microsoft Alias: **hrasheed**

**Comment by srvbpigh** [comment]
Hello, @hidwatanabe
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @hidwatanabe
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/hdinsight/hdinsight-hadoop-use-data-lake-store?toc=https%3A%2F%2Fdocs.microsoft.com%2Fja-jp%2Fazure%2Fhdinsight%2Fhadoop%2FTOC.json&bc=https%3A%2F%2Fdocs.microsoft.com%2Fja-jp%2Fazure%2Fbread%2Ftoc.json

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
