### ISSUE TITLE
Clarification needed on valid subscriptions for self-password resest

### ISSUE THREAD

**Issue by UKayo** [MicrosoftDocs/azure-docs.ja-jp#2718]
Please clarify what subscriptions are needed to use the 2 features.
Does "Microsoft 365 Business" mean the specific M365 Business plan only? How about Office 365 E3 or E5 plans? Are education plans excluded?

Self-Service Password Reset for cloud users
-&gt; This functionality is included in Azure AD Basic, Premium P1 or P2, or Microsoft 365 Business.

Self-Service Password Reset/Change/Unlock with on-premises writeback
-&gt; This functionality is included in Azure AD Premium P1 or P2, or Microsoft 365 Business.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 650b028a-16b9-f560-a2aa-8613d85ffce6
* Version Independent ID: 0e2c2f6b-65bd-4dc8-1a45-956d20bf8a9b
* Content: [セルフサービスによるパスワード リセットのライセンス - Azure Active Directory](https://docs.microsoft.com/ja-jp/azure/active-directory/authentication/concept-sspr-licensing#feedback)
* Content Source: [articles/active-directory/authentication/concept-sspr-licensing.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/authentication/concept-sspr-licensing.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @UKayo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #36821](https://github.com/MicrosoftDocs/azure-docs/issues/36821) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @UKayo

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/36821

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
