### ISSUE TITLE
undescribed preview

### ISSUE THREAD

**Issue by juyama** [MicrosoftDocs/azure-docs.ja-jp#2719]
Currently, "Azure Kubernetes Service (AKS) Ingress controller" is preview. However, it is undescribed in JP version page. I recommend to note about that such as "Azure Kubernetes Service (AKS) のイングレス コントローラーの概要 (プレビュー)".

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 68677bfe-232b-3f9f-5473-005098e7231d
* Version Independent ID: ab0e9bbf-b9cd-acdc-054d-ca64bf6700bb
* Content: [Azure Application Gateway とは](https://docs.microsoft.com/ja-jp/azure/application-gateway/overview#azure-kubernetes-service-aks-ingress-controller-preview)
* Content Source: [articles/application-gateway/overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/application-gateway/overview.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by srvbpigh** [comment]
Hello, @juyama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @juyama
 
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 
 
Kind regards,
Microsoft DOCS International Team

**Comment by juyama** [comment]
Hi @CeciAc,

My concern is resolved by following commit. There is no concern. So I will close this issue. Thanks for your help.
https://github.com/MicrosoftDocs/azure-docs.ja-jp/commit/5c7201060e9114d17b9dd128224db41766a9f2cc#diff-c24cd407dbcd97bcd316efa11bf4fb1c
