### ISSUE TITLE
It seems that Question and Answer are wrong

### ISSUE THREAD

**Issue by juyama** [MicrosoftDocs/azure-docs.ja-jp#2725]
This is a localization issue. It's buttoned up incorrectly. It seems that start with "既存の仮想ネットワークに AKS をデプロイできますか?" (English ver. "Can I deploy AKS into my existing virtual network?")

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d501ff67-9208-8bcb-e8df-f09e9b16a802
* Version Independent ID: e3fc3851-ddc4-d26c-251d-6ae53d714081
* Content: [Azure Kubernetes Service (AKS) についてよく寄せられる質問](https://docs.microsoft.com/ja-jp/azure/aks/faq)
* Content Source: [articles/aks/faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/aks/faq.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @juyama
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by juyama** [comment]
This issue was fixed. Thanks for your support.
https://github.com/MicrosoftDocs/azure-docs.ja-jp/commit/389098279b0948006a0041a69d662f35647e04cf#diff-d52ae18757d88d3e4a5da829fae6e1e6
