### ISSUE TITLE
機械翻訳による誤訳。修正お願いします。

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#2729]
毎 15 分の頻度　-&gt; 15分毎の頻度

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d5f8cad2-5ec7-b08e-d8da-5f6aba053cae
* Version Independent ID: f1ac2724-12c3-3096-757f-93bc7df05d13
* Content: [チュートリアル - Azure への SQL Server データベースのバックアップ](https://docs.microsoft.com/ja-jp/azure/backup/tutorial-sql-backup#create-a-backup-policy)
* Content Source: [articles/backup/tutorial-sql-backup.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/backup/tutorial-sql-backup.md)
* Service: **backup**
* GitHub Login: @dcurwin
* Microsoft Alias: **dacurwin**

**Comment by srvbpigh** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/backup/tutorial-sql-backup#create-a-backup-policy  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
