### ISSUE TITLE
"製品" と "成果物" ?

### ISSUE THREAD

**Issue by 4416km** [MicrosoftDocs/azure-docs.ja-jp#2760]
原文だと "product" なのに日本語訳では "製品" だったり "成果物" だったりとバラバラの用語が使われており、まるで別の概念のものが存在しているようでとても混乱します。意図的に使い分けているのでしょうか？そうでなければどちらかに統一していただきたいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6c12f877-77a9-0593-a539-2b011f9f83cd
* Version Independent ID: 0d600bc9-7ec1-27f5-5d27-a5d22e2e8629
* Content: [Azure API Management で成果物を作成して発行する方法](https://docs.microsoft.com/ja-jp/azure/api-management/api-management-howto-add-products#feedback)
* Content Source: [articles/api-management/api-management-howto-add-products.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/api-management/api-management-howto-add-products.md)
* Service: **api-management**
* GitHub Login: @mikebudzynski
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @4416km
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@4416km

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/api-management/api-management-howto-add-products#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
