### ISSUE TITLE
"データが保持されている場所はどこですか。" の内容をアップデートしてください

### ISSUE THREAD

**Issue by 4416km** [MicrosoftDocs/azure-docs.ja-jp#2768]
こちらのドキュメントでは、"米国、ヨーロッパ、または東南アジアです。 新しい Application Insights リソースを作成するときに場所を選択できます。" と記載されていますが、現時点では東日本やオーストラリア東部など多くのリージョンへの展開が可能になっています。ドキュメントの更新をお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c4cb6c8f-80a5-3a49-3cc1-e194e5b98b16
* Version Independent ID: ef9c64e5-466d-9be2-df6a-39de8c76b1ad
* Content: [Azure Application Insights でのデータ保持と保存](https://docs.microsoft.com/ja-jp/azure/azure-monitor/app/data-retention-privacy#where-is-the-data-held)
* Content Source: [articles/azure-monitor/app/data-retention-privacy.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/app/data-retention-privacy.md)
* Service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @4416km
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #38025](https://github.com/MicrosoftDocs/azure-docs/issues/38025) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@4416km
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (XXX) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
