### ISSUE TITLE
誤訳;多層防御の項

### ISSUE THREAD

**Issue by znrk** [MicrosoftDocs/azure-docs.ja-jp#2772]
「and listening ports that are not needed on the load balancers (Azure Load Balancer and Azure Application Gateway). 」
 →
「ロード バランサー (Azure Load Balancer と Azure Application Gateway) に必要のないポートをリッスンすることで、」
この訳では意味不明です。

訳の提案:
「ロード バランサー (Azure Load Balancer と Azure Application Gateway) を用いて不要にリスニングしているポートを閉じることで、」と変更したほうが良いかと思います。
この項ではALB/AppGwによって必要なポートだけが開いている状態になっていれば攻撃の範囲が狭まり、より安全であることを意図していますので、現在の訳では意味が分かりません。
サーバーではWebなど以外のポートも開いており、そのままインターネットにさらしておくと意図しないポートが開いている状態になっています。(NSGで必要なポートだけを晒すことはできますが。)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 103dfba7-eef6-e6b6-3713-d64b408e8077
* Version Independent ID: 721e7f13-4169-2f24-3a80-73ec7758db77
* Content: [Azure DDoS Protection のベスト プラクティスと参照アーキテクチャ](https://docs.microsoft.com/ja-jp/azure/security/fundamentals/ddos-best-practices#feedback)
* Content Source: [articles/security/fundamentals/ddos-best-practices.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/security/fundamentals/ddos-best-practices.md)
* Service: **security**
* Sub-service: **security-fundamentals**
* GitHub Login: @barclayn
* Microsoft Alias: **barclayn**

**Comment by srvbpigh** [comment]
Hello, @znrk
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@znrk

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/security/fundamentals/ddos-best-practices#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
