### ISSUE TITLE
Azure Data Explorer

### ISSUE THREAD

**Issue by satonaoki** [MicrosoftDocs/azure-docs.ja-jp#2773]
In the documentation of "Azure Data Explorer", "Azure Data Explorer" in translated to "Azure データ エクスプローラー":

https://docs.microsoft.com/ja-jp/azure/data-explorer/

"Azure Data Explorer" is an Azure service name, and must not be translated:

https://azure.microsoft.com/ja-jp/services/data-explorer/

Could you change "Azure データ エクスプローラー" back to "Azure Data Explorer"?

**Comment by srvbpigh** [comment]
Hello, @satonaoki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @satonaoki
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/data-explorer/

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
