### ISSUE TITLE
Please use "パスワードレス" instead of "パスワードなし"

### ISSUE THREAD

**Issue by watahani** [MicrosoftDocs/azure-docs.ja-jp#2774]
Passwordless is well-known not only word wold wide but also in Japan.
I think it is better to use "パスワードレス" instead of "パスワードなし". 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: ae3dbcad-9d0d-c32d-7b02-2a3ffe291b2e
* Version Independent ID: 4f716e15-73a2-71a0-53ba-801b6097c479
* Content: [Azure Active Directory へのパスワードなしのサインイン (プレビュー)](https://docs.microsoft.com/ja-jp/azure/active-directory/authentication/concept-authentication-passwordless#enable-new-passwordless-authentication-methods)
* Content Source: [articles/active-directory/authentication/concept-authentication-passwordless.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/authentication/concept-authentication-passwordless.md)
* Service: **active-directory**
* Sub-service: **authentication**
* GitHub Login: @MicrosoftGuyJFlo
* Microsoft Alias: **joflore**

**Comment by srvbpigh** [comment]
Hello, @watahani
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @watahani
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/active-directory/authentication/concept-authentication-passwordless#enable-new-passwordless-authentication-methods

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
