### ISSUE TITLE
About West Japan gateway IP address

### ISSUE THREAD

**Issue by v-makta** [MicrosoftDocs/azure-docs.ja-jp#2776]
There are differences between the English and Japanese versions of this site.
If there is a difference, it is a big problem that users cannot connect.
Please correct the Japanese version immediately.

The update date for the English and Japanese versions is the same as 7/2.
I think that the English version is up-to-date, but when is the correct update date for the English version?
Is there any chance that the update date will not be updated even though the content has been updated?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e1a62365-4312-8aad-d2f1-bb5c4184adf1
* Version Independent ID: 2ba5b809-8025-d7ee-c756-d6d1bab033fb
* Content: [Azure SQL Database と SQL Data Warehouse の接続アーキテクチャ](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-connectivity-architecture)
* Content Source: [articles/sql-database/sql-database-connectivity-architecture.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/sql-database/sql-database-connectivity-architecture.md)
* Service: **sql-database**
* Sub-service: **development**
* GitHub Login: @rohitnayakmsft
* Microsoft Alias: **rohitna**

**Comment by srvbpigh** [comment]
Hello, @v-makta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @v-makta 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-connectivity-architecture

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
