### ISSUE TITLE
image file is not accessible

### ISSUE THREAD

**Issue by ShuheiUda** [MicrosoftDocs/azure-docs.ja-jp#28]
Hi,

Image file is not accessible in this page.
Could you please check it?

**Comment by ericvt** [comment]
Hi Shuhei, can you tell me in which file you can't see the image?

**Comment by a-yui** [comment]
These images can't accessed.
Could you please check it?

https://github.com/Microsoft/azure-docs.ja-jp/blob/master/articles/monitoring-and-diagnostics/media/monitoring-overview/MonitoringAzureResources-non-compute_v3.png

https://github.com/Microsoft/azure-docs.ja-jp/blob/master/articles/monitoring-and-diagnostics/media/monitoring-overview/MonitoringAzureResources-compute_v3.png

**Comment by a-yui** [comment]
We can't  access this image either.

https://github.com/Microsoft/azure-docs.ja-jp/blob/master/articles/monitoring-and-diagnostics/media/monitoring-overview-of-diagnostic-logs/logical-placement-chart.png

**Comment by ShuheiUda** [comment]
Hi @ericvt, sorry for my late response.

Here is broken links.
https://1drv.ms/x/s!Ao2QgoUEYMTIqPFQdTnO5nOO6yvqVg

Thanks

**Comment by ericvt** [comment]
fixed
