### ISSUE TITLE
SQLDB supports AZ in Japan East

### ISSUE THREAD

**Issue by masashioms** [MicrosoftDocs/azure-docs.ja-jp#2809]
Actually we can deploy SQLDB with AZ option in Japan East. But this document says AZ is not available for SQLDB in Japan East.
Is this because it is still in preview status?
 
 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cca70845-100f-2cfd-aba3-34b7fa4a5264
* Version Independent ID: 475b26e5-9e23-f769-3bd5-cbc4a678dbf0
* Content: [Azure Availability Zones とは](https://docs.microsoft.com/ja-jp/azure/availability-zones/az-overview#services-support-by-region)
* Content Source: [articles/availability-zones/az-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/availability-zones/az-overview.md)
* Service: **azure**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by srvbpigh** [comment]
Hello, @masashioms
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #38867](https://github.com/MicrosoftDocs/azure-docs/issues/38867) via [**ZenHub**](https://www.zenhub.com/)
