### ISSUE TITLE
Duplicate IP addresses for Azure Public

### ISSUE THREAD

**Issue by v-hakob** [MicrosoftDocs/azure-docs.ja-jp#2832]
Customer pointed out there are the duplicate IP addresses in the list above. I confirmed the "en-US" document looks correct (no duplicates). Could you please fix them accordingly. Thank you. ＜Azure PublicのIPアドレスに重複がありますので、修正してください。よろしくお願いいたします＞

13.64.39.16/32
20.40.125.155/32
40.81.47.216/32
40.90.185.46/32
51.145.179.78/32
52.142.95.35/32

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8d854b3c-f9f9-7f6a-f889-e19acac2961c
* Version Independent ID: ed544e54-d24b-2f37-05b6-8b60eacd2026
* Content: [Azure API Management で仮想ネットワークを使用する方法](https://docs.microsoft.com/ja-jp/azure/api-management/api-management-using-with-vnet#feedback)
* Content Source: [articles/api-management/api-management-using-with-vnet.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/api-management/api-management-using-with-vnet.md)
* Service: **api-management**
* GitHub Login: @vlvinogr
* Microsoft Alias: **apimpm**

**Comment by srvbpigh** [comment]
Hello, @v-hakob
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @v-hakob
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/api-management/api-management-using-with-vnet#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
