### ISSUE TITLE
IoTCentralの日本語版のデバイス テンプレートWeb画面の間違いを訂正してください

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/azure-docs.ja-jp#2837]
デバイス テンプレートを作成する
設定
[設定] ページで、次の数値の設定を追加します。とありますが、実際のWeb画面では「数値」ではなく「回数」と表示されているので、非常にわかり難くなっています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 40e6d9e7-7b52-8cc0-0c38-f8d9596da0db
* Version Independent ID: 2586b5df-1f87-f90d-7533-a00e26dc93fa
* Content: [汎用の Node.js クライアント アプリケーションを Azure IoT Central に接続する](https://docs.microsoft.com/ja-jp/azure/iot-central/howto-connect-nodejs#feedback)
* Content Source: [articles/iot-central/howto-connect-nodejs.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-central/howto-connect-nodejs.md)
* Service: **iot-central**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by srvbpigh** [comment]
Hello, @ahidaka
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@ahidaka

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/iot-central/howto-connect-nodejs#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
