### ISSUE TITLE
Quotation mark is missing.

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/azure-docs.ja-jp#2838]
Section: Create a Node.js application
5.Add the following variable declarations to the file:
The line 3:
var symmetricKey = '{your Primary Key};
should be
var symmetricKey = '{your Primary Key}';

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 40e6d9e7-7b52-8cc0-0c38-f8d9596da0db
* Version Independent ID: 2586b5df-1f87-f90d-7533-a00e26dc93fa
* Content: [汎用の Node.js クライアント アプリケーションを Azure IoT Central に接続する](https://docs.microsoft.com/ja-jp/azure/iot-central/howto-connect-nodejs)
* Content Source: [articles/iot-central/howto-connect-nodejs.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-central/howto-connect-nodejs.md)
* Service: **iot-central**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by srvbpigh** [comment]
Hello, @ahidaka
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by lichasu** [comment]
Hello, @ahidaka 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback in the English repository and will be fixed automatically in Japanese.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
