### ISSUE TITLE
 Do not translate "location"

### ISSUE THREAD

**Issue by ioridev** [MicrosoftDocs/azure-docs.ja-jp#2868]
[The word “場所ヘッダー” is strange.
 Do not translate "location"
]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aacd2683-3d38-ac23-22bb-fadd39d16dcc
* Version Independent ID: 0eef0b80-ee12-958f-cbf3-e35ab8e7e535
* Content: [App Service を使用した Azure Application Gateway のトラブルシューティング - App Service URL へのリダイレクト](https://docs.microsoft.com/ja-jp/azure/application-gateway/troubleshoot-app-service-redirection-app-service-url#alternate-solution-use-a-custom-domain-name)
* Content Source: [articles/application-gateway/troubleshoot-app-service-redirection-app-service-url.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/application-gateway/troubleshoot-app-service-redirection-app-service-url.md)
* Service: **application-gateway**
* GitHub Login: @abshamsft
* Microsoft Alias: **absha**

**Comment by srvbpigh** [comment]
Hello, @ioridev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ioridev
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/application-gateway/troubleshoot-app-service-redirection-app-service-url#alternate-solution-use-a-custom-domain-name

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
