### ISSUE TITLE
about the -TypeHandlerVersion "2.0"; 

### ISSUE THREAD

**Issue by Tanharuki** [MicrosoftDocs/azure-docs.ja-jp#2892]
When I run this command on Powershell,it showed me error like this :
Set-AzVMExtension : A parameter cannot be found that matches parameter name 'TypeHandlerVesion'.

Set-AzVMExtension -ResourceGroupName "testforSQL" `
  -Location "<VMLocation>" -VMName "<VMName>" `
  -Name "SqlIaasExtension" -Publisher "Microsoft.SqlServer.Management" `
  -ExtensionType "SqlIaaSAgent" -TypeHandlerVersion "2.0";

why? what should I do ?
when i delete this option..the command run is OK..
So Can i just delete this option TypeHandleVersion?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 24255026-2d1c-0607-77e6-f9dd10fbe8dd
* Version Independent ID: 832ee4c2-a497-6db6-573d-5c9abe694b00
* Content: [SQL Server IaaS Agent 拡張機能を使用して Azure 仮想マシン上で管理タスクを自動化する](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/sql/virtual-machines-windows-sql-server-agent-extension)
* Content Source: [articles/virtual-machines/windows/sql/virtual-machines-windows-sql-server-agent-extension.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-machines/windows/sql/virtual-machines-windows-sql-server-agent-extension.md)
* Service: **virtual-machines-sql**
* GitHub Login: @MashaMSFT
* Microsoft Alias: **mathoma**

**Comment by srvbpigh** [comment]
Hello, @Tanharuki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #41799](https://github.com/MicrosoftDocs/azure-docs/issues/41799) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @Tanharuki

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/41799

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
