### ISSUE TITLE
数式？？？

### ISSUE THREAD

**Issue by ShujiMIYOSHI** [MicrosoftDocs/azure-docs.ja-jp#2894]
数式はフォーミュラ

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4ed6db4d-46c7-4182-e486-d71f14725837
* Version Independent ID: bb97c234-545d-694d-e3e0-e4c1b484ea1b
* Content: [Azure DevTest Labs リソースの分散型の共同開発](https://docs.microsoft.com/ja-jp/azure/lab-services/best-practices-distributive-collaborative-development-environment)
* Content Source: [articles/lab-services/best-practices-distributive-collaborative-development-environment.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/lab-services/best-practices-distributive-collaborative-development-environment.md)
* Service: **lab-services**
* GitHub Login: @spelluru
* Microsoft Alias: **spelluru**

**Comment by srvbpigh** [comment]
Hello, @ShujiMIYOSHI
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
こんにちは、@ShujiMIYOSHI

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: XXX  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
