### ISSUE TITLE
Title is disappeared in Japanese website

### ISSUE THREAD

**Issue by maku0119** [MicrosoftDocs/azure-docs.ja-jp#2906]
日本語のサイトからタイトルが消えていますので、修正をお願いします。

日本語版
https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/reserved-vm-instance-size-flexibility

英語版
https://docs.microsoft.com/en-us/azure/virtual-machines/windows/reserved-vm-instance-size-flexibility

**Comment by srvbpigh** [comment]
Hello, @maku0119
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@maku0119
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/reserved-vm-instance-size-flexibility
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
