### ISSUE TITLE
az network public-ip create の sku 指定について

### ISSUE THREAD

**Issue by a09-capf** [MicrosoftDocs/azure-docs.ja-jp#2907]
az network public-ip create コマンドの実施において、本ドキュメントに記載の通り sku を指定せずに Public IP を発行すると、デフォルトでは Basic の Public IP が発行されるようです。
Basic sku の Public IP を --set controller.service.loadBalancerIP に指定して NGINX イングレス コントローラー をインストールすると、以下のエラーが発生し Kubernetes ロード バランサーサービスに Public IP が割り当てられません。

Error creating load balancer (will retry): failed to ensure load balancer for service ingress-basic/esteemed-hydra-nginx-ingress-controller: timed out waiting for the condition

明示的に Standard sku を指定して作成した Public IP であれば、問題なく割り当てがおこなえました。

az network public-ip create --resource-group MC_myResourceGroup_myAKSCluster_eastus --name myAKSPublicIP --allocation-method static --sku Standard --query publicIp.ipAddress -o tsv

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 12009c1f-282d-2632-fac0-64b09c432833
* Version Independent ID: 6052d3d4-d295-9340-b16d-4c200e34cd73
* Content: [Azure Kubernetes Service (AKS) の静的 IP アドレスを使用して HTTP イングレス コントローラーを作成する](https://docs.microsoft.com/ja-jp/azure/aks/ingress-static-ip#feedback)
* Content Source: [articles/aks/ingress-static-ip.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/aks/ingress-static-ip.md)
* Service: **container-service**
* GitHub Login: @mlearned
* Microsoft Alias: **mlearned**

**Comment by srvbpigh** [comment]
Hello, @a09-capf
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@a09-capf
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/43219) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
