### ISSUE TITLE
"co-owners" part should be "co-administrators" ?

### ISSUE THREAD

**Issue by thiruma0203** [MicrosoftDocs/azure-docs.ja-jp#2908]
https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/maintenance-notifications#notification-and-alerts-in-the-portal

There are several sentences that contains a word "co-owners". However, on Subscription access control (IAM), there are no such role. Would this word be fixed to "co-administrators"?

" wave starts with a notification to customers. By default, notification is sent to subscription owner and co-owners.″

"Azure communicates a schedule for planned maintenance by sending an email to the subscription owner and co-owners group."

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d4c5d6a3-e9c6-2c5e-bc40-791542eda146
* Version Independent ID: c1cb02a0-2339-2ba4-474e-b696032be30f
* Content: [Azure での Windows VM のメンテナンス通知の処理](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/maintenance-notifications#notification-and-alerts-in-the-portal)
* Content Source: [articles/virtual-machines/windows/maintenance-notifications.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-machines/windows/maintenance-notifications.md)
* Service: **virtual-machines-windows**
* GitHub Login: @shants123
* Microsoft Alias: **shants**

**Comment by srvbpigh** [comment]
Hello, @thiruma0203
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @thiruma0203

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43304

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
