### ISSUE TITLE
Wrong Japanese Translation

### ISSUE THREAD

**Issue by konabuta** [MicrosoftDocs/azure-docs.ja-jp#2912]
"見積もりツール"  should be changed to "エスティメーター"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f70a36b8-6b3b-e06c-84d6-33fd56f79ea7
* Version Independent ID: fd3dc619-fc56-5f93-860b-997c2eeb44f4
* Content: [scikit-learn 機械学習モデルをトレーニングする - Azure Machine Learning](https://docs.microsoft.com/ja-JP/azure/machine-learning/service/how-to-train-scikit-learn)
* Content Source: [articles/machine-learning/service/how-to-train-scikit-learn.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/machine-learning/service/how-to-train-scikit-learn.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @maxluk
* Microsoft Alias: **maxluk**

**Comment by srvbpigh** [comment]
Hello, @konabuta
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @konabuta,
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following page https://docs.microsoft.com/ja-JP/azure/machine-learning/service/how-to-train-scikit-learn. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.
	
Kind regards,
Microsoft DOCS International Team
