### ISSUE TITLE
 Could not locate the bindings file. Tried:

### ISSUE THREAD

**Issue by masakinoda111** [MicrosoftDocs/azure-docs.ja-jp#2913]
Raspberry Pi の Azure IoT Hub への接続 (Node.js)
サンプル アプリケーションの実行
を試したところ以下のようなエラーが出ました。

 pi@raspberrypi:~/iot-hub-node-raspberrypi-client-app $ sudo node index.js 'HostName=test1011musuke.azure-devices.net;DeviceId=raspi;SharedAccessKey=fS6c2LUT1sIb6nWZbnig8rd9L+sdJzz8muecMhKKNBs='
/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:91
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Debug/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/out/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/Release/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/build/default/nodeWiringPi.node
 → /home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/compiled/10.17.0/linux/arm/nodeWiringPi.node
    at bindings (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/node_modules/node-wiring-pi/index.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/pi/iot-hub-node-raspberrypi-client-app/index.js:10:13)

エラーの意味するところがよくわからないのですが、どのようにしたら解決できますか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a57d05c9-562c-02a5-7ccd-b1b1bb7c8f0c
* Version Independent ID: 17ee094f-aee3-ca0c-959b-6380e4ea8b89
* Content: [Raspberry Pi から クラウドへ (Node.js) - Raspberry Pi の Azure IoT Hub への接続](https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-raspberry-pi-kit-node-get-started#feedback)
* Content Source: [articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-hub/iot-hub-raspberry-pi-kit-node-get-started.md)
* Service: **iot-hub**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by srvbpigh** [comment]
Hello, @masakinoda111
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @masakinoda111 

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/43515

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
