### ISSUE TITLE
PowerShell関数をローカルで実行するためにはどの様にすればよいのでしょうか？

### ISSUE THREAD

**Issue by seike460** [MicrosoftDocs/azure-docs.ja-jp#2917]
mac にて brew install したAzure Functions Core Toolsを使って、
PowerShellの関数を作り、
「関数をローカルで実行する」セクションの
「func start」を実行しても、以下のエラーが発生してしまいます。

Exceeded language worker restart retry count for runtime:powershell. Shutting down Functions Host

こちらどの様に対応するのがよろしいでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b2646ad4-34b7-fc5e-dcc9-d53a061df394
* Version Independent ID: bbff4fda-24e4-2b62-24b9-94cda5f53bed
* Content: [Azure Functions Core Tools の操作](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-run-local#start)
* Content Source: [articles/azure-functions/functions-run-local.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-run-local.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by srvbpigh** [comment]
Hello, @seike460
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-maudel** [comment]
こんにちは、@seike460
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/43510) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
