### ISSUE TITLE
Ja-JP version of this page hasn't been updated with 1.4.320.0

### ISSUE THREAD

**Issue by ms-yuukih** [MicrosoftDocs/azure-docs.ja-jp#2918]
Ja-JP version of the doc hasn't been updated with the information about 1.4.320.0 while other languages like zh-cn, de-de and ko-kr have been updated. Please update ja-jp version as well.

https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-version-history#14320

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 57f5478b-3132-21d0-a420-a1140db235de
* Version Independent ID: 266bbd16-2117-f680-6493-e183eb09fdbc
* Content: [Azure AD Connect:バージョンのリリース履歴](https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-version-history#14320)
* Content Source: [articles/active-directory/hybrid/reference-connect-version-history.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/hybrid/reference-connect-version-history.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @ms-yuukih
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ms-yuukih
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/reference-connect-version-history#14320

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
