### ISSUE TITLE
タイトル「に」→「から」

### ISSUE THREAD

**Issue by nakamacchi** [MicrosoftDocs/azure-docs.ja-jp#2919]
Connect with the Windows Desktop client の with は、「～に」ではなく「～から」が正しい訳と思います。
（他の一連のページも同様です。）

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 524e47b0-1295-7d07-0cbc-86e6daaa1358
* Version Independent ID: 1cb3a5d8-4f16-583c-ad85-325f7638a873
* Content: [Windows Virtual Desktop に接続する Windows 10 または 7 - Azure](https://docs.microsoft.com/ja-jp/azure/virtual-desktop/connect-windows-7-and-10)
* Content Source: [articles/virtual-desktop/connect-windows-7-and-10.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-desktop/connect-windows-7-and-10.md)
* Service: **virtual-desktop**
* GitHub Login: @Heidilohr
* Microsoft Alias: **helohr**

**Comment by srvbpigh** [comment]
Hello, @nakamacchi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@nakamacchi

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-desktop/connect-windows-7-and-10

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
