### ISSUE TITLE
Port 8443 should not be an issue any longer

### ISSUE THREAD

**Issue by TeppeiIshii** [MicrosoftDocs/azure-docs.ja-jp#292]
By June 15th, you do not have to allow port 8443 - outbound connection from the VM which uses Managed Disks any more.

The original article drastically re-written, and 8443 port is not mentioned at all.

Azure Managed Disks Overview
https://docs.microsoft.com/en-us/azure/storage/storage-managed-disks-overview

Previously, the following FAQ page stated as follows:

Frequently Asked Questions about Azure IaaS VM Disks and managed and unmanaged premium disks
https://docs.microsoft.com/en-us/azure/storage/storage-faq-for-disks
------------------ 
Is there an estimated date for this issue to be fixed so I no longer have to unblock port 8443?
Yes, by the end of May 2017.
------------------ 

Now that statement is gone.

**Comment by SunnyDeng** [comment]
@robinsh could you help to clarify the solution about port 8443 in the article? Thanks！

**Comment by robinsh** [comment]
@TeppeiIshii Thanks for the question. The reason that mention of port 8443 is no longer in the docs is because they fixed the problem. You no longer have to unblock port 8443. Thanks for asking!

**Comment by SunnyDeng** [comment]
@TeppeiIshii Please reactivate if you still see problem. 
Thanks @robinsh
