### ISSUE TITLE
Feedback from cx

### ISSUE THREAD

**Issue by v-hakob** [MicrosoftDocs/azure-docs.ja-jp#2922]
Customer gave us the feedback that it would be helpful for what values he can inputted as the example for Action Group name and Alert Rule name. Because it is free text form, they did not know what they can input. They do not speak English, and cannot view video. Thank you.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4361b185-8181-891f-bf59-7365aa84427c
* Version Independent ID: 083d5ddb-5d02-34bc-246a-ac23c6a8e4f6
* Content: [Azure サービスの通知でアクティビティ ログ アラートを受け取る](https://docs.microsoft.com/ja-jp/azure/service-health/alerts-activity-log-service-notifications)
* Content Source: [articles/service-health/alerts-activity-log-service-notifications.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/service-health/alerts-activity-log-service-notifications.md)
* Service: **service-health**
* GitHub Login: @stephbaron
* Microsoft Alias: **stbaron**

**Comment by srvbpigh** [comment]
Hello, @v-hakob
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by stephbaron** [comment]
Action group and alert rule information can be found at https://docs.microsoft.com/en-us/azure/azure-monitor/platform/action-groups and https://docs.microsoft.com/en-us/azure/azure-monitor/platform/action-groups, respectively. These are "generic" alert concepts used across all Azure Alerts, not just Service Health notifications.

**Comment by CeciAc** [comment]
Hello, @v-hakob 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
