### ISSUE TITLE
Remove the webhook item from the Japanese site

### ISSUE THREAD

**Issue by damochiz** [MicrosoftDocs/azure-docs.ja-jp#2929]
The description of the Webhook has been deleted on the English site, but it remains on the Japanese site.
Please delete this page because it confuses customers?

&gt; https://docs.microsoft.com/ja-jp/azure/cognitive-services/speech-service/batch-transcription#webhooks

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 73fb7e76-fb80-c420-2efe-e3ca3a27b749
* Version Independent ID: 07a42557-deb3-e4b3-3f14-f26a27be49c2
* Content: [バッチ文字起こしの使用方法 - Speech Service - Azure Cognitive Services](https://docs.microsoft.com/ja-jp/azure/cognitive-services/speech-service/batch-transcription#webhooks)
* Content Source: [articles/cognitive-services/Speech-Service/batch-transcription.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cognitive-services/Speech-Service/batch-transcription.md)
* Service: **cognitive-services**
* Sub-service: **speech-service**
* GitHub Login: @PanosPeriorellis
* Microsoft Alias: **panosper**

**Comment by srvbpigh** [comment]
Hello, @damochiz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @damochiz 
Thank you for your feedback.
We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment?
 
Kind regards,
Microsoft DOCS International Team

**Comment by damochiz** [comment]
Hi, @CeciAc 
Thank you for contacting me. When I checked it today, the Webhook description was already removed. Since I can confirm the deletion history of the webhook from the following site, I think that it was approved yesterday.

https://github.com/MicrosoftDocs/azure-docs.ja-jp/commits/master/articles/cognitive-services/Speech-Service/batch-transcription.md
-----
![image](https://user-images.githubusercontent.com/52324401/70485996-be682600-1b33-11ea-85bd-b705183f6ae0.png)
-----

https://github.com/MicrosoftDocs/azure-docs.ja-jp/commit/9a10088238a757e0b16412a24833b881b28d1f2c#diff-a8e8739676e88b93b0592cc9701dc9bd
-----
![image](https://user-images.githubusercontent.com/52324401/70486055-dcce2180-1b33-11ea-8664-f446ced0642d.png)
-----

**Comment by CeciAc** [comment]
Hello, @damochiz 

Your feedback is much appreciated. We are glad to see that your experience with our documentation meets your expectations.
We encourage you to provide your valuable feedback so that we can continue improve your experience.

Kind regards,
Microsoft DOCS International Team
