### ISSUE TITLE
見出しの重複：「自動的なエージェントのインストールとワークスペースの作成を停止するにはどうすればよいですか?」

### ISSUE THREAD

**Issue by v-pethur** [MicrosoftDocs/azure-docs.ja-jp#2965]
見出し：
「自動的なエージェントのインストールとワークスペースの作成を停止するにはどうすればよいですか?」https://docs.microsoft.com/ja-jp/azure/security-center/security-center-faq#should-i-opt-out-of-the-automatic-agent-installation-and-workspace-creation

は一つ上の見出しと重複しています。
英語版ではそれぞれ、「How do I stop the automatic agent installation and workspace creation?」と「Should I opt out of the automatic agent installation and workspace creation?」の違った見出しとなっています。

或いは、二つの英語見出しの異なる箇所、「How do I stop」と「Should I opt out of 」が日本語では同じ「停止する」に訳され、一字一句、まったく同じ題名になっています。

「停止する」は現在進行中の状態を止めるですが、Opt-Outは「適用を除外」、「最初からはじめない」という違いがあるので、資料内リンクや関連資料

（例）　＊停止の影響　　＊停止する場合に推奨される手順

で、「停止」ではなく「Opt-Out」のニュアンスにより近い言葉と入れ替えることをご検討願います。

「停止」だと　お客様は「とりあえず自動プロビジョニングを有効にしてみて、課金されたくないVMにMMAがインストールされたら、停止すればいい」と停止が安易であるという印象を与えてしまう懸念がございます。　一度MMAがインストールされたVMの課金の停止はもう少し手の込んだ作業が必要となると私は認識しています。

「Opt-out」に近い言葉でありましたら、お客様の方も　推奨されている自動プロビジョニングを有効にする前、慎重に除外したいVMを考え直し、いらないSecurity Centerの課金が発生するアクシデントの回避に役立つかもしれません。

ご検討の程、よろしくお願いいたします。

英語版では

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 75c7f3f6-1c1e-0654-f2e7-79dbfbcc433b
* Version Independent ID: da1ac295-09fd-f240-3f61-a09f3cb94dac
* Content: [Azure Security Center のよく寄せられる質問 (FAQ)](https://docs.microsoft.com/ja-jp/azure/security-center/security-center-faq#should-i-opt-out-of-the-automatic-agent-installation-and-workspace-creation)
* Content Source: [articles/security-center/security-center-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/security-center/security-center-faq.md)
* Service: **security-center**
* GitHub Login: @memildin
* Microsoft Alias: **memildin**

**Comment by srvbpigh** [comment]
Hello, @v-pethur
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by memildin** [comment]
Clearly, the translated text of "How do I stop" and "Should I opt out of" should not both be translated to the same word (“停止する” in the Japanese).
We appreciate you bringing this to our attention. 
I'm going to ask the translation team to use “除外する” for “opt out” in this context.
Thanks again and feel free to contact us with any further questions or issues.
#please-close

**Comment by CeciAc** [comment]
@memildin we are working on this issue with the localization team
The issue needs to remain open until the fix is live :) 

kind regards

**Comment by SunnyDeng** [comment]
@memildin we are loc team, we are working on this as JAPANESE translation improvement. Leave this open until we fix it. 
Thanks for monitoring!

**Comment by CeciAc** [comment]
こんにちは、@v-pethur

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/security-center/security-center-faq#should-i-opt-out-of-the-automatic-agent-installation-and-workspace-creation

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
