### ISSUE TITLE
consistencyの訳に揺れがある

### ISSUE THREAD

**Issue by haru01** [MicrosoftDocs/azure-docs.ja-jp#2973]
consistent prefix , 整合性のあるプレフィックス ,一貫性のあるプレフィックス 
consistency level, 整合性レベル,一貫性レベル
strong consistency, 厳密な整合性, 強力な一貫性, 強固 , Strong, (strongでも揺れがある)
etc..

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b3fb7da-5483-160d-1781-d4abff9d798d
* Version Independent ID: d5e51b7e-7f34-c7df-ce4f-ee4bf5c8059a
* Content: [Azure Cosmos DB の整合性レベル](https://docs.microsoft.com/ja-jp/azure/cosmos-db/consistency-levels#feedback)
* Content Source: [articles/cosmos-db/consistency-levels.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cosmos-db/consistency-levels.md)
* Service: **cosmos-db**
* GitHub Login: @markjbrown
* Microsoft Alias: **mjbrown**

**Comment by srvbpigh** [comment]
Hello, @haru01
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@haru01   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/cosmos-db/consistency-levels#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
