### ISSUE TITLE
記載のないメトリックが多数存在する

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#2975]
以下のメトリックについて記載がありません。

Microsoft.ApiManagement/service | BackendDuration
Microsoft.Web/sites/slots | FileSystemUsage
Microsoft.Web/sites/slots | HealthCheckStatus
Microsoft.Web/sites/slots | HttpResponseTime
Microsoft.Web/serverfarms | TcpCloseWait
Microsoft.Web/serverfarms | TcpClosing
Microsoft.Web/serverfarms | TcpEstablished
Microsoft.Web/serverfarms | TcpFinWait1
Microsoft.Web/serverfarms | TcpFinWait2
Microsoft.Web/serverfarms | TcpLastAck
Microsoft.Web/serverfarms | TcpSynReceived
Microsoft.Web/serverfarms | TcpSynSent
Microsoft.Web/serverfarms | TcpTimeWait
Microsoft.Web/serverfarms | TcpCloseWait
Microsoft.Web/serverfarms | TcpClosing
Microsoft.Web/serverfarms | TcpEstablished
Microsoft.Web/serverfarms | TcpFinWait1
Microsoft.Web/serverfarms | TcpFinWait2
Microsoft.Web/serverfarms | TcpLastAck
Microsoft.Web/serverfarms | TcpSynReceived
Microsoft.Web/serverfarms | TcpSynSent
Microsoft.Web/serverfarms | TcpTimeWait
Microsoft.Network/applicationGateways | ApplicationGatewayTotalTime
Microsoft.Network/applicationGateways | AvgRequestCountPerHealthyHost
Microsoft.Network/applicationGateways | BackendConnectTime
Microsoft.Network/applicationGateways | BackendFirstByteResponseTime
Microsoft.Network/applicationGateways | BackendLastByteResponseTime
Microsoft.Network/applicationGateways | BackendResponseStatus
Microsoft.Network/applicationGateways | BytesReceived
Microsoft.Network/applicationGateways | BytesSent
Microsoft.Network/applicationGateways | ClientRtt
Microsoft.Network/applicationGateways | ComputeUnits
Microsoft.Network/applicationGateways | TlsProtocol
Microsoft.DocumentDb/databaseAccounts | DeleteVirtualNetwork
Microsoft.DocumentDb/databaseAccounts | MongoRequestsCount
Microsoft.DocumentDb/databaseAccounts | MongoRequestsDelete
Microsoft.DocumentDb/databaseAccounts | MongoRequestsInsert
Microsoft.DocumentDb/databaseAccounts | MongoRequestsQuery
Microsoft.DocumentDb/databaseAccounts | MongoRequestsUpdate
Microsoft.DataFactory/factories | ActivityCancelledRuns
Microsoft.DataFactory/factories | IntegrationRuntimeAverageTaskPickupDelay
Microsoft.DataFactory/factories | IntegrationRuntimeQueueLength
Microsoft.DataFactory/factories | PipelineCancelledRuns
Microsoft.DataFactory/factories | TriggerCancelledRuns
Microsoft.EventGrid/topics | DeadLetteredCount
Microsoft.EventGrid/topics | DeliveryAttemptFailCount
Microsoft.EventGrid/topics | DeliverySuccessCount
Microsoft.EventGrid/topics | DestinationProcessingDurationInMs
Microsoft.EventGrid/topics | DroppedEventCount
Microsoft.EventGrid/topics | MatchedEventCount
Microsoft.Network/expressRouteCircuits | ArpAvailability
Microsoft.Network/expressRouteCircuits | BgpAvailability
Microsoft.Network/expressRouteCircuits | QosDropBitsInPerSecond
Microsoft.Network/expressRouteCircuits | QosDropBitsOutPerSecond
microsoft.storagesync/storageSyncServices | StorageSyncRecalledNetworkBytesByApplication
microsoft.storagesync/storageSyncServices | StorageSyncRecalledTotalNetworkBytes
microsoft.storagesync/storageSyncServices | StorageSyncRecallThroughputBytesPerSecond
Microsoft.Network/azureFirewalls | FirewallHealth
Microsoft.Network/frontdoors | BillableResponseSize
Microsoft.Web/sites | FileSystemUsage
Microsoft.Web/sites | HealthCheckStatus
Microsoft.Web/sites | HttpResponseTime
Microsoft.Devices/IotHubs | C2DMessagesExpired
Microsoft.Devices/IotHubs | deviceDataUsageV2
Microsoft.Devices/IotHubs | EventGridLatency
Microsoft.KeyVault/vaults | Availability
Microsoft.KeyVault/vaults | SaturationShoebox
Microsoft.Logic/workflows | RunStartThrottledEvents
Microsoft.MachineLearningServices/workspaces | Active Cores
Microsoft.MachineLearningServices/workspaces | Active Nodes
Microsoft.MachineLearningServices/workspaces | CpuUtilization
Microsoft.MachineLearningServices/workspaces | GpuUtilization
Microsoft.MachineLearningServices/workspaces | Idle Cores
Microsoft.MachineLearningServices/workspaces | Idle Nodes
Microsoft.MachineLearningServices/workspaces | Leaving Cores
Microsoft.MachineLearningServices/workspaces | Leaving Nodes
Microsoft.MachineLearningServices/workspaces | Model Deploy Failed
Microsoft.MachineLearningServices/workspaces | Model Deploy Started
Microsoft.MachineLearningServices/workspaces | Model Deploy Succeeded
Microsoft.MachineLearningServices/workspaces | Model Register Failed
Microsoft.MachineLearningServices/workspaces | Model Register Succeeded
Microsoft.MachineLearningServices/workspaces | Preempted Cores
Microsoft.MachineLearningServices/workspaces | Preempted Nodes
Microsoft.MachineLearningServices/workspaces | Quota Utilization Percentage
Microsoft.MachineLearningServices/workspaces | Total Cores
Microsoft.MachineLearningServices/workspaces | Total Nodes
Microsoft.MachineLearningServices/workspaces | Unusable Cores
Microsoft.MachineLearningServices/workspaces | Unusable Nodes
Microsoft.ServiceBus/Namespaces | ConnectionsClosed
Microsoft.ServiceBus/Namespaces | ConnectionsOpened
Microsoft.Storage/storageAccounts/blobServices | BlobCount
Microsoft.Storage/storageAccounts/fileServices | FileShareQuota
Microsoft.Storage/storageAccounts/fileServices | FileShareSnapshotCount
Microsoft.Storage/storageAccounts/fileServices | FileShareSnapshotSize
Microsoft.Web/sites | FileSystemUsage
Microsoft.Web/sites | HealthCheckStatus
Microsoft.Web/sites | HttpResponseTime

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftwebsites-excluding-functions)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@fujitani-hiromu-fixer  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/44931) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team

**Comment by fujitani-hiromu-fixer** [comment]
こちらで出したissue、英語ページは対応していただいたようですが、日本語ページは未反映のようです。
英語ページには存在していて、日本語ページには存在しないメトリックが多数存在している状態です。
英語ページ、日本語ページで表記の統一をお願いします。
