### ISSUE TITLE
日本語の表記、ピリオド「.」が「。」になっている

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#2976]
以下５つのメトリックについて、
「Average_Avg.」が正しいのに「Average_Avg。」となっています。

Average_Avg。   Disk sec/Read
Average_Avg。   Disk sec/Read
Average_Avg。   Disk sec/Transfer
Average_Avg。   Disk sec/Write
Average_Avg。   Disk sec/Write

https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftoperationalinsightsworkspaces

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccountsblobservices)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
フィードバックをお送りいただきありがとうございました。  

Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccountsblobservices   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team

**Comment by fujitani-hiromu-fixer** [comment]
Is this issue not improved?

**Comment by fujitani-hiromu-fixer** [comment]
It seems to have been closed and reopened.
Is this issue not improved?

**Comment by CeciAc** [comment]
Hi @fujitani-hiromu-fixer 
We are having technical difficulties publishing the fixes on the live page.
We'll keep this issue open until it's solved

FYI @ishasahni1
