### ISSUE TITLE
日本語への訳が完全ではない

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#2978]
日本語訳ページにてほとんどのメトリックが英語表記にも関わらず
一部のメトリックのみが日本語に翻訳されており、不完全です。

なぜ一部のみ日本語なのでしょうか。翻訳するのかしないのか、
どちらかに統一したほうが良いと思います。
ちなみに英語表記のメトリックは以下の通りです。

BitsInPerSecond (受信ビット数/秒)
BitsOutPerSecond (送信ビット数/秒)
OS ディスクのキューの深さ
OS ディスク書き込みバイト数/秒
OS ディスク書き込み操作数/秒
OS ディスク読み取りバイト数/秒
OS ディスク読み取り操作数/秒
Premium OS ディスク キャッシュ読み取りヒット
Premium OS ディスク キャッシュ読み取りミス
Premium データ ディスク キャッシュ読み取りヒット
Premium データ ディスク キャッシュ読み取りミス
イングレス
エグレス
スループット
データ ディスクのキューの深さ
データ ディスク書き込みバイト数/秒
データ ディスク書き込み操作数/秒
データ ディスク読み取りバイト数/秒
データ ディスク読み取り操作数/秒
トランザクション
メッセージ
可用性
開始した実行数
完了した実行数
更新
使用法
失敗した実行
受信ネットワーク合計
受信フローの最大作成速度
受信フロー数
送信ネットワーク合計
送信フローの最大作成速度
送信フロー数
未使用の CPU クレジット
容量
要求/率

#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#feedback)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@fujitani-hiromu-fixer   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
