### ISSUE TITLE
Azure Table storage/Azure Table Storageで英語ページ、日本語ページで表記ゆれしている

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/azure-docs.ja-jp#2981]
[フィードバックをこちらに入力してください]
https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/azure-functions/functions-bindings-storage-table.md
↑
上記では「Azure Table storage」と書いている部分を
以下では「Azure Table Storage」と書き換えています。
↓
https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-bindings-storage-table.md

https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/analysis-services/analysis-services-datasource.md
↑
また、英語原本でも上記では「Azure Table Storage」と書いています。

サービス名称は一意であるはずなので、「Azure Table storage」「Azure Table Storage」のどれが正しいのか確定していただき、それに基づいて日本語ページを翻訳していただけないでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6d35c032-eae7-ac4b-2ad3-32fd0cd2318f
* Version Independent ID: 92b0a972-eabe-8048-36b1-a1cefb3acf43
* Content: [Azure Functions における Azure Table Storage のバインド](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-bindings-storage-table#feedback)
* Content Source: [articles/azure-functions/functions-bindings-storage-table.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-bindings-storage-table.md)
* GitHub Login: @craigshoemaker
* Microsoft Alias: **cshoe**

**Comment by srvbpigh** [comment]
Hello, @changeworld
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@changeworld   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-bindings-storage-table#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
