### ISSUE TITLE
Why allow F0 to train but not deploy and translate with custom translator?

### ISSUE THREAD

**Issue by bl0odier** [MicrosoftDocs/azure-docs.ja-jp#2993]
Would you please explain the purpose of allowing user to train the model if they are not allowed to use the model? What can they get during the training process? Thank you.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e834eb0c-bc29-1d4b-7322-7c2bf9d719ba
* Version Independent ID: 2e0a4153-71d8-d7f5-1cbd-b757b1cdcfef
* Content: [システムのテスト結果とデプロイを確認する - Custom Translator - Azure Cognitive Services](https://docs.microsoft.com/ja-jp/azure/cognitive-services/translator/custom-translator/how-to-view-system-test-results#feedback)
* Content Source: [articles/cognitive-services/Translator/custom-translator/how-to-view-system-test-results.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cognitive-services/Translator/custom-translator/how-to-view-system-test-results.md)
* Service: **cognitive-services**
* Sub-service: **translator-text**
* GitHub Login: @swmachan
* Microsoft Alias: **swmachan**

**Comment by srvbpigh** [comment]
Hello, @bl0odier
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @bl0odier

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
