### ISSUE TITLE
4.[基本的な SAML 構成] セクションで、次の手順を実行します。

### ISSUE THREAD

**Issue by hisssa** [MicrosoftDocs/azure-docs.ja-jp#2995]
上記のスクリーンショットが最新でなく、コメントに不足があります。応答URL欄が追加されていますので追加を希望します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cbfa13a7-4d2d-b203-d7fa-760833a745cb
* Version Independent ID: 72ff67dc-732d-478e-1595-9d4bd6737714
* Content: [チュートリアル:Azure Active Directory と Tableau Online の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/tableauonline-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/tableauonline-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/saas-apps/tableauonline-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by srvbpigh** [comment]
Hello, @hisssa
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@hisssa  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/45358) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
