### ISSUE TITLE
表の記載がズレている

### ISSUE THREAD

**Issue by libartweb** [MicrosoftDocs/azure-docs.ja-jp#3000]
Microsoft.Sql/servers/elasticPoolsの「storage_percent」の記載がズレています。
単位「Percent」の列から右に1列ズレているので修正をお願いします。

[フィードバックをこちらに入力してください]

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftwebsites-excluding-functions)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @libartweb
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
フィードバックをお送りいただきありがとうございました。  

Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftwebsites-excluding-functions   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team

**Comment by fujitani-hiromu-fixer** [comment]
特に更新がされていないようですが、どのような更新をされましたか？
