### ISSUE TITLE
記載のないメトリックが多数存在する

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#3002]
以下のissueにつきまして、英語版のリポジトリに移行されましたが、
日本語版での対応がされずにクローズされてしまいました。
https://github.com/MicrosoftDocs/azure-docs.ja-jp/issues/2975

今回のissueで英語ページに追加いただいたメトリックが日本語ページには存在していません。
ご対応をお願いいたします。

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@fujitani-hiromu-fixer 様、

フィードバックとご提案をいただき、ありがとうございます。  

現在、ファイルはローカライズ処理中です。このアーティクルはまもなくリリースされます。

サポートいただきありがとうございます。 

敬具
 
Microsoft DOCS グローバル エクスペリエンス チーム
