### ISSUE TITLE
BlobCountの表示が崩れている

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#3004]
以下issueについて英語版のみ対応されたようです。
https://github.com/MicrosoftDocs/azure-docs.ja-jp/issues/2974
英語以外のページについては依然対応されていません。
対応をお願いします。
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@fujitani-hiromu-fixer 様、
コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。
敬具
Microsoft DOCS インターナショナル チーム

**Comment by fujitani-hiromu-fixer** [comment]
https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccountsblobservices

Microsoft.Storage/storageAccounts/blobServices
メトリック：BlobCount

上記メトリックが2つ表示されており、どちらが正しいかがわからない状態です。
表記崩れでしょうか。


以下英語ページについては、正常のようです。
https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftstoragestorageaccountsblobservices

**Comment by srvbpigh** [comment]
フィードバックをお送りいただきありがとうございました。  

Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
