### ISSUE TITLE
英語ページとそれ以外の言語のページで記載内容が違う

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#3006]
英語ページとそれ以外の言語のページ（今回は日本語ページを例にします）を比較したときに、記載されている内容がページ全体で大きく異なっています。

まず、メトリックのグループが大きく異なっています。
各グループ内の表記metricも食い違っています。今回日本語ページを一例に挙げましたが、英語ページとそれ以外の言語で異なっているようです。

どのページを信用すれば良いでしょうか？ドキュメントとして正しくないので、改善を希望します。

■英語ページのグループ一覧（全107）
Microsoft.AnalysisServices/servers
Microsoft.ApiManagement/service
Microsoft.AppConfiguration/configurationStores
Microsoft.AppPlatform/Spring
Microsoft.Automation/automationAccounts
Microsoft.Batch/batchAccounts
Microsoft.BatchAI/workspaces
Microsoft.Blockchain/blockchainMembers
Microsoft.Cache/redis
Microsoft.Cdn/cdnwebapplicationfirewallpolicies
Microsoft.ClassicCompute/virtualMachines
Microsoft.ClassicCompute/domainNames/slots/roles
Microsoft.ClassicStorage/storageAccounts
Microsoft.ClassicStorage/storageAccounts/blobServices
Microsoft.ClassicStorage/storageAccounts/tableServices
Microsoft.ClassicStorage/storageAccounts/fileServices
Microsoft.ClassicStorage/storageAccounts/queueServices
Microsoft.CognitiveServices/accounts
Microsoft.Compute/virtualMachines
Microsoft.Compute/virtualMachineScaleSets
Microsoft.Compute/virtualMachineScaleSets/virtualMachines
Microsoft.ContainerInstance/containerGroups
Microsoft.ContainerRegistry/registries
Microsoft.ContainerService/managedClusters
Microsoft.CustomProviders/resourceproviders
Microsoft.DataBoxEdge/dataBoxEdgeDevices
Microsoft.DataFactory/datafactories
Microsoft.DataFactory/factories
Microsoft.DataLakeAnalytics/accounts
Microsoft.DataLakeStore/accounts
Microsoft.DBforMariaDB/servers
Microsoft.DBforMySQL/servers
Microsoft.DBforPostgreSQL/servers
Microsoft.DBforPostgreSQL/serversv2
Microsoft.Devices/IotHubs
Microsoft.Devices/provisioningServices
Microsoft.DocumentDB/databaseAccounts
Microsoft.EnterpriseKnowledgeGraph/services
Microsoft.EventGrid/domains
Microsoft.EventGrid/topics
Microsoft.EventGrid/eventSubscriptions
Microsoft.EventGrid/extensionTopics
Microsoft.EventHub/namespaces
Microsoft.EventHub/clusters
Microsoft.HDInsight/clusters
Microsoft.Insights/AutoscaleSettings
Microsoft.Insights/Components
Microsoft.KeyVault/vaults
Microsoft.Kusto/Clusters
Microsoft.Logic/workflows
Microsoft.Logic/integrationServiceEnvironments
Microsoft.MachineLearningServices/workspaces
Microsoft.Maps/accounts
Microsoft.Media/mediaservices/streamingEndpoints
Microsoft.Media/mediaservices
Microsoft.NetApp/netAppAccounts/capacityPools/volumes
Microsoft.NetApp/netAppAccounts/capacityPools
Microsoft.Network/networkInterfaces
Microsoft.Network/loadBalancers
Microsoft.Network/dnszones
Microsoft.Network/publicIPAddresses
Microsoft.Network/virtualNetworks
Microsoft.Network/azurefirewalls
Microsoft.Network/applicationGateways
Microsoft.Network/virtualNetworkGateways
Microsoft.Network/expressRoutePorts
Microsoft.Network/expressRouteCircuits
Microsoft.Network/expressRouteCircuits/peerings
Microsoft.Network/connections
Microsoft.Network/expressRouteGateways
Microsoft.Network/trafficManagerProfiles
Microsoft.Network/networkWatchers/connectionMonitors
Microsoft.Network/frontdoors
Microsoft.NotificationHubs/Namespaces/NotificationHubs
Microsoft.OperationalInsights/workspaces
Microsoft.Peering/peeringServices
Microsoft.Peering/peerings
Microsoft.PowerBIDedicated/capacities
Microsoft.Relay/namespaces
Microsoft.Search/searchServices
Microsoft.ServiceBus/namespaces
Microsoft.ServiceFabricMesh/applications
Microsoft.SignalRService/SignalR
Microsoft.Sql/servers/databases
Microsoft.Sql/servers/elasticPools
Microsoft.Sql/servers
Microsoft.Sql/managedInstances
Microsoft.Storage/storageAccounts
Microsoft.Storage/storageAccounts/blobServices
Microsoft.Storage/storageAccounts/tableServices
Microsoft.Storage/storageAccounts/fileServices
Microsoft.Storage/storageAccounts/queueServices
Microsoft.StorageCache/caches
microsoft.storagesync/storageSyncServices
microsoft.storagesync/storageSyncServices/syncGroups
microsoft.storagesync/storageSyncServices/syncGroups/serverEndpoints
microsoft.storagesync/storageSyncServices/registeredServers
Microsoft.StreamAnalytics/streamingjobs
Microsoft.TimeSeriesInsights/environments
Microsoft.TimeSeriesInsights/environments/eventsources
Microsoft.VMwareCloudSimple/virtualMachines
Microsoft.Web/serverfarms
Microsoft.Web/sites (excluding functions)
Microsoft.Web/sites (functions)
Microsoft.Web/sites/slots
Microsoft.Web/hostingEnvironments/multiRolePools
Microsoft.Web/hostingEnvironments/workerPools

■日本語ページのグループ一覧（全83）
Microsoft.AnalysisServices/servers
Microsoft.ApiManagement/service
Microsoft.Automation/automationAccounts
Microsoft.Batch/batchAccounts
Microsoft.Cache/redis
Microsoft.ClassicCompute/virtualMachines
Microsoft.ClassicCompute/domainNames/slots/roles
Microsoft.CognitiveServices/accounts
Microsoft.Compute/virtualMachines
Microsoft.Compute/virtualMachineScaleSets
Microsoft.ContainerInstance/containerGroups
Microsoft.ContainerRegistry/registries
Microsoft.ContainerService/managedClusters
Microsoft.CustomerInsights/hubs
Microsoft.DataBoxEdge/dataBoxEdgeDevices
Microsoft.DataFactory/datafactories
Microsoft.DataFactory/factories
Microsoft.DataLakeAnalytics/accounts
Microsoft.DataLakeStore/accounts
Microsoft.DBforMariaDB/servers
Microsoft.DBforMySQL/servers
Microsoft.DBforPostgreSQL/servers
Microsoft.DBforPostgreSQL/serversv2
Microsoft.Devices/IotHubs
Microsoft.Devices/provisioningServices
Microsoft.DocumentDB/databaseAccounts
Microsoft.EventGrid/topics
Microsoft.EventGrid/eventSubscriptions
Microsoft.EventGrid/extensionTopics
Microsoft.EventHub/namespaces
Microsoft.EventHub/clusters
Microsoft.HDInsight/clusters
Microsoft.Insights/AutoscaleSettings
Microsoft.Insights/Components
Microsoft.KeyVault/vaults
Microsoft.Kusto/Clusters
Microsoft.LocationBasedServices/accounts
Microsoft.Logic/workflows
Microsoft.Logic/integrationServiceEnvironments
Microsoft.MachineLearningServices/workspaces
Microsoft.Maps/accounts
Microsoft.NetApp/netAppAccounts/capacityPools/Volumes
Microsoft.NetApp/netAppAccounts/capacityPools
Microsoft.Network/networkInterfaces
Microsoft.Network/loadBalancers
Microsoft.Network/dnszones
Microsoft.Network/publicIPAddresses
Microsoft.Network/azurefirewalls
Microsoft.Network/applicationGateways
Microsoft.Network/virtualNetworkGateways
Microsoft.Network/expressRouteCircuits
Microsoft.Network/expressRouteCircuits/peerings
Microsoft.Network/connections
Microsoft.Network/trafficManagerProfiles
Microsoft.Network/networkWatchers/connectionMonitors
Microsoft.Network/frontdoors
Microsoft.NotificationHubs/Namespaces/NotificationHubs
Microsoft.OperationalInsights/workspaces
Microsoft.PowerBIDedicated/capacities
Microsoft.Relay/namespaces
Microsoft.Search/searchServices
Microsoft.ServiceBus/namespaces
Microsoft.ServiceFabricMesh/applications
Microsoft.SignalRService/SignalR
Microsoft.Sql/servers/databases
Microsoft.Sql/servers/elasticPools
Microsoft.Sql/managedInstances
Microsoft.Storage/storageAccounts
Microsoft.Storage/storageAccounts/blobServices
Microsoft.Storage/storageAccounts/fileServices
Microsoft.Storage/storageAccounts/queueServices
Microsoft.Storage/storageAccounts/tableServices
microsoft.storagesync/storageSyncServices
Microsoft.StreamAnalytics/streamingjobs
Microsoft.TimeSeriesInsights/environments
Microsoft.TimeSeriesInsights/environments/eventsources
Microsoft.VMwareCloudSimple/virtualMachines
Microsoft.Web/serverfarms
Microsoft.Web/sites (関数を除く)
Microsoft.Web/sites (関数)
Microsoft.Web/sites/slots
Microsoft.Web/hostingEnvironments/multiRolePools
Microsoft.Web/hostingEnvironments/workerPools

例えば1つ例として挙げてみますと
Microsoft.Sql/servers/elasticPoolsの内容を見ると…
英語ページのmetricは32個記載されていますが、
日本語ページ（英語以外のページ）は22個しかありません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftdevicesiothubs)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@fujitani-hiromu-fixer 様、

フィードバックとご提案をいただき、ありがとうございます。  

現在、ファイルはローカライズ処理中です。このアーティクルはまもなくリリースされます。

サポートいただきありがとうございます。 

敬具

 Microsoft DOCS グローバル エクスペリエンス チーム
