### ISSUE TITLE
Duplicate metrics

### ISSUE THREAD

**Issue by fujitani-hiromu-fixer** [MicrosoftDocs/azure-docs.ja-jp#3007]
The following metrics are listed twice in the documentation.
The same goes for English documentation.
https://github.com/MicrosoftDocs/azure-docs/issues/45763

Average_% Free Space | Microsoft.OperationalInsights/workspaces
Average_% Processor Time | Microsoft.OperationalInsights/workspaces
Average_Avg. Disk sec/Read | Microsoft.OperationalInsights/workspaces
Average_Avg. Disk sec/Write | Microsoft.OperationalInsights/workspaces
Average_Disk Reads/sec | Microsoft.OperationalInsights/workspaces
Average_Disk Transfers/sec | Microsoft.OperationalInsights/workspaces
Average_Disk Writes/sec | Microsoft.OperationalInsights/workspaces
Average_Free Megabytes | Microsoft.OperationalInsights/workspaces
BillingUsageNativeOperation | Microsoft.Logic/workflows
BillingUsageStandardConnector | Microsoft.Logic/workflows
BillingUsageStorageConsumption | Microsoft.Logic/workflows

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a0a586c4-71fd-e60b-9c4c-1a3eb2443c74
* Version Independent ID: 2f3706cc-073b-a310-8da4-2a5a90da6473
* Content: [Azure Monitor でサポートされているメトリック (リソースの種類別)](https://docs.microsoft.com/ja-jp/azure/azure-monitor/platform/metrics-supported#microsoftwebsites-excluding-functions)
* Content Source: [articles/azure-monitor/platform/metrics-supported.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/platform/metrics-supported.md)
* Service: **azure-monitor**
* Sub-service: **metrics**
* GitHub Login: @anirudhcavale
* Microsoft Alias: **ancav**

**Comment by srvbpigh** [comment]
Hello, @fujitani-hiromu-fixer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @fujitani-hiromu-fixer 

Your contribution is much appreciated. Our team reviewed your feedback and it appears that this issue has been already logged.
Please review issue https://github.com/MicrosoftDocs/azure-docs/issues/45763
 For this reason we are closing this issue since it is duplicated.

Kind regards,
Microsoft DOCS International Team
