### ISSUE TITLE
DBCA command option

### ISSUE THREAD

**Issue by anishi1222** [MicrosoftDocs/azure-docs.ja-jp#3018]
Hi,

Following this document, I tried to use DBCA (Database Configuration Assistant) silent mode to create Oracle Database instance. But the following error occurred.

[INS-04008] Invalid combination of arguments passed from command line. One or more mandatory dependent arguments are not passed for the argument: -storageType

When diagnosing this issue, I found the following option should be added to the dbca command in the document.

-datafileDestination {/path/to/datafile}

In this case, the following options would be good.

-datafileDestination /u01/app/oracle/oradata/cdb1

Could you please validate the option and modify dbca command option in this document?
Thanks in advance.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 279359a4-139a-ee4b-027b-4f43c538b90f
* Version Independent ID: 950014e2-2457-6045-eefd-865bd1c1fb76
* Content: [Azure VM での Oracle データベースの作成](https://docs.microsoft.com/ja-jp/azure/virtual-machines/workloads/oracle/oracle-database-quick-create)
* Content Source: [articles/virtual-machines/workloads/oracle/oracle-database-quick-create.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-machines/workloads/oracle/oracle-database-quick-create.md)
* Service: **virtual-machines-linux**
* GitHub Login: @romitgirdhar
* Microsoft Alias: **rogirdh**

**Comment by srvbpigh** [comment]
Hello, @anishi1222
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @anishi1222, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/46471. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
