### ISSUE TITLE
There's a mistake sample command at The serial console..

### ISSUE THREAD

**Issue by tawatan** [MicrosoftDocs/azure-docs.ja-jp#3020]
Please check below.

No 7
mount /dev/sda2 /temp is incorrect.
mount /dev/sda1 /temp is  correct.
No 8
xfs_repair /dev/sda2 -L is incorrect.
xfs_repair /dev/sda1 -L  is correct.

No 9
XFS (sda2): Mounting V1 Filesystem is incorrect.
XFS (sda2): Ending clean mount is inccorect.

XFS (sda1): Mounting V1 Filesystem is correct..
XFS (sda1): Ending clean mount is correct.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 44a6b760-f0d5-d408-5383-90e92812a586
* Version Independent ID: 86bc6e09-73d6-92dc-c2b7-f51aacbb78a8
* Content: [ファイル システム エラーによる Linux VM の起動に関する問題のトラブルシューティング](https://docs.microsoft.com/ja-jp/azure/virtual-machines/troubleshooting/linux-recovery-cannot-start-file-system-errors#feedback)
* Content Source: [articles/virtual-machines/troubleshooting/linux-recovery-cannot-start-file-system-errors.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-machines/troubleshooting/linux-recovery-cannot-start-file-system-errors.md)
* Service: **virtual-machines-linux**
* GitHub Login: @v-miegge
* Microsoft Alias: **v-six**

**Comment by srvbpigh** [comment]
Hello, @tawatan
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@tawatan  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/46749) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
