### ISSUE TITLE
「Set-ADSyncAADCompanyFeature」のコマンドライン オプションが誤っています。

### ISSUE THREAD

**Issue by ShintakuNobuhiro** [MicrosoftDocs/azure-docs.ja-jp#3028]
https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/how-to-connect-password-hash-synchronization#public-preview-of-synchronizing-temporary-passwords-and-force-password-on-next-logon

「一時パスワードと "次回ログオン時にパスワードを適用" を同期する (パブリック プレビュー)」内に記載されているコマンドラインのオプション部に誤りがあります。
The option part of the command line described in Public Preview of synchronizing temporary passwords and "Force Password Reset on Next Logon" is incorrect.
誤(Incorrect)：Set-ADSyncAADCompanyFeature  -ForcePasswordResetOnLogonFeature $true
正(Correct)：Set-ADSyncAADCompanyFeature -ForcePasswordChangeOnLogOn $true

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: c900f942-4456-5238-9f4c-a7a5bd685c04
* Version Independent ID: a5d7d971-765f-0977-f531-232ea5924121
* Content: [Azure AD Connect 同期でパスワード ハッシュ同期を実装する](https://docs.microsoft.com/ja-jp/azure/active-directory/hybrid/how-to-connect-password-hash-synchronization#public-preview-of-synchronizing-temporary-passwords-and-force-password-on-next-logon)
* Content Source: [articles/active-directory/hybrid/how-to-connect-password-hash-synchronization.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/hybrid/how-to-connect-password-hash-synchronization.md)
* Service: **active-directory**
* Sub-service: **hybrid**
* GitHub Login: @billmath
* Microsoft Alias: **billmath**

**Comment by srvbpigh** [comment]
Hello, @ShintakuNobuhiro
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46984](https://github.com/MicrosoftDocs/azure-docs/issues/46984) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@ShintakuNobuhiro  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/46984) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
