### ISSUE TITLE
Is ”Resource Health alerts” already GA ?

### ISSUE THREAD

**Issue by aykitaya** [MicrosoftDocs/azure-docs.ja-jp#3031]
I have a question about "Resource Health alerts".
This document says "Resource Health alerts currently are in preview.".
However, according to the site below,  it looks like that Azure Monitor (Alert) and Azure Service Health have been already GA.
I think it means that "Resource Health alerts" is GA too. Is this correct?

Products available by region
https://azure.microsoft.com/en-us/global-infrastructure/services/?products=monitor,service-health&regions=non-regional,japan-west,japan-east

If "Resource Health alerts" is GA, the information in this article is out of data.
I'd appreciate it if you could confirm it. Thanks.
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 73f3e9c6-8cf1-6c8d-2de7-54f6d3740fc1
* Version Independent ID: 42af845a-aed7-a035-33ee-66077d7efc57
* Content: [Azure Resource Health アラートを作成する - Resource Manager テンプレート](https://docs.microsoft.com/ja-jp/azure/service-health/resource-health-alert-arm-template-guide?source=docs#feedback)
* Content Source: [articles/service-health/resource-health-alert-arm-template-guide.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/service-health/resource-health-alert-arm-template-guide.md)

**Comment by srvbpigh** [comment]
Hello, @aykitaya
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47063](https://github.com/MicrosoftDocs/azure-docs/issues/47063) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@aykitaya  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/47063) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
