### ISSUE TITLE
リンク「Jenkins 用の Azure Marketplace イメージ」が404

### ISSUE THREAD

**Issue by AtsushiWada** [MicrosoftDocs/azure-docs.ja-jp#3032]
リンク先にアクセスすると404になりました。(/en-us/がないようです。)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6c50161e-7d27-2c8d-8be9-7e48aec40a06
* Version Independent ID: b6443dd4-1018-e9d1-8c9c-e3d32615690a
* Content: [Azure に Jenkins サーバーを作成する](https://docs.microsoft.com/ja-jp/azure/jenkins/install-jenkins-solution-template#feedback)
* Content Source: [articles/jenkins/install-jenkins-solution-template.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/jenkins/install-jenkins-solution-template.md)

**Comment by srvbpigh** [comment]
Hello, @AtsushiWada
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
@AtsushiWada 様、 

コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。 

敬具 

Microsoft DOCS インターナショナル チーム

**Comment by AtsushiWada** [comment]
ご確認ありがとうございます。念のためURLを明記します。
https://docs.microsoft.com/ja-jp/azure/jenkins/install-jenkins-solution-template
こちらのページで「ブラウザーで、Jenkins 用の Azure Marketplace イメージを開きます。」の記述における「Jenkins 用の Azure Marketplace」に対してリンクが張られていますが、そのリンクからジャンプすると404エラー（存在しないページ）となります。
リンク先のURLが誤っていると思います。
NG?：https://azuremarketplace.microsoft.com/marketplace/apps/azure-oss.jenkins?tab=Overview
OK：https://azuremarketplace.microsoft.com/ja-jp/marketplace/apps/azure-oss.jenkins?tab=Overview
よろしくお願いします。

**Comment by ticianaciminari** [comment]
Hello, @AtsushiWada,

Your contribution is much appreciated. Your feedback is related to the original documentation. 

We truly appreciate your contribution to our articles.  

Kind regards, 

Microsoft DOCS International Team 

@ishasahni1 @Gonzalo-Salines
