### ISSUE TITLE
Why the resources exist, that is 'supportsTags'=FALSE but 'costReport'=TRUE.

### ISSUE THREAD

**Issue by na2ko-ucym** [MicrosoftDocs/azure-docs.ja-jp#3039]
I was just wondering why these resources is 'supportsTags'=FALSE but 'costReport'=TRUE?

providerName				resourceType							supportsTags	costReport
Microsoft.Network			frontdoors								FALSE			TRUE
Microsoft.Network			frontdoorWebApplicationFirewallPolicies	FALSE			TRUE
Microsoft.SQL				managedInstances / databases			FALSE			TRUE
Microsoft.SQL				servers / databases						FALSE			TRUE
Microsoft.StreamAnalytics	streamingjobs							FALSE			TRUE
Microsoft.StreamAnalytics	streamingjobs							FALSE			TRUE

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 66769e1b-720b-f1b1-a5e3-ed5cb24cd233
* Version Independent ID: b6272e61-58c1-3e2f-3e36-a9ee920c0915
* Content: [リソースでのタグのサポート](https://docs.microsoft.com/ja-jp/azure/azure-resource-manager/management/tag-support#feedback)
* Content Source: [articles/azure-resource-manager/management/tag-support.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-resource-manager/management/tag-support.md)

**Comment by srvbpigh** [comment]
Hello, @na2ko-ucym
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #47234](https://github.com/MicrosoftDocs/azure-docs/issues/47234) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @na2ko-ucym, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/47234. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
