### ISSUE TITLE
UseApplicationInsights extension method is already deprecated?

### ISSUE THREAD

**Issue by NewGyu** [MicrosoftDocs/azure-docs.ja-jp#3310]
&gt; By calling the UseApplicationInsights extension method on IWebHostBuilder

It seems to that UseApplicationInsights method has been already marked as `obsolete`.
https://github.com/microsoft/ApplicationInsights-dotnet/blob/2.12.1/NETCORE/src/Microsoft.ApplicationInsights.AspNetCore/Extensions/ApplicationInsightsWebHostBuilderExtensions.cs#L17

And IWebHostBuilder will be deprecated.
https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.1&tabs=visual-studio#hostbuilder-replaces-webhostbuilder

Is `UseApplicationInsights extension method` standard?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b09a09da-72ae-d5c0-fe25-69274054d302
* Version Independent ID: 6911ee60-7c91-f024-8788-94939567d477
* Content: [ILogger を使用して .NET トレース ログを探索する - Azure Application Insights](https://docs.microsoft.com/ja-jp/azure/azure-monitor/app/ilogger#feedback)
* Content Source: [articles/azure-monitor/app/ilogger.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-monitor/app/ilogger.md)
* Service: **azure-monitor**
* Sub-service: **application-insights**
* GitHub Login: @mrbullwinkle
* Microsoft Alias: **mbullwin**

**Comment by srvbpigh** [comment]
Hello, @NewGyu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48070](https://github.com/MicrosoftDocs/azure-docs/issues/48070) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @NewGyu, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48070. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
