### ISSUE TITLE
Difference between Japanese and English

### ISSUE THREAD

**Issue by kenzoohba** [MicrosoftDocs/azure-docs.ja-jp#3522]
The timeline for "Retiring D15_v2/DS15_v2 isolation on May 15, 2020" is different with Japanese page below
https://docs.microsoft.com/ja-jp/azure/security/fundamentals/isolation-choices#timeline

https://docs.microsoft.com/en-us/azure/security/fundamentals/isolation-choices#timeline
Date	Action
November 18, 2019	Availability of D/DS15i_v2 (PAYG, 1-year RI)
May 14, 2020	Last day to buy D/DS15i_v2 1-year RI
May 15, 2020	D/DS15_v2 isolation guarantee removed
May 15, 2021	Retire D/DS15i_v2 (all customers except who bought 3-year RI of D/DS15_v2 before November 18, 2019)
November 17, 2022	Retire D/DS15i_v2 when 3-year RIs done (for customers who bought 3-year RI of D/DS15_v2 before November 18, 2019)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3c9d1ff4-9e32-39fc-2d8d-46d3c07bca4d
* Version Independent ID: 72b20547-e78b-f6d2-6e69-31c846965ad0
* Content: [Azure Public Cloud での分離](https://docs.microsoft.com/ja-jp/azure/security/fundamentals/isolation-choices#feedback)
* Content Source: [articles/security/fundamentals/isolation-choices.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/security/fundamentals/isolation-choices.md)
* Service: **security**
* Sub-service: **security-fundamentals**
* GitHub Login: @unifycloud
* Microsoft Alias: **TomSh**

**Comment by srvbpigh** [comment]
Hello, @kenzoohba
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @kenzoohba,

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @kenzoohba,

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello, @kenzoohba,

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 

Microsoft DOCS International Team
