### ISSUE TITLE
「払戻ポリシー」箇所の英語版にある「We are currently not charging this penalty.」が資料の日本語版に反映されていません。

### ISSUE THREAD

**Issue by v-pethur** [MicrosoftDocs/azure-docs.ja-jp#3526]
I do not know if this is intentional, but the 2nd sentence in the "Refund policies" section of the original English version of this document,
 
"There may be a 12% early termination fee for cancellations in future. We are currently not charging this penalty."

Does not exist in the Japanese version.  It's debate-able whether it's necessary to include, however I do feel after handling a few cases regarding this topic, adding this one line might reduce the cases we receive on this subject. 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3f0af130-6b0a-0a7e-5fd9-e67810f66b45
* Version Independent ID: 445b1c77-472a-e0f7-45fc-168f4a2454f3
* Content: [Azure の予約のセルフサービスによる交換と払戻](https://docs.microsoft.com/ja-jp/azure/cost-management-billing/reservations/exchange-and-refund-azure-reservations#feedback)
* Content Source: [articles/cost-management-billing/reservations/exchange-and-refund-azure-reservations.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cost-management-billing/reservations/exchange-and-refund-azure-reservations.md)
* Service: **cost-management-billing**
* GitHub Login: @yashesvi
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @v-pethur
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Hello @v-pethur, I did find this sentence in Japanese version. Could you please confirm we are seeing the same or if I'm looking at something different? 
![image](https://user-images.githubusercontent.com/43826292/74686529-90950280-51b0-11ea-9352-2d8a4399a6f7.png)
![image](https://user-images.githubusercontent.com/43826292/74686577-b3bfb200-51b0-11ea-83d1-14b89065520f.png)

Kind regards,
Microsoft DOCS International Team

**Comment by v-pethur** [comment]
Hello Ticiana,
Sorry for the late response, I tried a couple different browsers, but I can not see the images you posted.  This is what I am seeing.  Under the "Refund Policies" of the "Cancel, exchange, and refund policies section" 
https://docs.microsoft.com/en-us/azure/cost-management-billing/reservations/exchange-and-refund-azure-reservations#cancel-exchange-and-refund-policies

•There may be a 12% early termination fee for cancellations in future. We are currently not charging this penalty.

The Japanese version is below and does not have "We are currently not charging this penalty."

https://docs.microsoft.com/ja-jp/azure/cost-management-billing/reservations/exchange-and-refund-azure-reservations

予約をキャンセルする場合は、12% の中途解約料が発生する可能性があります。

 Thank you

**Comment by ticianaciminari** [comment]
@v-pethur we are looking at the same page: https://docs.microsoft.com/ja-jp/azure/cost-management-billing/reservations/exchange-and-refund-azure-reservations#cancel-exchange-and-refund-policies.

I found it in the last bullet point, it's not present in the first one, like in English. This file might be on vendor side for localization.

Here's the string: Microsoft は、すべての返品に対して 12% のペナルティを請求する権利を留保します。 **ペナルティは現在請求されていませんが、将来、請求されます。**

Kind regards,
Microsoft DOCS International Team

**Comment by v-pethur** [comment]
Ah, thank you
