### ISSUE TITLE
「交換と払戻」箇所の最後の行に「確定済み支払い残金」が払戻額に「適用される」（英語版ではaccrue towards）に該当する内容が見当たりません

### ISSUE THREAD

**Issue by v-pethur** [MicrosoftDocs/azure-docs.ja-jp#3527]
The last sentence of the 3rd Paragraph of the "Exchange and refunds" section reads,
"The remaining committed payments accrue towards the $50,000 USD refund limit.

The Japanese version of this sentence,
確定済み支払い残金の上限は、払戻の上限である 50,000 米国ドルとなります。
reads, "The upper limit of the remaining committed payments is 50,000 USD, (also) the upper limit of the refund limit"

and is stating to two share the same upper limit, but because it is missing the "accrue towards", it isn't explaining whatever the remaining committed payment ends up being (whether Microsoft decided to apply the 12% cancellation fee or not), it is applied to the refund amount, which has an upper limit of 50,000 USD.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6a4a8f89-f1a0-0ac2-b0c7-24d7a7091ee5
* Version Independent ID: 7c83c499-f398-b70c-80ae-6e16ddb11cff
* Content: [前払いまたは月払いで Azure の予約を購入する](https://docs.microsoft.com/ja-jp/azure/cost-management-billing/reservations/monthly-payments-reservations#feedback)
* Content Source: [articles/cost-management-billing/reservations/monthly-payments-reservations.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cost-management-billing/reservations/monthly-payments-reservations.md)
* Service: **cost-management-billing**
* GitHub Login: @bandersmsft
* Microsoft Alias: **banders**

**Comment by srvbpigh** [comment]
Hello, @v-pethur
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48283](https://github.com/MicrosoftDocs/azure-docs/issues/48283) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @v-pethur, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/48283. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
