### ISSUE TITLE
[加筆要望] ロードバランサーの種類(standard/basic,external/internal)の選び方をガイドするような内容が欲しい

### ISSUE THREAD

**Issue by shimodatkh** [MicrosoftDocs/azure-docs.ja-jp#3536]
ロードバランサーの種類を選ぶときのポイントが公式ドキュメントとして表にまとまっているとありがたいです。例えば以下記事のような。
https://www.syuheiuda.com/?p=5150

また、以下記事のような引っかかりがちなポイントも合わせてガイドされると更に助かります。
https://jpaztech1.z11.web.core.windows.net/Azure%E3%83%AD%E3%83%BC%E3%83%89%E3%83%90%E3%83%A9%E3%83%B3%E3%82%B5%E3%83%BC%E5%88%A9%E7%94%A8%E6%99%82%E3%81%AE%E6%B3%A8%E6%84%8F%E7%82%B9.html

既にどこかにドキュメントが存在していたら申し訳ありません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dd59e134-be71-0ac8-bb71-abebb2ef16f5
* Version Independent ID: a99d6a21-1c49-6bfc-9572-f7dfe8be8a4c
* Content: [Azure Load Balancer の概要 - Azure Load Balancer](https://docs.microsoft.com/ja-jp/azure/load-balancer/load-balancer-overview)
* Content Source: [articles/load-balancer/load-balancer-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/load-balancer/load-balancer-overview.md)
* Service: **load-balancer**
* GitHub Login: @asudbring
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @shimodatkh
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #48284](https://github.com/MicrosoftDocs/azure-docs/issues/48284) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@shimodatkh  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/48284) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
