### ISSUE TITLE
Default Route の訳を「既定のルート」から「デフォルトルート」に修正してください。

### ISSUE THREAD

**Issue by maku0119** [MicrosoftDocs/azure-docs.ja-jp#3676]
[フィードバックをこちらに入力してください]
Default Routeは既定のルートではなく、日本語でもデフォルトルートです。修正をお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b29b475d-056b-ba43-5309-dd1ee50b4318
* Version Independent ID: 55d5f203-32ef-40a1-62fa-83e8c81cdb14
* Content: [Azure ExpressRoute: ルーティングの要件](https://docs.microsoft.com/ja-jp/azure/expressroute/expressroute-routing#feedback)
* Content Source: [articles/expressroute/expressroute-routing.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/expressroute/expressroute-routing.md)
* Service: **expressroute**
* GitHub Login: @cherylmc
* Microsoft Alias: **cherylmc**

**Comment by srvbpigh** [comment]
Hello, @maku0119
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@maku0119   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/expressroute/expressroute-routing#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
