### ISSUE TITLE
正反対の意味になっています

### ISSUE THREAD

**Issue by azechi** [MicrosoftDocs/azure-docs.ja-jp#386]
https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/live/articles/active-directory-b2c/active-directory-b2c-reference-kmsi-custom.md#L27

>公共のコンピューターでは、ユーザーはこのオプションをチェックすることが推奨されています。 

英文では
>We recommend against users checking this option on public computers.

となっています。チェックすることを勧めない、またはチェックしないことを勧める、というような意味ではないでしょうか

**Comment by azechi** [comment]
チェックの言葉が、"チェックボックスにチェックを入れる"なのか"オプションのon,offを確認せよ"なのか、日本語では不明瞭になっているように感じます、 どうでしょうか。

**Comment by SunnyDeng** [comment]
@azechi Thank you for your contribution. We are checking against the current articles.
https://ceapex.visualstudio.com/CEINTL/_queries/edit/8441/?triage=true

**Comment by gosali** [comment]
こんにちは@azechi

あなたは新しいプルリクエストを開き、より良い翻訳を提案してください。

https://github.com/MicrosoftDocs/azure-docs.ja-jp/blame/live/articles/active-directory-b2c/active-directory-b2c-reference-kmsi-custom.md

私たちのフィードバックチームはあなたの貢献に取り組み、決議であなたにお返しします。

ご協力ありがとうございました、
マイクロソフトC＆Eローカリゼーションチーム

**Comment by CeciAc** [comment]
@azech i様、フィードバックとご提案をいただき、ありがとうございます。  
	 
お寄せいただいたフィードバックを検討させていただき、Microsoft スタイル ガイドに準拠するように調整いたします。この記事は次のローカライズ リリース ラウンドでリリースされる予定です。 
	 
Microsoft C & E ローカライズ チーム

**Comment by CeciAc** [comment]
LM Feedback: | Agree  that it is a mistranslation. However, the suggestion adds "checkbox"  that is not present in the source. 

LM suggestion: 公共のコンピューターでは、ユーザーはこのオプションにチェックを入れないよう推奨されています。
