### ISSUE TITLE
Should translate "Azure Stack Development Kit" ?

### ISSUE THREAD

**Issue by k-takai** [MicrosoftDocs/azure-docs.ja-jp#388]
"Azure Stack Development Kit" is translated "Azure Stack 開発キット" on some pages.
But it isn't translated on some other pages. (written in "Azure Stack Development Kit".)

Which is correct at Microsoft's translation policy ?
(I proposed #387 including this topic, but if "Azure Stack 開発キット" is correct, I will remove notation changes about this from #387 .)

**Comment by SunnyDeng** [comment]
@k-takai thank you for  your contribution! We are checking your feedback. 
https://ceapex.visualstudio.com/CEINTL/_workitems/edit/8442

**Comment by gosali** [comment]
Hi Takai,

According to our linguistic Department the correct translation is: "Azure Stack Development Kit"
Therefore we accepted your PR: https://github.com/MicrosoftDocs/azure-docs.ja-jp/pull/387/files 

We will take corresponding action to ensure the correct translation for this term.
Please feel free to open new Pull Requests or Issues for Linguistics inconsistencies

Thanks for your support,
Microsoft C&E Localization Team
