### ISSUE TITLE
Please fix pull-down menu

### ISSUE THREAD

**Issue by ShuheiUda** [MicrosoftDocs/azure-docs.ja-jp#391]
In many pages, pull-down menu has duplicated since some days ago.

For example:
https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-howto-site-to-site-resource-manager-portal

![image](https://user-images.githubusercontent.com/16984569/32999903-28745334-cde8-11e7-8e3a-5d939b395953.png)

**Comment by SunnyDeng** [comment]
@ShuheiUda thank you for your contribution! There are two issues here, while localization is fixing the translated strings (dup strings), i am cc-ing the writer @cherylmc to double confirm whether the 'select' behavior is changed accordingly.

**Comment by SunnyDeng** [comment]
dup strings in ja-jp version (1st and 4th) https://ceapex.visualstudio.com/CEINTL/_workitems/edit/8443

**Comment by cherylmc** [comment]
I don't see duplicate strings in my version for the dropdown. That's very odd. It should be Azure portal, PowerShell, CLI, Azure portal (classic).

**Comment by SunnyDeng** [comment]
Thank you @cherylmc for confirming the selector's behavior! 
@ShuheiUda we are investigating and track through the bug (internally) https://ceapex.visualstudio.com/CEINTL/_workitems/edit/8443

**Comment by SunnyDeng** [comment]
we resolved it. @ShuheiUda
