### ISSUE TITLE
Please fix id tag

### ISSUE THREAD

**Issue by ShuheiUda** [MicrosoftDocs/azure-docs.ja-jp#392]
Id tag is too long.
Could you please fix it?

For example:
(Today)
https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-about-vpn-devices#span-data-ttu-idf5390-117a-namedevicetablea検証済みの-vpn-デバイスとデバイス構成ガイドspanspan-classsxs-lookupspan-data-stu-idf5390-117a-namedevicetableavalidated-vpn-devices-and-device-configuration-guidesspanspan

![image](https://user-images.githubusercontent.com/16984569/33000122-84a95766-cde9-11e7-8dd3-c9a1c3e8441f.png)

(Last Week)
https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-about-vpn-devices#devicetable

**Comment by SunnyDeng** [comment]
@ShuheiUda Thank you for your contribution. 
I am seeing the page "https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-about-vpn-devices#span-data-ttu-idf5390-117a-namedevicetablea検証済みの-vpn-デバイスとデバイス構成ガイドspanspan-classsxs-lookupspan-data-stu-idf5390-117a-namedevicetableavalidated-vpn-devices-and-device-configuration-guidesspanspan" is the same as "https://docs.microsoft.com/ja-jp/azure/vpn-gateway/vpn-gateway-about-vpn-devices" as long as you click the TOC again: 
![image](https://user-images.githubusercontent.com/8811264/33305645-deef2f40-d3c3-11e7-88e4-2b234e5f034b.png)

Could you please tell how you retrieve that long URL?
Thanks
-sunny

**Comment by ShuheiUda** [comment]
@SunnyDeng  Thank you for your time.
When I click following links, I got long URL.

![image](https://user-images.githubusercontent.com/16984569/33306134-7ac84c18-d454-11e7-9cf9-085cbe6d80cd.png)

**Comment by SunnyDeng** [comment]
Thank you @ShuheiUda ! we will fix it: https://ceapex.visualstudio.com/CEINTL/_workitems/edit/8566.

**Comment by SunnyDeng** [comment]
the root cause is found and the specific article issue is fixed. 
Continuing to figure the most efficient way in order to fix all affected files. 
FYI @ShuheiUda
