### ISSUE TITLE
ja-jp version of page referencing wrong NuGet package for direct method sample

### ISSUE THREAD

**Issue by jesweare** [MicrosoftDocs/azure-docs.ja-jp#3929]
In the Japanese version of this document, the tutorial for creating a "direct method sample" (ダイレクト メソッドを呼び出し、デバイス ツインの更新を送信するジョブのスケジュール) has Step 4 that directs the installation of NuGet package Microsoft.Azure.Devices.Client:

> 4. [NuGet パッケージ マネージャー] で [参照] を選択し、Microsoft.Azure.Devices.Client を検索して選択してから、 [インストール] を選択します。

However, this package is not sufficient to follow through the rest of the steps and achieving the expected result, because the NuGet package that is *actually* required is Microsoft.Azure.Devices

The en-us counterpart has the proper direction (shown below), so fixing this version to align with the original document would be helpful.

> In the NuGet Package Manager, select Browse, search for and choose Microsoft.Azure.Devices, then select Install.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5b87df0b-e5e8-8844-5ecb-932791da3c9c
* Version Independent ID: 9682b73c-668b-4d24-5924-22175bf2eb32
* Content: [Azure IoT Hub を使用してジョブのスケジュールを設定する (.NET/.NET)](https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-csharp-csharp-schedule-jobs#feedback)
* Content Source: [articles/iot-hub/iot-hub-csharp-csharp-schedule-jobs.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-hub/iot-hub-csharp-csharp-schedule-jobs.md)
* Service: **iot-hub**
* GitHub Login: @robinsh
* Microsoft Alias: **robinsh**

**Comment by jesweare** [comment]
I've created PR #3930 for this change

**Comment by srvbpigh** [comment]
Hello, @jesweare
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@jesweare   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-csharp-csharp-schedule-jobs#feedback   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
