### ISSUE TITLE
Update Request on "active-directory-aadconnect-faq" article

### ISSUE THREAD

**Issue by o365tatsuyan** [MicrosoftDocs/azure-docs.ja-jp#395]
Describe your request: 
The following documentation should be fix or updated. Because "Soft match" is supported based on proxy address for groups and contacts.

Title : How to use SMTP matching to match on-premises user accounts to Office 365 user accounts for directory synchronization
URL : https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-faq

---- description --------------
Q: Is it supported to soft match on-premises AD Group/Contact objects with existing Azure AD Group/Contact objects?
No, this is currently not supported.
-------------------------------

PM confirmed Soft match is supported based on proxy address for groups and contacts.
And we have tested in my lab, soft match works for groups. 
So if it's possible, please fix or add these information into this article.

Addtional information:
The following docs describes "Soft match" is supported based on proxy address for groups and contacts.

https://docs.microsoft.com/en-us/azure/active-directory/connect/active-directory-aadconnect-existing-tenant
-------------------------------
Other objects than users
For mail-enabled groups and contacts, you can soft-match based on proxyAddresses. Hard-match is not applicable since you can only update the sourceAnchor/immutableID (using PowerShell) on Users only. For groups that aren't mail-enabled, there is currently no support for soft-match or hard-match.
-------------------------------

**Comment by SunnyDeng** [comment]
@o365tatsuyan Thank you for the contribution. 
Escalate to this article writer @billmath to check the English article.

**Comment by SunnyDeng** [comment]
@billmath Could you please have a look?

**Comment by billmath** [comment]
Checking with PMs.

**Comment by SunnyDeng** [comment]
@billmath, ping... do we have any reply?

**Comment by CeciAc** [comment]
@billmath Any updates on this?

**Comment by CeciAc** [comment]
Moved to en-US repo
https://github.com/MicrosoftDocs/azure-docs/issues/5415
