### ISSUE TITLE
Doesn't sync to original doc

### ISSUE THREAD

**Issue by hihorika** [MicrosoftDocs/azure-docs.ja-jp#4205]
[フィードバックをこちらに入力してください]
In original document, following sentence was removed by https://github.com/MicrosoftDocs/azure-docs/commit/90b3a364418853f2698b4a58a01981e6af311d5a#diff-98a391eef4283a3ac1f5fc42611fbebf

> This functionality is currently available using the Premium Plan and a virtual network integration.

But the change is not applied to Japanese version.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bc0b34e2-0eb8-fe89-300c-67e6c212ed31
* Version Independent ID: 5d01d8ce-f835-c88c-801c-1d569f24fd9f
* Content: [Azure Functions のネットワーク オプション](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-networking-options#restricting-your-storage-account-to-a-virtual-network)
* Content Source: [articles/azure-functions/functions-networking-options.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-networking-options.md)
* GitHub Login: @alexkarcher-msft
* Microsoft Alias: **alkarche**

**Comment by srvbpigh** [comment]
Hello, @hihorika
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by hihorika** [comment]
My suggestion is removing `この機能は現在、Premium プランと仮想ネットワーク統合を使用して利用できます。` in `お使いのストレージ アカウントを仮想ネットワークに制限する` section.

**Comment by CeciAc** [comment]
Hello, @hihorika 

Thank you for your feedback and suggestion.  

The file is currently under localization process. We will release this article soon.

Many thanks for your support. 

Kind regards,
 
Microsoft DOCS Global Experience Team
