### ISSUE TITLE
Update "Refresh Token Inactivity: 90 Days"

### ISSUE THREAD

**Issue by hiraxkats** [MicrosoftDocs/azure-docs.ja-jp#423]
Currently, Refresh Token Inactivity default value is set to be 90 Days.
Please update the document from 14 days to 90 days.

https://cloudblogs.microsoft.com/enterprisemobility/2017/08/31/changes-to-the-token-lifetime-defaults-in-azure-ad/

**Comment by SunnyDeng** [comment]
@hiraxkats thank you very much for the feedback! Could you please comment in cloundblog directly?
Currently, we are not able to track cloudblog comment for Japanese DOCS. 
Close this ISSUE
