### ISSUE TITLE
スループットに関する翻訳

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#4255]
英語：Max cached and temp storage throughput: 
日本語：キャッシュが有効な場合の一時ストレージの最大スループット

この翻訳は正しくない。temp storage とは一時ストレージで問題ないが、それと、その他のディスクにキャッシュされた操作に対するスループットを表しています。下記の提案をご検討ください。
提案：キャッシュが有効な場合及び一時ストレージの最大スループット

この文字列は、このページだけではなく、Windows やLinux VMサイズの多くのページにありますので、徹底的に修正するようお願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d11ed461-c687-fc39-0320-ccd60b403e06
* Version Independent ID: 50017c9f-a8dd-c0ab-7154-57e1665dc547
* Content: [Dv3 および Dsv3 シリーズ - Azure Virtual Machines](https://docs.microsoft.com/ja-jp/azure/virtual-machines/dv3-dsv3-series)
* Content Source: [articles/virtual-machines/dv3-dsv3-series.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-machines/dv3-dsv3-series.md)
* Service: **virtual-machines**
* GitHub Login: @jonbeck7
* Microsoft Alias: **lahugh**

**Comment by srvbpigh** [comment]
Hello, @dcbrown16
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-machines/dv3-dsv3-series

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  

Microsoft DOCS International Team
