### ISSUE TITLE
The description is desplayed in English even though I saw that in Japanese until yesterday.

### ISSUE THREAD

**Issue by makokui** [MicrosoftDocs/azure-docs.ja-jp#4269]
The summary and regional vnet integration description are now displaying in Englins even though I saw that in Japanese until yesterday.
https://docs.microsoft.com/ja-jp/azure/app-service/web-sites-integrate-with-vnet

**Comment by srvbpigh** [comment]
Hello, @makokui
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Thank you for your feedback. 

Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/app-service/web-sites-integrate-with-vnet

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
