### ISSUE TITLE
英語版では存在するページが存在しない

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/azure-docs.ja-jp#4316]
https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance-enabling-service-aided-subnet-configuration
現在対応中でしたら申し訳ございません。
上記のドキュメントが日本語だと存在しておりません。
---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 02b8d70d-ea67-98ec-cd98-236d8c2bf5b1
* Version Independent ID: 18d9663b-35d0-0e15-8ad4-00ae60f413b8
* Content: [パブリック エンドポイントの構成 - マネージド インスタンス](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-managed-instance-public-endpoint-configure)
* Content Source: [articles/sql-database/sql-database-managed-instance-public-endpoint-configure.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/sql-database/sql-database-managed-instance-public-endpoint-configure.md)
* Service: **sql-database**
* Sub-service: **security**
* GitHub Login: @srdan-bozovic-msft
* Microsoft Alias: **srbozovi**

**Comment by srvbpigh** [comment]
Hello, @LifeRyuto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@LifeRyuto
フィードバックをお送りいただきありがとうございました。  

このコンテンツはお使いの言語では利用できません。  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  

Microsoft DOCS International Team
