### ISSUE TITLE
東日本GW IP

### ISSUE THREAD

**Issue by ryoma-nagata** [MicrosoftDocs/azure-docs.ja-jp#4354]
東日本について13.78.106.224のみ疎通しません。これは最新のIP情報ですか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e1a62365-4312-8aad-d2f1-bb5c4184adf1
* Version Independent ID: 2ba5b809-8025-d7ee-c756-d6d1bab033fb
* Content: [接続のアーキテクチャ - Azure SQL Database and SQL Data Warehouse](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-connectivity-architecture#feedback)
* Content Source: [articles/sql-database/sql-database-connectivity-architecture.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/sql-database/sql-database-connectivity-architecture.md)
* Service: **sql-database**
* Sub-service: **development**
* GitHub Login: @rohitnayakmsft
* Microsoft Alias: **rohitna**

**Comment by srvbpigh** [comment]
Hello, @ryoma-nagata
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52076](https://github.com/MicrosoftDocs/azure-docs/issues/52076) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@ryoma-nagata  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/52076) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
