### ISSUE TITLE
The link of Twistlock and Aqua Security is broken link

### ISSUE THREAD

**Issue by CeciAc** [MicrosoftDocs/azure-docs.ja-jp#4370]
@rayifu commented on [Thu Sep 05 2019](https://github.com/MicrosoftDocs/azure-docs/issues/38339)

The link of Twistlock and Aqua Security is broken link. 
the page is 404 not found.

So would you please fix the link of Twistlock and Aqua Security.

twistlock: 
- column: 33
    - before: https://azuremarketplace.microsoft.com/marketplace/apps/twistlock.twistlock?tab=Overview
    - after: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/twistlock.twistlock?tab=Overview

Aqua Security: 
- column: 33, 106
    - before: https://azuremarketplace.microsoft.com/marketplace/apps/aqua-security.aqua-security?tab=Overview
    - after: https://azuremarketplace.microsoft.com/en-us/marketplace/apps/aqua-security.aqua-security?tab=Overview

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: f275d757-c0ac-498e-cf5f-b2aa1b6aade7
* Version Independent ID: 4b198221-09d2-6d0d-69ae-972745621e50
* Content: [Azure Container Instances security considerations](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-image-security#feedback)
* Content Source: [articles/container-instances/container-instances-image-security.md](https://github.com/Microsoft/azure-docs/blob/master/articles/container-instances/container-instances-image-security.md)
* Service: **container-instances**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

---

@VikasPullagura-MSFT commented on [Thu Sep 05 2019](https://github.com/MicrosoftDocs/azure-docs/issues/38339#issuecomment-528201378)

@rayifu Thanks for your feedback. When I tried opening the links, they are automatically redirecting (en-us) and the expected pages are being opened without any 404 error.

Can you please share the url to which the page is redirecting when you click on the link. 

---

@rayifu commented on [Thu Sep 05 2019](https://github.com/MicrosoftDocs/azure-docs/issues/38339#issuecomment-528226362)

thank you for replying
https://docs.microsoft.com/ja-jp/azure/container-instances/container-instances-image-security
https://docs.microsoft.com/en-us/azure/container-instances/container-instances-image-security

perhaps, I think depends on the lang of browser setting.
now, i happend 404 error when I set japanease on google chrome (v.76.0.3809.132 64 bit）.
and when I go to page of docs at after ja-jp to en-us , I happend 404 at both page of docs  and en-us.

---

@VikasPullagura-MSFT commented on [Thu Sep 05 2019](https://github.com/MicrosoftDocs/azure-docs/issues/38339#issuecomment-528268512)

@rayifu Thanks for responding with all your findings. 

I have assigned the issue who takes care of the document localization. This will be addressed soon.

---

@VikasPullagura-MSFT commented on [Thu Sep 05 2019](https://github.com/MicrosoftDocs/azure-docs/issues/38339#issuecomment-528268711)

@ishasahni1 Can you please look into this issue and add your comments.

---

@srvbpigh commented on [Sat Apr 11 2020](https://github.com/MicrosoftDocs/azure-docs/issues/38339#issuecomment-612529458)

Hello, @rayifu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
Hello, @CeciAc
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Moved to the ja-JP since the issue doesn't repro in the source
assigned back to @ishasahni1 
not a loc issue

**Comment by ishasahni1** [comment]
@rayifu when i click on this link i don't see this issue repro. It lands me to en-us page as these sites localization is not managed by our team.

I changed the browser settings on my machine and i still see en-us page. Can you kindly confirm of you still this issue? As last i see this issue was created in Sep 2019.

@CeciAc FYI

**Comment by rayifu** [comment]
@ishasahni1 
Thanks your replying for me.
yeah. I think recently (from 2 months ago) it disappear this issue.

So I'm thinking that I might as well close this issue.
