### ISSUE TITLE
"Slack" is used incorrectly instead of  "Box".

### ISSUE THREAD

**Issue by murasamelabo** [MicrosoftDocs/azure-docs.ja-jp#4375]
I found "slack" word at no 11. I guess ”Box" is correct.

>11. [マッピング] セクションの [Synchronize Azure Active Directory Users to **Slack** (Azure Active Directory ユーザーを Box に同期する)] を選択します。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e60d73e2-2709-5f22-5d31-fc2bca7ede41
* Version Independent ID: e3b73f91-7660-0621-0df0-767ea6fe7cb7
* Content: [チュートリアル: Box を構成し、Azure Active Directory を使用した自動ユーザー プロビジョニングに対応させる](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/box-userprovisioning-tutorial)
* Content Source: [articles/active-directory/saas-apps/box-userprovisioning-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/saas-apps/box-userprovisioning-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by srvbpigh** [comment]
Hello, @murasamelabo
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by v-nagta** [comment]
@murasamelabo  I have not found Slack reference in the Doc, can you please check one more time

I can see Box word in point 11 in the main Doc

![image](https://user-images.githubusercontent.com/27479164/80447599-78bbc680-8937-11ea-91bf-de4a35d1fbfa.png)

**Comment by CeciAc** [comment]
Hello, @murasamelabo 

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/box-userprovisioning-tutorial

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 

Microsoft DOCS International Team
