### ISSUE TITLE
"認証コードフロー" is incorrect.

### ISSUE THREAD

**Issue by kg0r0** [MicrosoftDocs/azure-docs.ja-jp#4386]
In the following diagram, I think the correct name is "認可コードフロー", not "認証コードフロー".
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/develop/media/scenarios/web-app.svg
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/develop/media/scenarios/desktop-app.svg
- https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/develop/media/scenarios/mobile-app.svg

I found these on the following page.
https://docs.microsoft.com/ja-jp/azure/active-directory/develop/authentication-flows-app-scenarios

**Comment by srvbpigh** [comment]
Hello, @kg0r0
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by kg0r0** [comment]
I've confirmed that it's been fixed and will close it.
