### ISSUE TITLE
[LOC]Back-Translation "転送フロー"→"TensorFlow"

### ISSUE THREAD

**Issue by hyoshioka0128** [MicrosoftDocs/azure-docs.ja-jp#4391]
ja-jp:https://docs.microsoft.com/ja-jp/azure/databricks/applications/deep-learning/single-node-training/tensorflow
![tensorflow_j](https://user-images.githubusercontent.com/40815708/79434890-f7e0fe80-8009-11ea-8c1a-564c6b9bb861.png)

en-us:https://docs.microsoft.com/en-us/azure/databricks/applications/deep-learning/single-node-training/tensorflow
![tensorflow_e](https://user-images.githubusercontent.com/40815708/79434874-f0b9f080-8009-11ea-852f-7f36333e6d04.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b0035de5-06e3-42fc-133e-93bd9c109f55
* Version Independent ID: 3fca2d8f-5bcd-9fdf-fe11-3d8a5d2ffb95
* Content: [最新のフロー-Azure Databricks](https://docs.microsoft.com/ja-jp/azure/databricks/applications/deep-learning/single-node-training/tensorflow)
* Content Source: [databricks/applications/deep-learning/single-node-training/tensorflow.md](https://github.com/MicrosoftDocs/databricks-pr.ja-JP/blob/live/databricks/applications/deep-learning/single-node-training/tensorflow.md)
* Service: **azure-databricks**
* GitHub Login: @mamccrea
* Microsoft Alias: **mamccrea**

**Comment by srvbpigh** [comment]
Hello, @hyoshioka0128
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello @hyoshioka0128 

Thank you for your contribution. 

Contributions on translation problems against machine-translated content are currently not accepted. 

We value your feedback and suggestions on human translated content, which is used to train the machine translation engines, so over time, your contributions will improve the quality of both human and machine translations. 

Human translated topics can be distinguished from machine-translated topics by the ms.translationtype metadata value “HT” (versus “MT” for machine translated) in the header of each content file. 

Many thanks for your support. 

Microsoft DOCS Global Experience Team
