### ISSUE TITLE
Configuration script does not work correctly on non-English environment

### ISSUE THREAD

**Issue by tksh164** [MicrosoftDocs/azure-docs.ja-jp#4401]
The configuration script (MicrosoftAzureMigrate-Hyper-V.ps1) does not work correctly on the non-English environment. Because the Integration Services name depends on the language of the environment.

![image](https://user-images.githubusercontent.com/1618784/79536376-e1df4680-80ba-11ea-8fea-37915c3f255c.png)

![image](https://user-images.githubusercontent.com/1618784/79536387-e6a3fa80-80ba-11ea-98d4-dfd46af6e433.png)

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0e471b58-5a81-3c02-4e3a-cbb6f19e6a49
* Version Independent ID: b57b16ff-09c9-ba7f-87f3-8780f4c8d964
* Content: [Azure Migrate を使用した評価と移行に向けて Hyper-V VM を準備する](https://docs.microsoft.com/ja-jp/azure/migrate/tutorial-prepare-hyper-v)
* Content Source: [articles/migrate/tutorial-prepare-hyper-v.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/migrate/tutorial-prepare-hyper-v.md)
* GitHub Login: @olprod

**Comment by tksh164** [comment]
This issue is will close due to I report on the English page.
https://github.com/MicrosoftDocs/azure-docs/issues/52634

**Comment by srvbpigh** [comment]
Hello, @tksh164
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
