### ISSUE TITLE
How can I get "IDPID" in Configure Azure AD SSO?

### ISSUE THREAD

**Issue by ShujiMIYOSHI** [MicrosoftDocs/azure-docs.ja-jp#4445]
Here there is a description to setupsaml configration.

Configure Azure AD SSO
(snip)
4.In the Basic SAML Configuration section, follow these steps:
a. In the Sign on URL box, enter a URL using the following pattern: https://&lt;subdomain&gt;.docusign.com/organizations/&lt;OrganizationID&gt;/saml2/login/sp/&lt;IDPID&gt;

But we can not get the infomation(IDPID) there. Because we can get the information the following steps.
Configure DocuSign SSO -&gt; "l. In the View SAML 2.0 Endpoints section of the DocuSign admin portal, follow these steps:"

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 40756c7c-63eb-10f8-c8c4-17b57877bb7f
* Version Independent ID: 9de82050-9230-0236-c246-b2fd273888ce
* Content: [チュートリアル:Azure Active Directory シングル サインオン (SSO) と DocuSign の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/docusign-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/docusign-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/active-directory/saas-apps/docusign-tutorial.md)
* Service: **active-directory**
* Sub-service: **saas-app-tutorial**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by srvbpigh** [comment]
Hello, @ShujiMIYOSHI
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #52977](https://github.com/MicrosoftDocs/azure-docs/issues/52977) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @ShujiMIYOSHI, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/52977. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
