### ISSUE TITLE
Assign the Contributor role to the resource (outside the managed resource group)

### ISSUE THREAD

**Issue by nakamacchi** [MicrosoftDocs/azure-docs.ja-jp#4483]
We have to assign the Contributor role to the resource manually, when the resource exists outside the MC_&lt;resourcegroup&gt;_&lt;clustername&gt;_&lt;location&gt; resource group.

For example, if you create the AKS cluster by using --vnet-subnet-id parameter (with existing vnet), you have to assign the Contributor role to the resource manually.

az aks create --resource-group $RG_AKS --name $AKS_CLUSTER_NAME --location $LOCATION --vnet-subnet-id $AKS_VNET_SUBNET_NPS_ID --generate-ssh-keys --enable-managed-identity

AKS_VNET_ID=$(az network vnet show --name $AKS_VNET_NAME --resource-group $RG_AKS --query id -o tsv)
AKS_MANAGED_ID=$(az aks show --name $AKS_CLUSTER_NAME --resource-group $RG_AKS --query identity.principalId -o tsv)

az role assignment create --assignee $AKS_MANAGED_ID --role "Contributor" --scope $AKS_VNET_ID

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6a9c74a8-9f1a-3d3d-3aed-f8ec45f92e05
* Version Independent ID: 01e98043-dc80-490e-a761-8d558ff4e6df
* Content: [Azure Kubernetes Service でマネージド ID を使用する](https://docs.microsoft.com/ja-jp/azure/aks/use-managed-identity)
* Content Source: [articles/aks/use-managed-identity.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/aks/use-managed-identity.md)
* GitHub Login: @saudas
* Microsoft Alias: **saudas**

**Comment by srvbpigh** [comment]
Hello, @nakamacchi
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #53073](https://github.com/MicrosoftDocs/azure-docs/issues/53073) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @nakamacchi, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/53073. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
