### ISSUE TITLE
フィードバック.００１

### ISSUE THREAD

**Issue by akdae** [MicrosoftDocs/azure-docs.ja-jp#4515]
『アプリケーションのダウンロード』まで何度も調べましたが、『アプリケーションを開く』で書かれているような、表示されている、地図は出ませんし、同４．の『対話形式の検索を実行』にも、いきつきませんでしたね。ですが、ローカルに保存してくださいとされている AzureMapDemo.html  を開くと、Webアプリケーションらしき、検索はできない検索バーと改善を促すのとその先の詳細ページ、この部分のみのページになったんですが。このページではこういうことだけでだったでしょうな。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3d455c9-d5c7-3a9e-5de5-b16072f3c77e
* Version Independent ID: d0f120b2-5ef9-9112-d17f-e8b2275ed5b4
* Content: [クイック スタート:Azure Maps を使った対話型のマップ検索](https://docs.microsoft.com/ja-jp/azure/azure-maps/quick-demo-map-app#open-the-application)
* Content Source: [articles/azure-maps/quick-demo-map-app.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-maps/quick-demo-map-app.md)
* Service: **azure-maps**
* GitHub Login: @philmea
* Microsoft Alias: **philmea**

**Comment by srvbpigh** [comment]
Hello, @akdae
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by yoichinak** [comment]
私はうまく動きました。

**Comment by akdae** [comment]
フィードバックの方をはじめたばかりなのに見ていただき、誠に恐縮でございます。
ここ最近は、Azure Maps weather serviceの作成にあたり、何が足りないのかいつもかんがみております。
Yoichi様ができたのなら、わたしにも、同じ結果が返ってくるでしょう。足りないのではなく、できるのでしょう。
さて、あれこれ難しくなるまで考察もしておりました。
できるまでの仮定として、まず、はじめのチュートリアルは何だったのでしょうかとか。
Azureの基礎のラーニング中から、発展して今に至るので、その間で、外の前提として見ておかないといけないチュートリアルが他にもあったのではないかなど。色々インストールさせられたアプリもありましたがです。
やはり、この『クックスタート:Azure Mapsを使用して対話形式の検索マップを作成する』の
『アプリケーションを開く』の2番目の『表示されたロサンゼルスの地図を…』の箇所で、地図が表示させることができない。
ここまでの、お返事よろしいですか。
私はまだできておりません。
こちらでは、まだ Github のお世話になったばかりなので、使いこなせてませんからこういった形になりました。本当に恐縮です。
Yoichi様の方も、チームの皆様の方からも、何かあれば、詳細お待ちしております。

2020年5月3日(日) 午後0:14 Yoichi Nakamura <notifications@github.com>:

**Comment by yoichinak** [comment]
@akdae 様
丁寧なお返事ありがとうございます。

この部分が気になります。

>改善を促すのとその先の詳細ページ

もしかしたら、「詳細」をクリックし、「～にアクセスする」をクリックすると表示できるようになるパターンかもしれません。

- ブラウザーは何をご利用でしょうか。Microsoft Edge (Chromium)、Google Chrome、Firefox では動きましたが、Internet Explorer 11 では動きませんでした。
- 地図が表示されないとき、ブラウザー上では何かエラーが発生しているでしょうか。ブラウザーで F12 キーを押すと開発者ツールが表示されますので、そこで何か情報が得られるかもしれません。
- `subscriptionKey` に正しいキーを指定しないと地図は表示されません。念のためご確認ください。

**Comment by akdae** [comment]
早速お返事いただき誠にありがとうございます。あわてると誤字脱字もございますが、正直に、報告していますので、サポートの方を何卒よろしくお願い致します。
頂いた内容で、一通り確認しましたら、お返事差し上げます。
さすがです、F12でというところが、かんがえどころしょうか。
このあともお時間が掛かります、多少お待たせすることになります。
うまく動けば良いなと気になってます、それでは、勝手ですがよろしくお願い致します。

2020年5月4日(月) 午前1:45 Yoichi Nakamura <notifications@github.com>:

**Comment by akdae** [comment]
開発者ツールから、エラーを発見し、調べて対処しようとしました。
　改めてご連絡差し上げます。
　よろしくお願いいたします。
　古いほうの microsoft edge です。キャッシュ と クッキー をクリアにして、再起動を行い、Azure portal に サインイン認証後、主キーは更新しておらずコードの追加変更はしておりません。そして、ローカルに保存した AzureMapDemo.html を microsoft edge で開くと、やはり、以前と変わらず、表示されません。
　F12で確認したところ、HTML1300：の青字のメッセージと、XML5619：が一つと、HTTP401：の赤字のメッセージがつづいています。
　Google chrome の方のエラーも調べたのですが、キャッシュとクッキーのクリアで解決するとありましたので対処中です。こちらの方の結果はまだ、未確認状態です。先に、microsoft edge が、確認できましたので、お返事とさせていただきます。
　お忙しい仲になるとは思いますが、ご一報おまちしております。

**Comment by CeciAc** [comment]
@akdae  様、 

ご投稿いただき、ありがとうございます。このフィードバックは製品に関連しているようです。ドキュメント ページの下部にある [製品フィードバックを送る] ボタンを使用して、提案を記録してください。 

ドキュメントに関連したフィードバックがある場合は、このチャネルを通して記録してください。 

記事への投稿に感謝しております。 

Microsoft DOCS International Team

**Comment by yoichinak** [comment]
@akdae HTTP401 の原因は `subscriptionKey` の値が間違っているせいかもしれません。AzureMapDemo.html の 40 行目で設定した値を確認してください。
たぶん HTML1300 と XML5619 は無視してかまいません。

**Comment by akdae** [comment]
ドキュメントに関係する内容を、報告してます。動作確認がとれないまま、先に進めないのであっては、ドキュメントを拝見するに当たり根拠が示されず習得できないのではと思います。
開発者ツールのエラーのひとつで、拒否をしてるみたいで、原因となるのが、要求されたリソースにはユーザー認証が必要だったとされています。
ドキュメントの確認をするためにできることをしました。残念ですが、こちらのものでは動かないのでしょう。

2020年5月5日(火) 午前8:14 Yoichi Nakamura <notifications@github.com>:

**Comment by akdae** [comment]
https://docs.microsoft.com/ja-jp/azure/azure-maps/about-azure-maps

　このドキュメントの『 使用法 』の箇所で書かれている、『 オンラインサービスの下請けの一覧にTomTomを追加するプロセスを実行中です。 』や、『 現在プレビューの段階です。 』のことによって、
　ドキュメントを参考にしたデモアプリ作成で、画面に表示されるはずの地図が表示されない、又は、開発ツールに表れている、リソースのユーザー認証を要求するエラーなどと、この上記のドキュメントで書かれていた、このコンテンツによるところが関係しているのではないですか。
　もし、このような事態で認証できないのであれば、次はいつ展開させれるまでに、期日をもっていくことができるのでしょうか。
　コンテンツに違いがあり追いついていないのであれば、あきらめておき、わかりませんが動向を見守りましょう。
　このフィードバックは一部の最新のコンテンツに追いつけているでしょうか。
