### ISSUE TITLE
「Runbookの起動」のPowershellが実行できない

### ISSUE THREAD

**Issue by piyo0320** [MicrosoftDocs/azure-docs.ja-jp#4527]
「Runbookの起動」にあるPowershellを実行しましたが、以下のエラーで失敗します。

Start-AzAutomationRunbook : オブジェクト参照がオブジェクト インスタンスに設定されていません。
発生場所 行:1 文字:8
+ $job = Start-AzAutomationRunbook @startParams
+        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : CloseError: (:) [Start-AzAutomationRunbook]、NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.Automation.Cmdlet.StartAzureAutomationRunbook

$startParams、および$startParams.Parametersをコンソール上で確認したところ、想定通りの値が入っているようでした。
環境などによって実行可否がありますか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d4ea5e93-b220-57c1-b011-865b7da3c5a6
* Version Independent ID: 179a79da-0e12-716e-725e-9db6b8f20282
* Content: [Azure Automation Runbook に Azure Resource Manager テンプレートをデプロイする](https://docs.microsoft.com/ja-jp/azure/automation/automation-deploy-template-runbook#feedback)
* Content Source: [articles/automation/automation-deploy-template-runbook.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/automation/automation-deploy-template-runbook.md)
* Sub-service: **process-automation**
* GitHub Login: @OpenLocalizationService

**Comment by srvbpigh** [comment]
Hello, @piyo0320
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by piyo0320** [comment]
Dear @srvbpigh

Thank you for your reply.
I rechecked, but all the parameters are correct.
After running a runbook test from the portal, I found that Az.Storage was not importedin my Account.
I tested the runbook from portal after importing Az.Storage and it worked.
But the execution from Powershell fails with the same error.

Kind regards,

**Comment by CeciAc** [comment]
こんにちは、@<共同作成者の GITHUB 名>  

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/azure-docs/issues/54237 を確認してください。  

 記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 

Microsoft DOCS International Team
