### ISSUE TITLE
手順6 「Connect-AzAccount」と入力しても該当コマンドが表示されない

### ISSUE THREAD

**Issue by kurihiro0119** [MicrosoftDocs/azure-docs.ja-jp#4528]
手順6にしたがって、左のライブラリ項目の検索と書かれたフォームに
「Connect-AzAccount」を入力しても、何も表示されません。
そのため、該当コマンドを設定できず、チュートリアルが途中で終わってしまいます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4799ebe4-d654-b9d2-e64f-923d025ad7cf
* Version Independent ID: f6519afb-bf55-c886-e3c3-d11174da3aea
* Content: [Azure Automation でグラフィカル Runbook を作成する](https://docs.microsoft.com/ja-jp/azure/automation/learn/automation-tutorial-runbook-graphical#feedback)
* Content Source: [articles/automation/learn/automation-tutorial-runbook-graphical.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/automation/learn/automation-tutorial-runbook-graphical.md)
* Sub-service: **process-automation**
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @kurihiro0119
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #54249](https://github.com/MicrosoftDocs/azure-docs/issues/54249) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@kurihiro0119  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/54249) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
