### ISSUE TITLE
精密/再現率グラフ

### ISSUE THREAD

**Issue by ShujiMIYOSHI** [MicrosoftDocs/azure-docs.ja-jp#4529]
精密/再現率グラフ　=&gt; 精度/再現率グラフ

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 52d75487-5a8d-f735-bc34-8a5d90c52d86
* Version Independent ID: b651cdfb-6d3b-8ce9-f665-be07b1f11273
* Content: [自動 ML 結果の概要 - Azure Machine Learning](https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-understand-automated-ml)
* Content Source: [articles/machine-learning/how-to-understand-automated-ml.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/machine-learning/how-to-understand-automated-ml.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @RachelKellam
* Microsoft Alias: **rakellam**

**Comment by srvbpigh** [comment]
Hello, @ShujiMIYOSHI
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@ShujiMIYOSHI   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-understand-automated-ml   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team
