### ISSUE TITLE
フィードバック.００１

### ISSUE THREAD

**Issue by akdae** [MicrosoftDocs/azure-docs.ja-jp#4531]
https://docs.microsoft.com/ja-jp/azure/azure-maps/about-azure-maps

　このドキュメントの『 使用法 』の箇所で書かれている、『 オンラインサービスの下請けの一覧にTomTomを追加するプロセスを実行中です。 』や、『 現在プレビューの段階です。 』のことにより、
　ドキュメントを参考にしたデモアプリ作成で、画面に表示されるはずの地図が表示されない、又は、開発ツールに表れている、リソースのユーザー認証を要求するエラーなどと、この上記のドキュメントで書かれている、このコンテンツによるところが関係しているのではないですか。
　もし、このような事態で認証できないのであれば、次はいつ展開させれるまでに、期日をもっていくことができるのでしょうか。
　コンテンツに違いがあり追いついていないのであれば、あきらめておき、わかりませんが動向を見守りましょう。
　このフィードバックは一部の最新のコンテンツに追いつけているでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3d455c9-d5c7-3a9e-5de5-b16072f3c77e
* Version Independent ID: d0f120b2-5ef9-9112-d17f-e8b2275ed5b4
* Content: [クイック スタート:Azure Maps を使った対話型のマップ検索](https://docs.microsoft.com/ja-jp/azure/azure-maps/quick-demo-map-app#feedback)
* Content Source: [articles/azure-maps/quick-demo-map-app.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-maps/quick-demo-map-app.md)
* Service: **azure-maps**
* GitHub Login: @philmea
* Microsoft Alias: **philmea**

**Comment by srvbpigh** [comment]
Hello, @akdae
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@<共同作成者の GITHUB 名>  

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/azure-docs/issues/54478
 を確認してください。  

 記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 

Microsoft DOCS International Team

**Comment by akdae** [comment]
sorry.
