### ISSUE TITLE
Linked URL should be Japanese page

### ISSUE THREAD

**Issue by yujit** [MicrosoftDocs/azure-docs.ja-jp#4533]
Linked URL of " Power BI から Azure Machine Learning Web サービスを使用する方法をご確認ください" should be 
https://docs.microsoft.com/ja-jp/power-bi/service-machine-learning-integration
instead of
https://docs.microsoft.com/en-gb/power-bi/service-machine-learning-integration

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d9415d8d-a30c-42f9-989c-c7b3a79d7108
* Version Independent ID: b7b8ae97-1801-42b1-431e-c96ca5e958f7
* Content: [Web サービスとしてデプロイされるモデル用のクライアントを作成する - Azure Machine Learning](https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-consume-web-service#feedback)
* Content Source: [articles/machine-learning/how-to-consume-web-service.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/machine-learning/how-to-consume-web-service.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @aashishb
* Microsoft Alias: **aashishb**

**Comment by srvbpigh** [comment]
Hello, @yujit
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @yujit 
Thank you for your feedback.
 
Our engineer team reviewed your suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-consume-web-service#feedback

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
