### ISSUE TITLE
The behavior of "az aks update --api-server-authorized-ip-ranges" is "replace" rather than "add" 

### ISSUE THREAD

**Issue by Darmuck** [MicrosoftDocs/azure-docs.ja-jp#4558]
https://docs.microsoft.com/ja-jp/azure/aks/egress-outboundtype#enable-developer-access-to-the-api-server
&gt; # Add to AKS approved list
&gt; az aks update -g $RG -n $AKS_NAME --api-server-authorized-ip-ranges $CURRENT_IP/32

I think it is exactly as follows
&gt; # Replace to AKS approved list
&gt; az aks update -g $RG -n $AKS_NAME --api-server-authorized-ip-ranges $FWPUBLIC_IP,$CURRENT_IP/32

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7d721081-0c1c-abf3-a398-386a718446d0
* Version Independent ID: 92b5504d-e25a-be94-e5e5-151083a70607
* Content: [Azure Kubernetes Service (AKS) でユーザー定義ルート (UDR) をカスタマイズする](https://docs.microsoft.com/ja-jp/azure/aks/egress-outboundtype#enable-developer-access-to-the-api-server)
* Content Source: [articles/aks/egress-outboundtype.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/aks/egress-outboundtype.md)
* GitHub Login: @olprod

**Comment by srvbpigh** [comment]
Hello, @Darmuck
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @Darmuck , 

We truly appreciate your comment and we strive to improve your experience in docs.microsoft.com. However, we need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @Darmuck , 

We are following up on our previous comment. We need more information in order to be able to address your feedback. Can you please provide more detailed information and clarify your comment? 

Kind regards, 

Microsoft DOCS International Team

**Comment by V-vafune** [comment]
Hello, @Darmuck , 

Thanks once again for your comment. 

Unfortunately, we are still missing information and we are unable to process your feedback. We are closing this GitHub issue at this time but we encourage you to submit more feedback in the future. 

Kind regards, 

Microsoft DOCS International Team
