### ISSUE TITLE
ADLS Gen 2 is complicated to use

### ISSUE THREAD

**Issue by damochiz** [MicrosoftDocs/azure-docs.ja-jp#4574]
The following steps are a little confusing. It would be helpful if you could explain the setting items separately.  
Also, it says that it is necessary to grant with Storage Blob Data Owner access, but it failed if it's "Owner access". I didn't know why "Owner access" couldn't be accessed.  

> Azure Data Lake Storage Generation 2  
For an Azure Data Lake Storage Generation 2 (ADLS Gen 2) datastore, use register_azure_data_lake_gen2() to register a credential datastore connected to an Azure DataLake Gen 2 storage with service principal permissions. In order to utilize your service principal you need to register your application and grant the service principal with Storage Blob Data Owner access. Learn more about access control set up for ADLS Gen 2.  

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cd91721f-4a86-30cb-5e37-147c7319f0e6
* Version Independent ID: 98499c4f-ad83-81a4-e5db-af6415f79a98
* Content: [Azure Storage サービスに接続する - Azure Machine Learning](https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-access-data#azure-data-lake-storage-generation-2)
* Content Source: [articles/machine-learning/how-to-access-data.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/machine-learning/how-to-access-data.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @MayMSFT
* Microsoft Alias: **sihhu**

**Comment by srvbpigh** [comment]
Hello, @damochiz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55203](https://github.com/MicrosoftDocs/azure-docs/issues/55203) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @damochiz, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55203. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
