### ISSUE TITLE
英語版のセクションがないものがある

### ISSUE THREAD

**Issue by LifeRyuto** [MicrosoftDocs/azure-docs.ja-jp#4613]
https://docs.microsoft.com/en-us/azure/private-link/private-endpoint-dns#on-premises-workloads-using-a-dns-forwarder
こちらの日本語化もお願いできますでしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: a88af182-32aa-a8f3-359d-b92ae1cfb8c7
* Version Independent ID: 01ce07fc-4bc2-def5-9ecd-a80330ad9488
* Content: [Azure プライベート エンドポイントの DNS 構成](https://docs.microsoft.com/ja-jp/azure/private-link/private-endpoint-dns)
* Content Source: [articles/private-link/private-endpoint-dns.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/private-link/private-endpoint-dns.md)
* Service: **private-link**
* GitHub Login: @mblanco77
* Microsoft Alias: **allensu**

**Comment by srvbpigh** [comment]
Hello, @LifeRyuto
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@LifeRyuto  様、

フィードバックとご提案をいただき、ありがとうございます。  

現在、ファイルはローカライズ処理中です。このアーティクルはまもなくリリースされます。

サポートいただきありがとうございます。 

敬具

Microsoft DOCS グローバル エクスペリエンス チーム
