### ISSUE TITLE
Could you add notes to ja-jp document?

### ISSUE THREAD

**Issue by K-Ubu** [MicrosoftDocs/azure-docs.ja-jp#4618]
About Japanese site:
https://docs.microsoft.com/ja-jp/azure/lab-services/classroom-labs/tutorial-setup-classroom-lab
in English:
https://docs.microsoft.com/en-us/azure/lab-services/classroom-labs/tutorial-setup-classroom-lab

This English site has the following notes before "Publish the template VM" section.

>  Note
> Template VMs incur cost when running, so ensure that the template VM is shutdown when you don’t need it to be running.

But this notes does not exist before "テンプレート VM を発行する" section in Japanese page.
Could you please translate it and add it there? 
Please add more details like follows:
"テンプレート VM が実行中の場合コストが発生します。作成後のテンプレート VM は自動的に実行中のステータスとなるため、実行が不要な場合は停止してください。"

日本語での説明
英語ドキュメントで記載されている下記部分を、日本語ドキュメントにも記載してください。
>  Note
> Template VMs incur cost when running, so ensure that the template VM is shutdown when you don’t need it to be runn
ing.
日本語の例":
"テンプレート VM が実行中の場合コストが発生します。作成後のテンプレート VM は自動的に実行中のステータスとなるため、実行が不要な場合は停止してください。"

**Comment by srvbpigh** [comment]
Hello, @K-Ubu
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @K-Ubu

Thank you for your feedback.

The English page was recently updated, the changes in the localized versions will be updated soon.

Kind regards,
Microsoft DOCS International Team
