### ISSUE TITLE
IoT Hub Azure Private Link is now GA in all region

### ISSUE THREAD

**Issue by yahanda** [MicrosoftDocs/azure-docs.ja-jp#4620]
[フィードバックをこちらに入力してください]

IoT Hub Azure Private Link is now GA in all regions, but following description still remains in Japanese document. English documentation has already been updated, so it is better to update ja-jp doc as well.

> 利用可能なリージョン (プライベート エンドポイント)
次のリージョンで作成された IoT Hub でサポートされるプライベート エンドポイント:
米国東部
米国中南部
米国西部 2

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 514b0c8a-a670-e0d0-17e2-ec977a572dd5
* Version Independent ID: 22df9ffd-cfc7-e9d1-bb0f-a3b48ce58c17
* Content: [仮想ネットワークの Azure IoT Hub サポート](https://docs.microsoft.com/ja-jp/azure/iot-hub/virtual-network-support)
* Content Source: [articles/iot-hub/virtual-network-support.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/iot-hub/virtual-network-support.md)
* Service: **iot-fundamentals**
* GitHub Login: @jlian
* Microsoft Alias: **jlian**

**Comment by jlian** [comment]
Thanks. I think our localization team usually have a roughly 2 week turn around. The English documentation was updated today to coordinate with the official announcement, so would you mind waiting for another two weeks?

**Comment by yahanda** [comment]
@jlian Thank you for your response, I'm looking forward to update!

**Comment by srvbpigh** [comment]
Hello, @yahanda
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team
