### ISSUE TITLE
Can't finish a Spark job on display()

### ISSUE THREAD

**Issue by c-nova** [MicrosoftDocs/azure-docs.ja-jp#4622]
I have try to through this tutorial from yesterday.
But can't finish a Spark job at the code below on this page (I've waited about 3 hours):

sampled_taxi_df.show(5)
display(sampled_taxi_df.show(5))

Have you any idea?

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 075d1d7b-372e-0926-d74e-80cd173bd7a7
* Version Independent ID: 86d2610b-7050-5150-7894-e8b766a81911
* Content: [Apache Spark MLlib と Azure Synapse Analytics を使用して機械学習アプリを構築する](https://docs.microsoft.com/ja-jp/azure/synapse-analytics/spark/apache-spark-machine-learning-mllib-notebook)
* Content Source: [articles/synapse-analytics/spark/apache-spark-machine-learning-mllib-notebook.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/synapse-analytics/spark/apache-spark-machine-learning-mllib-notebook.md)
* Service: **synapse-analytics**
* GitHub Login: @euangms
* Microsoft Alias: **euang**

**Comment by euangms** [comment]
This is an older version of the article and its pulling 1.5 bill rows from East US Region, this can take a VERY long time.

It also has the wrong import statements and will fail later in the sample.

The first few code cells should look like this;

   import matplotlib.pyplot as plt
    from datetime import datetime
    from dateutil import parser
    from pyspark.sql.functions import unix_timestamp, date_format, col, when
    from pyspark.ml import Pipeline
    from pyspark.ml import PipelineModel
    from pyspark.ml.feature import RFormula
    from pyspark.ml.feature import OneHotEncoder, StringIndexer, VectorIndexer
    from pyspark.ml.classification import LogisticRegression
    from pyspark.mllib.evaluation import BinaryClassificationMetrics
    from pyspark.ml.evaluation import BinaryClassificationEvaluator

    from azureml.opendatasets import NycTlcYellow

    end_date = parser.parse('2018-06-06')
    start_date = parser.parse('2018-05-01')
    nyc_tlc = NycTlcYellow(start_date=start_date, end_date=end_date)
    filtered_df = nyc_tlc.to_spark_dataframe()

  # To make development easier, faster and less expensive down sample for now
    sampled_taxi_df = filtered_df.sample(True, 0.001, seed=1234)

    #sampled_taxi_df.show(5)
    display(sampled_taxi_df)

**Comment by srvbpigh** [comment]
Hello, @c-nova
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #55801](https://github.com/MicrosoftDocs/azure-docs/issues/55801) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @c-nova, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/55801. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
