### ISSUE TITLE
cannot create the openshift cluster by "az aro create"

### ISSUE THREAD

**Issue by FY0323** [MicrosoftDocs/azure-docs.ja-jp#4669]
[フィードバックをこちらに入力してください]

0. environment

* using Azure Cloud Shell by Windows Terminal 
* azure cli version：2.5.1

1. cannot execute the command

I tried the following command and the error was returned.

```
# command

> az aro create --resource-group aro-rg --name cluster --vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet --pull-secret '$(< pull-secret.txt)'

# error 
The behavior of this command has been altered by the following extension: aro
Invalid --pull-secret.
```

I tried the other command in [this page](https://docs.microsoft.com/ja-jp/azure/openshift/howto-create-private-cluster-4x), and the command was successfully executed.

```
> az aro create --resource-group aro-rg --name cluster --vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet --pull-secret @pull-secret.txt
```

2. We need to upgrade the quotas

The following command make the new errors about the resource quotas, but no information about resource quotas was described in this page.

```
# command
> az aro create --resource-group aro-rg --name cluster --vnet aro-vnet --master-subnet master-subnet --worker-subnet worker-subnet --pull-secret @pull-secret.txt
The behavior of this command has been altered by the following extension: aro

# error
Deployment failed. Correlation ID: < ID >. Resource quota of cores exceeded. Maximum allowed: 10, Current in use: 0, Additional requested: 36.
```

3. no descriptions about the default vm size

I wanted to upgrade the resource quotas but cannot, because no information about the default vm sizes of openshift clusters. I also found in [this page](https://docs.microsoft.com/en-us/cli/azure/aro?view=azure-cli-latest#az-aro-create), but I cannot.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 93aa980e-1970-235c-228a-7b19880171b8
* Version Independent ID: 6f7937a4-12e0-d61c-3bd8-c6347ec48385
* Content: [チュートリアル - Azure Red Hat OpenShift 4 クラスターを作成する](https://docs.microsoft.com/ja-jp/azure/openshift/tutorial-create-cluster#feedback)
* Content Source: [articles/openshift/tutorial-create-cluster.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/openshift/tutorial-create-cluster.md)
* Service: **container-service**
* GitHub Login: @sakthi-vetrivel
* Microsoft Alias: **suvetriv**

**Comment by srvbpigh** [comment]
Hello, @FY0323
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #56124](https://github.com/MicrosoftDocs/azure-docs/issues/56124) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Hello, @FY0323, 

Your contribution is much appreciated. Your feedback is related to the original documentation. 

Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/56124. 

We truly appreciate your contribution to our articles.  

Kind regards, 
Microsoft DOCS International Team
