### ISSUE TITLE
Don't translate Role Name in RBAC

### ISSUE THREAD

**Issue by tanaka-takayoshi** [MicrosoftDocs/azure-docs.ja-jp#47]
"ロール名" in RBAC should not be translated.
https://github.com/Microsoft/azure-docs.ja-jp/blob/master/articles/active-directory/role-based-access-built-in-roles.md

I can make PR, but I wonder this type of fix will be overwritten by automated translation. Could you check what is the best way to fix?

**Comment by SunnyDeng** [comment]
@tanaka-takayoshi could you please check again? the issue should be addressed at 8/23.
