### ISSUE TITLE
『認証用の環境変数を構成する』の macOS タブの内容について

### ISSUE THREAD

**Issue by kakisoft** [MicrosoftDocs/azure-docs.ja-jp#4772]
[フィードバックをこちらに入力してください]
https://docs.microsoft.com/ja-jp/azure/cognitive-services/cognitive-services-apis-create-account?tabs=multiservice%2Cunix
『認証用の環境変数を構成する』の macOS タブの内容についてです。

>環境変数を追加した後、変更を有効にするには、コンソール ウィンドウから source .bash_profile を実行します。

この内容について
「source .bash_profile を実行します。」
を
「source ~/.bash_profile を実行します。」
に変更してはどうでしょう？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7e866571-0651-bddb-f012-bf3bfe16f179
* Version Independent ID: 27429467-3c37-27da-b839-065268c6af23
* Content: [Azure portal で Cognitive Services リソースを作成する - Azure Cognitive Services](https://docs.microsoft.com/ja-jp/azure/cognitive-services/cognitive-services-apis-create-account?tabs=multiservice%2Cunix)
* Content Source: [articles/cognitive-services/cognitive-services-apis-create-account.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/cognitive-services/cognitive-services-apis-create-account.md)
* Service: **cognitive-services**
* GitHub Login: @aahill
* Microsoft Alias: **aahi**

**Comment by srvbpigh** [comment]
Hello, @kakisoft
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@kakisoft  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/56657) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
