### ISSUE TITLE
Degraded localized files om Azure SQL contents

### ISSUE THREAD

**Issue by miyamam** [MicrosoftDocs/azure-docs.ja-jp#4778]
The original Azure SQL documents were changed its structure without any change on each .md files. 
This change effected all localized documents as just “deleted”. 
Currently we lost all of Japanese localized document about Azure SQL without machine translated documents.

**Comment by srvbpigh** [comment]
Hello, @miyamam
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
Hi @ishasahni1 is this under your radar?
@SunnyDeng FYI

**Comment by ishasahni1** [comment]
@miyamam the content is getting localized and most of the content is already localized and published live. 

https://docs.microsoft.com/ja-jp/azure/azure-sql/azure-sql-iaas-vs-paas-what-is-overview.

@CeciAc FYI
