### ISSUE TITLE
The Japanese translation of "feature" is not "機能", shuld be "特徴量"

### ISSUE THREAD

**Issue by damochiz** [MicrosoftDocs/azure-docs.ja-jp#4784]
In some documents, including this document, the word "feature" that should be translated as "特徴量" has been translated into "機能".
For example, the following:

Incorrect:
不足している機能の値の補完

Correct:
不足している特徴量の値の補完

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: dc4e187d-ef1b-b3a8-6b06-0f41a89fec3e
* Version Independent ID: 26ed409d-f7d7-fd85-e6e4-deda1df6d1c3
* Content: [autoML を使用して、モデルとデプロイを作成する - Azure Machine Learning](https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-use-automated-ml-for-ml-models)
* Content Source: [articles/machine-learning/how-to-use-automated-ml-for-ml-models.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/machine-learning/how-to-use-automated-ml-for-ml-models.md)
* Service: **machine-learning**
* Sub-service: **core**
* GitHub Login: @tsikiksr
* Microsoft Alias: **nibaccam**

**Comment by srvbpigh** [comment]
Hello, @damochiz
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
こんにちは、@damochiz   

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/machine-learning/how-to-use-automated-ml-for-ml-models   

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  

敬具  
Microsoft DOCS International Team

**Comment by konabuta** [comment]
There are still wrong translations in the document. Could you check all document ?
