### ISSUE TITLE
既存の従量課金プランの割り当てについて

### ISSUE THREAD

**Issue by go-shinyashiki** [MicrosoftDocs/azure-docs.ja-jp#4791]
**Azure Functions のスケールとホスティング > 従量課金プラン**
> 同じリージョンの関数アプリを同じ従量課金プランに割り当てることができます。

ページ内の上記 1 文につきまして、GUI 上で以下操作を試しました。
・Azure Function を新規作成する際、Azure Portal で既に作成されているホスティングプラン「従量課金」で構成された App Service Plan を指定する

結果として、プラン選択時に従量課金で構成された App Service Plan は表示されず、新規 Azure Function を既存の従量課金プランに割り当てることはできませんでした。
もしドキュメントの誤りでしたら、該当の 1 文を削除していただけたら幸いです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 06436739-8586-23b1-6b69-1960e93c26be
* Version Independent ID: 8f7abfae-cf6d-56cb-1d20-f02041a6f6d9
* Content: [Azure Functions のスケールとホスティング](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-scale#feedback)
* Content Source: [articles/azure-functions/functions-scale.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/azure-functions/functions-scale.md)
* Service: **azure-functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by srvbpigh** [comment]
Hello, @go-shinyashiki
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #56905](https://github.com/MicrosoftDocs/azure-docs/issues/56905) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
こんにちは、@go-shinyashiki  

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。  

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/56905) を確認してください。  

記事の品質向上にご協力いただき誠にありがとうございました。   

敬具 , 
Microsoft DOCS International Team
