### ISSUE TITLE
Japanese translation of "Resolution" is not correct

### ISSUE THREAD

**Issue by eru01** [MicrosoftDocs/azure-docs.ja-jp#4799]
現文でResolutionとなっているSection見出しですが、日本語ドキュメントで解像度と訳されています。
おそらく解決策などの単語が適当だと思われます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: db5e2e62-b8fd-71e7-33c7-f0725aa9fda5
* Version Independent ID: 5d936c2a-b42f-885a-7cab-1db79714b621
* Content: [Python 3 対応 Linux Azure Virtual Machines システムでの VM 拡張機能の使用に関する問題](https://docs.microsoft.com/ja-jp/azure/virtual-machines/extensions/issues-using-vm-extensions-python-3#feedback)
* Content Source: [articles/virtual-machines/extensions/issues-using-vm-extensions-python-3.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/virtual-machines/extensions/issues-using-vm-extensions-python-3.md)
* Service: **virtual-machines-windows**
* GitHub Login: @v-miegge
* Microsoft Alias: **jparrel**

**Comment by srvbpigh** [comment]
Hello, @eru01
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@eru01

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-machines/extensions/issues-using-vm-extensions-python-3#feedback

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
