### ISSUE TITLE
The screenshot contains wrong keyword 

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#489]
The search keyword "キュー" in the screenshot should be in English, the specific keyword in Japanese doesn't work for the tutorial.

**Comment by CeciAc** [comment]
Hello, @kazshi 
 
Thank you for your feedback.
 
We need further information on this issue, can you please specify the URL where you saw this issue?

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kazshi
Please get back to us with this so we can work on the issue.

Kind regards,
Microsoft DOCS International Team

**Comment by kazshi** [comment]
The 7th image in the following link if I remember correctly, the instruction text in the Step.2 is correct ('queue' in English) but the text in the image is translated, which doesn't work.
https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-create-storage-queue-triggered-function

**Comment by CeciAc** [comment]
Hi @kazshi, we are still investigating this issue, will update the resolution later soon.

**Comment by LisandroSu** [comment]
Hello, @kazshi   
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. 
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
