### ISSUE TITLE
about printing

### ISSUE THREAD

**Issue by hitacboy** [MicrosoftDocs/azure-docs.ja-jp#521]
印刷すると２ページ目から白紙になります。なぜ？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f89338c0-968d-c22f-5b0d-ed3870ebc2fa
* Version Independent ID: 6daae1cc-f758-1d37-9de3-80a2832c08ef
* Content: [高速ネットワークを使った Azure 仮想マシンの作成](https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-cli)
* Content Source: [articles/virtual-network/create-vm-accelerated-networking-cli.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-network/create-vm-accelerated-networking-cli.md)
* Service: **virtual-network**
* Product: **unspecified**
* GitHub Login: @jimdial
* Microsoft Alias: **jdial**

**Comment by SunnyDeng** [comment]
#please-translate cc @CeciAc 

Hi @hitacboy -san, 
Thank you for the feedback! If I understand your question correction from our translator, you only can print the first page of this article. I tried on my printer, I can print all the pages until "VM の高速ネットワークが有効になりました。", total 8 printed pages as the default font size setting on 'Letter' size of my printer. The reason that no pages were printed further compared with English is because English articles get updated and our translation hasn't been finished., thus no published yet. 
If you still can't print all the pages, could you please indicate more details like: from which paragraph you can print out, what is the printer type and what is the printing settings. 

Thanks a lot for the support!

**Comment by hitacboy** [comment]
Hi Sunny,

    Thanx a lot for reply so quick.
     All of Azure documents on web site such as follows have same plage.
    Now a day, many various virus spread out from e-mail which has an attachment,
so I’m unwilling to do this, but it make clear so much this situation I guess.

It’s a preview of printing the pages on each documents.

https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-cli
[cid:image001.jpg@01D3EE91.453053A0]

    https://docs.microsoft.com/ja-jp/azure/cloud-shell/quickstart-powershell
     [cid:image002.jpg@01D3EE91.453053A0]

     I don’t know why it’s occurred in this manner. Please give me a comment and advice if you have.

     I send you information as follows, thank you.
     Browser:IE11 11.0.9600.18977/11.0.56(KB402946)
　   Printer: Canon iR-ADV C5535/5540 LIPSLX

　　Kindly, yours
      Hiroshi.


Hiroshi Minagawa
Engineer
Innovation Competency Center
Products Services and Solutions
Hitachi, Ltd.
IT Platform Products Management Division
292 Yoshida Town Totuka Ward Yokohama City Kanagawa Pref.
244-0817 Japan
+81 50-3173-9928
mailto: Hiroshi.minagawa.ea@hitachi.com<mailto:Hiroshi.minagawa.ea@hitachi.com>
Offie: http://www.hitachi.co.jp/Div/soft/access.html

**Comment by SunnyDeng** [comment]
Hi @hitacboy , 
sorry, i don't get the meaning when you say "All of Azure documents on web site such as follows have same plage.", do you mean when you try to print, you only can print the 1st page accross all docs.microsoft.com articles? 
What i did is very simple: find a blank place on the page, right click, select 'Print'. 
I don't repo using Edge + Xerox; and my colleague doesn't repo using Chrome+Cannon. Aka, both of us printed 8 pages based https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-cli. 
As we can't repro, i am closing this issue.  Suggest you to further investigate:
1.	Try another printer, or re-install printer driver
2.	Try another computer connected to the same printer
3.	Try a different browser with the same printer
4.	Try another article in Docs, or another article in another site.

Thanks again for your support to Azure DOCS!
-sunny
