### ISSUE TITLE
Bシリーズについて

### ISSUE THREAD

**Issue by norifumi3** [MicrosoftDocs/azure-docs.ja-jp#522]
Bシリーズについても記載していただきたいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 53b9177e-fd0f-84ce-f02e-b32c04e1217c
* Version Independent ID: b44a31b5-5fe9-9e03-08f6-709aa90cffeb
* Content: [Azure コンピューティング ユニットの概要](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/acu)
* Content Source: [articles/virtual-machines/windows/acu.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/acu.md)
* Service: **virtual-machines-windows**
* Product: **unspecified**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by CeciAc** [comment]
こんにちは、@norifumi3

ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 

ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 

ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 

記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 
Microsoft DOCS International Team
