### ISSUE TITLE
Missing "public client" in the description for code_challenge from Japanese content.

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#523]
Missing "public client" in the description for code_challenge from Japanese content.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2870d4a9-e204-023a-56a8-c34e56347b43
* Version Independent ID: 846fe3ae-21cb-e030-f68f-db73acef0c74
* Content: [Azure AD での OAuth 2.0 承認コード フローについて](https://docs.microsoft.com/ja-jp/azure/active-directory/develop/active-directory-protocols-oauth-code)
* Content Source: [articles/active-directory/develop/active-directory-protocols-oauth-code.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/develop/active-directory-protocols-oauth-code.md)
* Service: **active-directory**
* Product: **unspecified**
* GitHub Login: @hpsin
* Microsoft Alias: **hirsin**

**Comment by CeciAc** [comment]
Hello, @kazshi,

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kazshi 

Thank you for your linguistic feedback. 
 
We had this reviewed by our linguists and the issue does not repro anymore.

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards,
Microsoft DOCS International Team
