### ISSUE TITLE
左メニューのリンクが機能していない？ Link is not working?

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#539]
左メニューの[概念]-&gt;[マルチテナントのサポート]のクリックを試みましたがリンクが設定されておらずドキュメントに繋げる事ができませんでした。
この記事にアクセスするには、言語を英語にした後、[Concepts]-&gt;[Multi-tenant support]にて英語版のドキュメントにアクセスした後に日本語に切り替える必要がございました。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: fc26a594-5ae3-3471-aced-23fdb101ae02
* Version Independent ID: f1ee8b57-ab36-d7aa-a5ad-4856a293e756
* Content: [複数のサイトをホストするアプリケーション ゲートウェイを作成する - Azure PowerShell](https://docs.microsoft.com/ja-jp/azure/application-gateway/application-gateway-create-multisite-azureresourcemanager-powershell)
* Content Source: [articles/application-gateway/application-gateway-create-multisite-azureresourcemanager-powershell.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/application-gateway/application-gateway-create-multisite-azureresourcemanager-powershell.md)
* Service: **application-gateway**
* GitHub Login: @vhorne
* Microsoft Alias: **victorh**

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。 

Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/application-gateway/application-gateway-create-multisite-azureresourcemanager-powershell


記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 


敬具 

Microsoft DOCS International Team
