### ISSUE TITLE
Mistranslation for "Variable"

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#540]
Storage: Basic: IOPS > Variable
It's translated as a noun (a quantity or function that may assume any given value or set of values) so the current translation doesn't make sense for the context, it should be translated as an adjective.

https://docs.microsoft.com/en-us/azure/postgresql/concepts-pricing-tiers#storage

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 038ee2b6-8a76-a678-1069-3eb7c2808d73
* Version Independent ID: cd6cb2ea-9fff-9237-2168-a39eb24f2677
* Content: [Azure Database for PostgreSQL の価格レベル](https://docs.microsoft.com/ja-jp/azure/postgresql/concepts-pricing-tiers)
* Content Source: [articles/postgresql/concepts-pricing-tiers.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/postgresql/concepts-pricing-tiers.md)
* Service: **postgresql**
* GitHub Login: @jan-eng
* Microsoft Alias: **janeng**

**Comment by gosali** [comment]
Hello, @kazshi , 

  
Thank you for your feedback. 
 

We are actively reviewing your comments and will get back to you soon. 


Kind regards, 

Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kazshi ,
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/postgresql/concepts-pricing-tiers. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
