### ISSUE TITLE
DEAD LINK

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#543]
リンク切れしているリンクが複数あるので修正をお願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 33d54e4a-f724-1888-96ba-daf51a4e958e
* Version Independent ID: 21e0cb01-8397-a4cc-cc38-2054cb7d0421
* Content: [Azure の監視データの使用](https://docs.microsoft.com/ja-jp/azure/monitoring-and-diagnostics/monitoring-data-sources)
* Content Source: [articles/monitoring-and-diagnostics/monitoring-data-sources.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/monitoring-and-diagnostics/monitoring-data-sources.md)
* Service: **monitoring-and-diagnostics**
* GitHub Login: @johnkemnetz
* Microsoft Alias: **johnkem**

**Comment by CeciAc** [comment]
こんにちは、@ KeiroKamioka0000 

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10491](https://github.com/MicrosoftDocs/azure-docs/issues/10491) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@ KeiroKamioka0000  


ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/10491) を確認してください。 


記事の品質向上にご協力いただき誠にありがとうございました。  


敬具 

Microsoft DOCS International Team
