### ISSUE TITLE
Endpoint Protection

### ISSUE THREAD

**Issue by jittata** [MicrosoftDocs/azure-docs.ja-jp#549]
Linux での Azure Security Center と Azure 仮想マシンというタイトルの本ドキュメントで、Security Center を使う意義のところに
・エンドポイント保護の推奨事項について
と記載されておりますが、Microsoftのサポート部隊に確認したところ
エンドポイント保護についてはWindowsのみの対応であり、Linuxについてはサポートされないという回答をいただきました。

----------------------
弊社公開情報から、"Endpoint Protection" が Windows VM に対してのみ有効であることをご確認いただけます。

- Azure Security Center でのセキュリティ ソリューションの統合
https://docs.microsoft.com/ja-jp/azure/security-center/security-center-partner-integration#integrated-azure-security-solutions
※ "統合された Azure セキュリティ ソリューション" の項目をご覧ください。
----------------------

本ドキュメントの内容ですと、お客様から見た際に Linuxもエンドポイント保護に対応しているかのような誤解を招く表現になってしまっておりますので、修正いただけますでしょうか。

よろしくお願いいたします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 8872d787-1114-3fb0-8fd8-71bd29dea646
* Version Independent ID: 8c788217-4f35-1a29-7c89-d965d6268b1d
* Content: [Linux での Azure Security Center と Azure 仮想マシン](https://docs.microsoft.com/ja-jp/azure/security-center/security-center-linux-virtual-machine#feedback)
* Content Source: [articles/security-center/security-center-linux-virtual-machine.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/security-center/security-center-linux-virtual-machine.md)
* Service: **security-center**
* GitHub Login: @terrylan
* Microsoft Alias: **yurid**

**Comment by v-maudel** [comment]
こんにちは、@jittata ,

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #10381](https://github.com/MicrosoftDocs/azure-docs/issues/10381) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@jittata 

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら https://github.com/MicrosoftDocs/azure-docs/issues/10381 を確認してください。 

記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 

Microsoft DOCS International Team
