### ISSUE TITLE
'Perf' command is translated

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#552]
The command shouldn't be translated

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cfb49644-fb30-6357-708b-d2007fcab408
* Version Independent ID: 3c6c3cac-e738-52c3-bf89-6476ba04e816
* Content: [Azure Virtual Machines に関するデータの収集](https://docs.microsoft.com/ja-jp/azure/log-analytics/log-analytics-quick-collect-azurevm#view-data-collected)
* Content Source: [articles/log-analytics/log-analytics-quick-collect-azurevm.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/log-analytics/log-analytics-quick-collect-azurevm.md)
* Service: **log-analytics**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by gosali** [comment]
Hello, @kazshi , 

  
Thank you for your feedback. 

  

We are actively reviewing your comments and will get back to you soon. 

 

Kind regards, 

Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @kazshi   
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [Azure Virtual Machines に関するデータの収集](https://docs.microsoft.com/ja-jp/azure/log-analytics/log-analytics-quick-collect-azurevm#view-data-collected).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
