### ISSUE TITLE
QueueTrigger is at-most-once or at-least-once?

### ISSUE THREAD

**Issue by nakamacchi** [MicrosoftDocs/azure-docs.ja-jp#561]
In the section "Trigger - concurrency", it says that we don't need to write the queue trigger function as idempotent. Is it true?

"The queue trigger automatically prevents a function from processing a queue message multiple times; functions do not have to be written to be idempotent."

But if the host process (func.exe) is terminated unexpectedly during the execution of its function, it seems that the runtime will kick the queue trigger function again (after the timeout).

Of course, in normal case, the host process will not kick the queue trigger multiple times. But in the above case, the host process potentially kick the queue trigger more than one time.

If so, the document should be written as below.

- The dispatch strategy for Queue Trigger is not at-most-once, but at-least-once strategy.
- In normal case, the same message will not be kicked twice.
- But in abnormal case (such like unexpected process crash), the same message would be kicked twice or more.
- You should write the code as resilient especially in the cloud world, so you should write the queue triggered function as idempotent as far as possible.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5063120f-d48e-6a76-8e6d-208ead92d187
* Version Independent ID: 72bb8ecc-6dec-079a-a9d4-52205466a8c6
* Content: [Azure Functions における Azure Queue Storage のバインド](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-bindings-storage-queue#trigger---concurrency)
* Content Source: [articles/azure-functions/functions-bindings-storage-queue.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-functions/functions-bindings-storage-queue.md)
* Service: **functions**
* GitHub Login: @tdykstra
* Microsoft Alias: **tdykstra**

**Comment by gosali** [comment]
Hello, @nakamacchi , 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation. 

Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page. 

If you have any feedback related to the documentation, please feel free to log it through this channel. 

We truly appreciate your contribution to our articles.  
 
@SunnyDeng 
Kind regards, 
Microsoft DOCS International Team
