### ISSUE TITLE
Japanese title for 'Get started with Log Analytics' is confusing

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#564]
Currently the title 'Get started with Log Analytics' is translated as 'Log Analytics の起動と開始' which is confusing (meaning 'Launching/Starting Log Analytics'), but the destination is 'Log Analytics Documentation'

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 521c75f5-5d71-10b5-df71-a8a6c0204a2e
* Version Independent ID: 4343bd59-d34e-8d99-a723-292fc27b60bd
* Content: [Log Analytics についてよく寄せられる質問](https://docs.microsoft.com/ja-jp/azure/log-analytics/log-analytics-faq)
* Content Source: [articles/log-analytics/log-analytics-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/log-analytics/log-analytics-faq.md)
* Service: **log-analytics**
* GitHub Login: @MGoedtel
* Microsoft Alias: **magoedte**

**Comment by gosali** [comment]
Hello, @kazshi , 

Thank you for your feedback. 

We are actively reviewing your comments and will get back to you soon. 

Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @kazshi 
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [Log Analytics についてよく寄せられる質問](https://docs.microsoft.com/ja-jp/azure/log-analytics/log-analytics-faq).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
