### ISSUE TITLE
サンプルコードのTypo

### ISSUE THREAD

**Issue by planethouki** [MicrosoftDocs/azure-docs.ja-jp#568]
「関数コードを更新する」のサンプルコード
19行目の"Microsoft.Resources/subscriptions/resourcegroups"は、
"Microsoft.Resources/subscriptions/resourceGroups"でないとうまくいきませんでした。
（resource'G'roupsにしないと、必ずif文へ入ってしまう）

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: aaeaad45-a7ae-b995-d0a2-29d56e0d0556
* Version Independent ID: 48c01c24-a4b0-dcc2-c307-60c0d5bd5ad1
* Content: [ジェネリック webhook でトリガーされる Azure 関数の作成](https://docs.microsoft.com/ja-jp/azure/azure-functions/functions-create-generic-webhook-triggered-function)
* Content Source: [articles/azure-functions/functions-create-generic-webhook-triggered-function.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-functions/functions-create-generic-webhook-triggered-function.md)
* Service: **functions**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by gosali** [comment]
こんにちは、@planethouki 

 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。  

 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。  

 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。  

 記事の品質向上にご協力いただき誠にありがとうございました。   

 敬具  
CC: @SunnyDeng 
Microsoft DOCS International Team
