### ISSUE TITLE
wrong translation for UI element:   Step.3 in Create a server-level firewall rule

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#574]
https://docs.microsoft.com/ja-jp/azure/sql-data-warehouse/load-data-wideworldimportersdw#get-the-fully-qualified-server-name
「そのデータベースの Azure Portal ページの [要点] ウィンドウで、サーバー名を見つけてコピーします。」
[要点] is not correct, actual UI is [基本] - it's minor translated issue but I was confused

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: d26e70c3-2769-5b47-2bda-8a4a7f0239d0
* Version Independent ID: 558a36bd-e151-1e4c-4427-fc52eb2d91e3
* Content: [チュートリアル: Azure SQL Data Warehouse へのデータの読み込み](https://docs.microsoft.com/ja-jp/azure/sql-data-warehouse/load-data-wideworldimportersdw#get-the-fully-qualified-server-name)
* Content Source: [articles/sql-data-warehouse/load-data-wideworldimportersdw.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-data-warehouse/load-data-wideworldimportersdw.md)
* Service: **sql-data-warehouse**
* GitHub Login: @Ckarst
* Microsoft Alias: **cakarst**

**Comment by DavidPrio** [comment]
Hello, @kazshi ,
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @kazshi   
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [チュートリアル: Azure SQL Data Warehouse へのデータの読み込み](https://docs.microsoft.com/ja-jp/azure/sql-data-warehouse/load-data-wideworldimportersdw#get-the-fully-qualified-server-name).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
