### ISSUE TITLE
Misleading translation

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#576]
「使用可能なコア サイズに制約があります」
This translation seems to imply that there are restrictions on core sizes, not that you can choose to use the constrained core size feature (same specs with fewer cores), which is the intent. 
See this doc: https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/constrained-vcpu
A better translation would be something like 少数のコアの構成でも提供しています。, but if you want to stick to the translation used on the other page, maybe 制約付きの vCPU サイズに対応しています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 58fe6a40-0b95-f1ed-db11-7a49d4a97ecf
* Version Independent ID: 54269236-da55-a1cd-01df-79a0458d9ac9
* Content: [Windows Azure VM のサイズ - メモリ](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/sizes-memory)
* Content Source: [articles/virtual-machines/windows/sizes-memory.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/sizes-memory.md)
* Service: **virtual-machines-windows**
* GitHub Login: @jonbeck7
* Microsoft Alias: **jonbeck**

**Comment by LisandroSu** [comment]
Hello, @dcbrown16 , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @dcbrown16 ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://github.com/MicrosoftDocs/azure-docs-pr.ja-jp/blob/live/includes/virtual-machines-common-sizes-memory.md  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
