### ISSUE TITLE
License requirements are inconsistent.

### ISSUE THREAD

**Issue by kaminagi107** [MicrosoftDocs/azure-docs.ja-jp#5775]
The license requirements differ between what is documented and what is actually displayed.

**[In this doc]**
[en-us] Any Azure AD license (Free/O365/P1/P2) is sufficient to ingest sign-in logs into Azure Sentinel. Additional per-gigabyte charges may apply for Azure Monitor (Log Analytics) and Azure Sentinel.
[ja-jp] 任意の Azure AD ライセンス (Free、O365、P1、P2) があれば、Azure Sentinel にサインイン ログを取り込むことができます。 Azure Monitor (Log Analytics) と Azure Sentinel には、追加のギガバイト単位の料金が適用される場合があります。

**[In Azure Sentinel AAD Connector]** 
[en-us] License: required AAD P2
[ja-jp] ライセンス: AAD P2 が必要

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 4ff6ed5e-5b5c-e516-aeae-c9bf0a0c69c9
* Version Independent ID: 63ecbda4-59e4-343e-e640-1c6be2ce805d
* Content: [Azure Sentinel に Azure Active Directory のデータを接続する](https://docs.microsoft.com/ja-jp/azure/sentinel/connect-azure-active-directory)
* Content Source: [articles/sentinel/connect-azure-active-directory.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/master/articles/sentinel/connect-azure-active-directory.md)
* Service: **azure-sentinel**
* Sub-service: **azure-sentinel**
* GitHub Login: @yelevin
* Microsoft Alias: **yelevin**

**Comment by yelevin** [comment]
Thanks for reaching out!

The documentation is correct; it was verified just a few days ago. The instructions in the user interface are awaiting being updated in accordance with this recent change. You should see it in the user interface as well in the near future.

**Comment by yelevin** [comment]
My apologies, I misread something - the documentation has been reverted to its current correct state (P2 license required); both it and the user interface should be updated with the new status (any license sufficient) when it takes effect soon.

**Comment by kaminagi107** [comment]
Thank you for confirmation.
I was able to confirm that it is also reflected in Japanese Docs page.

**Comment by yelevin** [comment]
The new status took effect February 1.

**Comment by kaminagi107** [comment]
I was able to confirm that the UI of my environment was also changed to the new content.
