### ISSUE TITLE
「Blob path ends with」プロパティの記載例について

### ISSUE THREAD

**Issue by keisukef** [MicrosoftDocs/azure-docs.ja-jp#590]
[フィードバックをこちらに入力してください]

例として掲載している画面キャプチャの「Blob path ends with」プロパティに「.csv」と記載していますが、この設定でEventTriggerを登録した場合、BlobStorageのイベントのSUFFIX FILTERには「/blobs/.csv」と登録されます。
マニュアルの例から、「Blob path ends with」プロパティに「.csv」と入力することで、拡張子がcsvのファイルは全て条件に一致する設定が可能、というように読み取れたために、思ったような動作ができませんでしたので、可能であればその旨を注意として記載していただくか、画面キャプチャを修正して頂けると読者が混乱せずに済むのではないかと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: b7ee5166-ff40-f4ed-ce07-5312f935e388
* Version Independent ID: 68f01b43-e3b2-003b-24cb-446a08aa0c1b
* Content: [Azure Data Factory でイベントベースのトリガーを作成する](https://docs.microsoft.com/ja-jp/azure/data-factory/how-to-create-event-trigger)
* Content Source: [articles/data-factory/how-to-create-event-trigger.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/data-factory/how-to-create-event-trigger.md)
* Service: **data-factory**
* GitHub Login: @douglaslMS
* Microsoft Alias: **douglasl**

**Comment by LisandroSu** [comment]
こんにちは、@keisukef

ご意見ありがとうございます。

私たちはあなたのコメントを積極的にレビューしており、すぐにあなたに連絡します。
 
敬具、
Microsoft DOCSインターナショナルチーム

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #12243](https://github.com/MicrosoftDocs/azure-docs/issues/12243) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@keisukef
 
ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。
 
そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら   (https://github.com/MicrosoftDocs/azure-docs/issues/12243) を確認してください。
 
記事の品質向上にご協力いただき誠にありがとうございました。
 
敬具
 
Microsoft DOCS International   Team

**Comment by LisandroSu** [comment]
This is just the semantics of how the blob triggers work with Azure Event Grid. We are making it simpler for the customer, so that he doesn’t have to get lost in the semantics, and doesn't have to remember that he needs to enter /blobs/ as well in front of the .csv.

#please-translate

**Comment by LisandroSu** [comment]
こんにちは @keisukef 、

これはAzureデータファクトリチームからの回答です

_これは、BLOBトリガーがAzure Event Gridでどのように動作するかのセマンティクスです。 私たちは顧客にとってシンプルにしているので、セマンティクスに迷う必要はなく、.csvの前に/ blobs /を入力する必要があることを覚えておく必要はありません。_

ありがとうございました
