### ISSUE TITLE
Portal text change

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#599]
すみません、ポータル内のテキストに対してフィードバックを寄せる窓口が分からないので一旦この関連ドキュメントから提出します。
Load Balancer の負担分散規則のメニューで「セッション永続化」に以下のテキストがありますが、「5D;」が入っているのは何等かのエンコード間違いのようで、混乱を招く記載ですので修正願います。

「セッション永続化は、セッション期間中にクライアントからのトラフィックをバックエンド プール内の同じ仮想マシンで処理する必要があることを指定します。[なし]5D; は同じクライアントからの連続する要求をどの仮想マシンが処理しても構わないことを示します。[クライアント IP]5D; は、同じクライアント IP アドレスからの連続する要求を同一の仮想マシンで処理することを示します。[クライアント IP とプロトコル]5D; は、同じクライアント IP アドレスとプロトコルの組み合わせからの要求を同じ仮想マシンで処理することを示します。」

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 0e1e7cb2-c5a7-7122-c729-dc259db99a40
* Version Independent ID: 45c6fd72-5114-fcda-0bab-2d80ac6bed33
* Content: [Load Balancer のカスタム プローブを使用して正常性の状態を監視する](https://docs.microsoft.com/ja-jp/azure/load-balancer/load-balancer-custom-probe-overview)
* Content Source: [articles/load-balancer/load-balancer-custom-probe-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/load-balancer/load-balancer-custom-probe-overview.md)
* Service: **load-balancer**
* GitHub Login: @KumudD
* Microsoft Alias: **kumud**

**Comment by dcbrown16** [comment]
ちなみにここで日本語テキストの表題でコメントを出そうとすると、「You must use this format:」とだけ表示され、エラー内容から何すればいいか不明です。英語にすれば正常に投稿できました。

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16 

フィードバックをお送りいただきありがとうございました。 

この問題を処理するには追加情報が必要です。 テキストの元のURLを入力してください。

敬具 
Microsoft DOCS International Team

**Comment by dcbrown16** [comment]
Azure ポータル内のテキストです。
Load Balancer ＞負担分散規則＞（規則を選ぶ）＞「セッション永続化」のツールチップ（？マーク）
確認できたURL はこちらの環境のサブスクリプションやリソース情報が入っているため、こちらでは共有できませんが、画面画像を添付します。
![loadbalancerule](https://user-images.githubusercontent.com/34466884/43108624-8f4a4c24-8e97-11e8-88b8-8deaf0291a4e.JPG)

**Comment by kazshi** [comment]
Reported the issue to Cloud and AI  Intl Localization Feedback community.
This can be closed.

**Comment by dcbrown16** [comment]
Thanks.
