### ISSUE TITLE
Fix link name

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#600]
「PowerShell でスナップショットから仮想マシンを作成する」のスクリプトを参照してください。
とありますが、PowerShell ではなく CLI です。
リンク先：「CLI でスナップショットから仮想マシンを作成する」

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 70653a41-2611-4649-af4f-fa8cf24e99e1
* Version Independent ID: 4cf0ed02-3ee6-6417-68c7-4b70298a0076
* Content: [Azure で VHD のスナップショットを作成する](https://docs.microsoft.com/ja-jp/azure/virtual-machines/linux/snapshot-copy-managed-disk)
* Content Source: [articles/virtual-machines/linux/snapshot-copy-managed-disk.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/linux/snapshot-copy-managed-disk.md)
* Service: **virtual-machines-linux**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: [Azure で VHD のスナップショットを作成する](https://docs.microsoft.com/ja-jp/azure/virtual-machines/linux/snapshot-copy-managed-disk)

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
