### ISSUE TITLE
"Cloud Services" shouldn't be translated (localized)

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#610]
In the following section, "Cloud Services" (classic service name) is translated into "クラウド サービス" but it shouldn't be translated since the service name is as in English - it's really confusing.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 948b29e3-d488-0a0e-89c7-42849a93522d
* Version Independent ID: 8c986086-9343-4b99-ae53-f4fd1159d4f8
* Content: [Azure での Windows VM の可用性管理](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/manage-availability#understand-vm-reboots---maintenance-vs-downtime)
* Content Source: [articles/virtual-machines/windows/manage-availability.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/manage-availability.md)
* Service: **virtual-machines-windows**
* GitHub Login: @cynthn
* Microsoft Alias: **cynthn**

**Comment by LisandroSu** [comment]
Hello, @kazshi 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kazshi, 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/manage-availability#understand-vm-reboots---maintenance-vs-downtime. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
