### ISSUE TITLE
Japanese Document says preview.

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#613]
It seems like Japanese Localized Document says still in preview.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1aa8c1f7-dc55-7129-95be-687a0b11a636
* Version Independent ID: 4a09b58a-9fd2-69fc-0348-e6d4d0956a20
* Content: [Azure ファイル同期 (プレビュー) のデプロイの計画](https://docs.microsoft.com/ja-jp/azure/storage/files/storage-sync-files-planning)
* Content Source: [articles/storage/files/storage-sync-files-planning.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/storage/files/storage-sync-files-planning.md)
* Service: **storage**
* GitHub Login: @wmgries
* Microsoft Alias: **wgries**

**Comment by wmgries** [comment]
@tamram please advise on how to expedite the translation into Japanese.

**Comment by KeiroKamioka0000** [comment]
Japanese Title :Azure ファイル同期 (プレビュー) のデプロイの計画
https://docs.microsoft.com/ja-jp/azure/storage/files/storage-sync-files-planning

 (プレビュー) stands for (Preview) in English.
I think just removing  (プレビュー) would be good because original English document removed the (preview) part from the document.

English Title: Planning for an Azure File Sync deployment
https://docs.microsoft.com/en-us/azure/storage/files/storage-sync-files-planning

**Comment by LisandroSu** [comment]
Hello @KeiroKamioka0000 

Thank you for your feedback.

It seems that they already removed (プレビュー) from the document's title. Can you confirm it?

Regards,
Microsoft DOCS International Team

**Comment by KeiroKamioka0000** [comment]
Confirmed

**Comment by wmgries** [comment]
@KeiroKamioka0000 Thanks for pointing this out! #please-close @LisandroSu @Adam-Smith-MSFT

**Comment by LisandroSu** [comment]
Thanks everybody!

I'll be closing the issue.
