### ISSUE TITLE
migrated-<region>を含むresource-groupが削除できません

### ISSUE THREAD

**Issue by otakesh** [MicrosoftDocs/azure-docs.ja-jp#625]
ポータルからmigrated-&lt;region&gt;単体を削除しようとするとエラーになります。
ポータルからmigrated-&lt;region&gt;を含むresource-groupを削除しようとすると、1時間以上たってもDeletingのままです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3744debf-7d5d-b71d-91ab-fc9a7037231b
* Version Independent ID: e530339f-aabf-3ba5-7c82-7296dc3b46de
* Content: [更新された Azure Batch AI API への移行](https://docs.microsoft.com/ja-jp/azure/batch-ai/migrate-to-new-api)
* Content Source: [articles/batch-ai/migrate-to-new-api.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/batch-ai/migrate-to-new-api.md)
* Service: **batch-ai**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by LisandroSu** [comment]
こんにちは、@otakesh

ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 

ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 

ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 

記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 
Microsoft DOCS International Team
