### ISSUE TITLE
Japanese: wrong translation for 'capacity'

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#629]
'capacity' (in 'Read Scale-Out allows you to load balance Azure SQL Database read-only workloads using the **capacity** of read-only replicas.') is translated wrongly so the current translated sentence doesn't make sense. 

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 7a2961d1-4448-11b7-2dc2-3b738bd70939
* Version Independent ID: 206eb022-25c4-66d7-7285-0d53a84956e3
* Content: [Azure SQL Database - レプリカでの読み取りクエリ](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-read-scale-out)
* Content Source: [articles/sql-database/sql-database-read-scale-out.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-database/sql-database-read-scale-out.md)
* Service: **sql-database**
* GitHub Login: @anosov1960
* Microsoft Alias: **sashan**

**Comment by LisandroSu** [comment]
Hello, @kazshi ,  
  
Thank you for your feedback. 
  
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages [Azure SQL Database - レプリカでの読み取りクエリ](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-read-scale-out).  
 
We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 
 
Kind regards, 
Microsoft DOCS International Team
