### ISSUE TITLE
Actionの翻訳

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#644]
英語の「Action」という種類が「アクションを表示します。」となってしまっています。
下記のリンクでは「アクション」になっていますが、そもそもこの欄はロール定義で Action であるか DataAction であるかを見分けるための情報のようですので、報告元のページでは Action, 下記のページで Actions が適切かと思います。
https://docs.microsoft.com/ja-jp/azure/role-based-access-control/role-definitions

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 33219707-3b9f-cc6b-541e-a806dc82622a
* Version Independent ID: b4e96391-bcf9-1f30-cb44-ed339469da4f
* Content: [Azure Resource Manager のリソース プロバイダー操作](https://docs.microsoft.com/ja-jp/azure/role-based-access-control/resource-provider-operations)
* Content Source: [articles/role-based-access-control/resource-provider-operations.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/role-based-access-control/resource-provider-operations.md)
* Service: **role-based-access-control**
* GitHub Login: @rolyon
* Microsoft Alias: **rolyon**

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16 

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: 
https://docs.microsoft.com/ja-jp/azure/role-based-access-control/resource-provider-operations
https://docs.microsoft.com/ja-jp/azure/role-based-access-control/role-definitions

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
