### ISSUE TITLE
Run duration translation

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#659]
「時間継続時間」とあるのは、正しくは「実行継続時間」になると思います。
ご確認のほどよろしくお願いします。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 845c4db9-1f3a-26d1-5061-c018cb1fe336
* Version Independent ID: c2a03981-a0aa-64a5-2659-e10202e5bb14
* Content: [制限と構成 - Azure Logic Apps](https://docs.microsoft.com/ja-jp/azure/logic-apps/logic-apps-limits-and-config#run-duration-and-retention-limits)
* Content Source: [articles/logic-apps/logic-apps-limits-and-config.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/logic-apps/logic-apps-limits-and-config.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 
敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

Microsoft   の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント   サイト上の次のページの更新された記事に公開しました: [制限と構成 - Azure Logic Apps](https://docs.microsoft.com/ja-jp/azure/logic-apps/logic-apps-limits-and-config#run-duration-and-retention-limits)

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。

敬具
Microsoft DOCS International   Team
