### ISSUE TITLE
Add-AzureRmServiceFabricApplicationCertificate 実行でエラーとなりました

### ISSUE THREAD

**Issue by isobe4u** [MicrosoftDocs/azure-docs.ja-jp#660]
クラスター ノードに証明書をインストールするで以下のコマンド

# Add a certificate to all the VMs in the cluster.
Add-AzureRmServiceFabricApplicationCertificate -ResourceGroupName $groupname -Name $clustername -SecretIdentifier $secret.Id -Verbose

を実行したところ、以下のエラーが発生します。

The secret's JSON representation retrieved from
https://&lt;some value&gt;.vault.azure.net/secrets/VotingAppPFX/&lt;some value&gt;
has a data field which is not a properly formatted PFX file,
or the password provided does not decode the PFX file correctly.

locahost の証明書はドキュメントの通り、以下のコマンドで
PS C:\program files\microsoft sdks\service fabric\clustersetup\secure&gt; .\CertSetup.ps1 -Install -CertSubjectName CN=localhost
作成し、certlm.msc での操作も [はい、秘密キーをエクスポートします] を選択しました。
上記で説明のない certlm.msc でのオプションは以下の
選択で作成しましたがこれが問題でしょうか。

ON  証明書のパスにある証明書を可能であればすべて含む
OFF 正しくエクスポートされたときは秘密キーを削除する
ON  すべての拡張プロパティをエクスポートする
ON  証明書のプライバシーを有効にする

パスワード：!Password321#
暗号化：AES256-SHA256

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3ac102a5-e9ad-0046-f217-446f1ad263c5
* Version Independent ID: a47523e2-0c30-dee4-0037-5f58836fa37f
* Content: [Azure の Service Fabric アプリに HTTPS エンドポイントを追加する](https://docs.microsoft.com/ja-jp/azure/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint)
* Content Source: [articles/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/service-fabric/service-fabric-tutorial-dotnet-app-enable-https-endpoint.md)
* Service: **service-fabric**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #13761](https://github.com/MicrosoftDocs/azure-docs/issues/13761) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@isobe4u

ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/13761) を確認してください。 

記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 
Microsoft DOCS International Team
