### ISSUE TITLE
typo/conversion-error

### ISSUE THREAD

**Issue by kazshi** [MicrosoftDocs/azure-docs.ja-jp#662]
See the 2nd paragraph containing the following error
error: "仕様法王"
correct: "使用方法" or something like that

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 3799662b-8f0f-c4e6-26b5-b2ff24a9242a
* Version Independent ID: 0c93223c-f28b-7ca7-0d10-c19e5fea9197
* Content: [Microsoft Azure Windows VM 用の非管理対象ディスク ストレージ (ページ BLOB) とマネージド ディスク ストレージについて](https://docs.microsoft.com/ja-jp/azure/virtual-machines/windows/about-disks-and-vhds)
* Content Source: [articles/virtual-machines/windows/about-disks-and-vhds.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/windows/about-disks-and-vhds.md)
* Service: **virtual-machines-windows**
* GitHub Login: @roygara
* Microsoft Alias: **rogarana**

**Comment by LisandroSu** [comment]
Hello, @kazshi , 
  
Thank you for your feedback. 
  
We are actively reviewing your comments and will get back to you soon. 
 
Kind regards, 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @kazshi , 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages XXX. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
