### ISSUE TITLE
`Max log size` doesn't have units for numbers

### ISSUE THREAD

**Issue by yamatoya** [MicrosoftDocs/azure-docs.ja-jp#667]
`Max log size` doesn't have units for numbers. I don't know `MB` or `GB`. I maybe think `GB`

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5676aae7-73bc-c084-174b-50ba4fd7be77
* Version Independent ID: 0998f821-0f03-a833-b4b3-0d6ebd9468e5
* Content: [Azure SQL Database の仮想コアベースのリソース制限 - 単一データベース](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-vcore-resource-limits-single-databases)
* Content Source: [articles/sql-database/sql-database-vcore-resource-limits-single-databases.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-database/sql-database-vcore-resource-limits-single-databases.md)
* Service: **sql-database**
* GitHub Login: @CarlRabeler
* Microsoft Alias: **carlrab**

**Comment by CarlRabeler** [comment]
@yamatoya thank you. Fixing now

**Comment by LisandroSu** [comment]
Hello, @CarlRabeler 

Since this issue affects the source ENU repo, do you want me to move it there? Or how should we proceed with it?

Regards,
Microsoft DOCS International Team

**Comment by CarlRabeler** [comment]
Fixed – see https://github.com/MicrosoftDocs/azure-docs-pr/pull/49963

**Comment by LisandroSu** [comment]
Thanks @CarlRabeler !

I'll be closing the issue now.
-----------------------------------
@yamatoya,

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
