### ISSUE TITLE
mistake createDatabase command

### ISSUE THREAD

**Issue by GitHub30** [MicrosoftDocs/azure-docs.ja-jp#672]
I got below error.
[INS-04008] Invalid combination of arguments passed from command line. One or more mandatory dependent arguments are not passed for the argument: -storageType
I run this.
dbca -silent \
       -createDatabase \
       -templateName General_Purpose.dbc \
       -gdbname cdb1 \
       -sid cdb1 \
       -responseFile NO_VALUE \
       -characterSet AL32UTF8 \
       -sysPassword OraPasswd1 \
       -systemPassword OraPasswd1 \
       -createAsContainerDatabase true \
       -numberOfPDBs 1 \
       -pdbName pdb1 \
       -pdbAdminPassword OraPasswd1 \
       -databaseType MULTIPURPOSE \
       -automaticMemoryManagement false \
       -storageType FS \
       -ignorePreReqs

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 279359a4-139a-ee4b-027b-4f43c538b90f
* Version Independent ID: 950014e2-2457-6045-eefd-865bd1c1fb76
* Content: [Azure VM での Oracle データベースの作成](https://docs.microsoft.com/ja-jp/azure/virtual-machines/workloads/oracle/oracle-database-quick-create)
* Content Source: [articles/virtual-machines/workloads/oracle/oracle-database-quick-create.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-machines/workloads/oracle/oracle-database-quick-create.md)
* Service: **virtual-machines-linux**
* GitHub Login: @romitgirdhar
* Microsoft Alias: **rogirdh**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14041](https://github.com/MicrosoftDocs/azure-docs/issues/14041) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @GitHub30 ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/14041.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
