### ISSUE TITLE
暗号化ディスク復元時のSet-AzureRmVMDiskEncryptionExtensionの実行タイミング

### ISSUE THREAD

**Issue by katakura** [MicrosoftDocs/azure-docs.ja-jp#676]
「復元されたディスクからの VM の作成」の章にて、暗号化されたディスクの復元時には「Set-AzureRmVMDiskEncryptionExtension」コマンドレットを実行する旨が追記されたようですが、章に記載の手順の流れから「New-AzureRmVM」による仮想マシン作成前に実行する手順に読めてしまいます。実際にはNew-AzureRmVM実行前にSet-AzureRmVMDiskEncryptionExtensionは実行不可(エラーとなる)と存じますので、記載順序の検討が必要かと。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e50dfe50-c177-f976-753b-9fa689d20f92
* Version Independent ID: 7f787259-8ce5-9ba6-8df7-58ab0b89dd5c
* Content: [Resource Manager でデプロイされた VM のバックアップを PowerShell を使用してデプロイおよび管理する](https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-vms-automation#feedback)
* Content Source: [articles/backup/backup-azure-vms-automation.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/backup/backup-azure-vms-automation.md)
* Service: **backup**
* GitHub Login: @markgalioto
* Microsoft Alias: **markgal**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14124](https://github.com/MicrosoftDocs/azure-docs/issues/14124) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@katakura

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/14124) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
