### ISSUE TITLE
The brand name is wrong. The correct brand name is "direct" and not "Direct".

### ISSUE THREAD

**Issue by mike-neck** [MicrosoftDocs/azure-docs.ja-jp#685]
[フィードバックをこちらに入力してください]

The wrong brand name "Direct" is used throughout the document. The correct brand name is "direct". All characters are lower cases. Please do not capitalize the first character.(https://direct4b.com/ja/)

ブランド名が間違えています。ドキュメントでは「Direct」と書かれていますが、すべてが小文字の「direct」が正しいブランド名です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1a402f6f-9c49-50ec-df27-fce8a17c5d44
* Version Independent ID: 960a880a-9d7a-d1f1-96cc-cf8dbe9c6c15
* Content: [チュートリアル: Azure Active Directory と Direct の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/direct-tutorial)
* Content Source: [articles/active-directory/saas-apps/direct-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/saas-apps/direct-tutorial.md)
* Service: **active-directory**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by jeevansd** [comment]
@chetansriv and @v-viinde Can you please update the tutorial and change the name in the tutorial?

**Comment by jeevansd** [comment]
@mike-neck Thanks for reporting the issue. We will update the tutorial.

**Comment by LisandroSu** [comment]
Hello, @mike-neck ,
 
Thank you for your feedback.

Hi @jeevansd Should I close this issue, or move it to the ENU repo?

Thanks!
Microsoft DOCS International Team

**Comment by jeevansd** [comment]
@LisandroSu Can you please move this to the ENU repo? We will fix there and then Loc team can merge the changes here.

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #14557](https://github.com/MicrosoftDocs/azure-docs/issues/14557) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
Hello, @mike-neck ,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/14557.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team

@jeevansd Done! Thanks for the quick answer!
