### ISSUE TITLE
new articles + major changes "Build a serverless web app in Azure"

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/azure-docs.ja-jp#697]
There is a mistake in translation of the following articles. So, I want to correct misinterpretation and send Pull Request.
- https://docs.microsoft.com/ja-jp/azure/functions/tutorial-static-website-serverless-api-with-database

However, I can not find the original file of the above article in this repository.
So, following the description of the Readme, I would like to create a new article.
If the original file already exists, I would like to send a pull request. Would you please let me know.

> Community - new articles + major changes: If you're part of the Azure community and you want to create a new article or submit major changes, please submit an issue to start a conversation with the documentation team. Once you've agreed to a plan, you'll need to work with an employee to help bring that new content in through a combination of work in the public and private repositories.

**Comment by LisandroSu** [comment]
Hello, @changeworld 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hello, @changeworld 

Can you provide us the changes you want to make through here? Since that's a private repo, there's no other way for now. We are working on ways to make it easier but we don't know how long that will take.

Thank you for your understanding,
Microsoft DOCS International Team

**Comment by gosali** [comment]
[intro.zip](https://github.com/MicrosoftDocs/azure-docs.ja-jp/files/2380272/intro.zip)

**Comment by LisandroSu** [comment]
Hello, @changeworld 

It seems that the repo for Japanese is no longer private. Here's the link where the Markdown files are: https://github.com/MicrosoftDocs/azure-interactive-pr.ja-JP/tree/live/AzureInteractive/includes

Please check if you can create Pull Requests there.

Thanks!

**Comment by changeworld** [comment]
Hi, @LisandroSu

Thank you for telling me the location of the files.
I will immediately create a pull request and send it to you.
