### ISSUE TITLE
PowerShell云々の文章は原文にはありません

### ISSUE THREAD

**Issue by takekazuomi** [MicrosoftDocs/azure-docs.ja-jp#725]
&gt; PowerShell コンソールを使用している場合は、以下を実行します。
の部分の文書と、その下の例は、原文（英語）にはありません。削除してください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e026dd3b-caa2-73bd-ce82-65660d5e2128
* Version Independent ID: a925fed6-52b4-c67d-2088-306a128984cb
* Content: [クイック スタート - Hello World を Azure Service Fabric mesh にデプロイする](https://docs.microsoft.com/ja-jp/azure/service-fabric-mesh/service-fabric-mesh-quickstart-deploy-container)
* Content Source: [articles/service-fabric-mesh/service-fabric-mesh-quickstart-deploy-container.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/service-fabric-mesh/service-fabric-mesh-quickstart-deploy-container.md)
* Service: **service-fabric-mesh**
* GitHub Login: @rwike77
* Microsoft Alias: **ryanwi**

**Comment by LisandroSu** [comment]
こんにちは、@takekazoumi

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@takekazuomi

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/service-fabric-mesh/service-fabric-mesh-quickstart-deploy-container  
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team
