### ISSUE TITLE
モジュールツインの報告されるプロパティ（reported properties)について

### ISSUE THREAD

**Issue by bigw00d** [MicrosoftDocs/azure-docs.ja-jp#728]
モジュールツインの報告されるプロパティ（reported properties)をMQTTで更新したいです。トピックは何を指定したら良いでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: bcf2a86a-1de0-2786-db87-58279ceffb22
* Version Independent ID: 7e43624f-a87d-1c4d-94e6-e38c1d42686f
* Content: [Azure IoT Hub の MQTT サポートについて](https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-mqtt-support)
* Content Source: [articles/iot-hub/iot-hub-mqtt-support.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/iot-hub/iot-hub-mqtt-support.md)
* Service: **iot-hub**
* GitHub Login: @fsautomata
* Microsoft Alias: **elioda**

**Comment by LisandroSu** [comment]
@bigw00d  様、

コメントをお寄せいただき、誠にありがとうございます。docs.microsoft.com におけるエクスペリエンスの改善に努めておりますが、お寄せいただいたフィードバックに従って対応するにあたり、さらに情報をいただけるならありがたく存じます。さらに詳しい情報とともに、コメントについてご説明いただけましたら幸いです。

敬具
Microsoft DOCS インターナショナル チーム

**Comment by bigw00d** [comment]
ご対応ありがとうございます。
説明させていただきます。

「MQTT プロトコルを使用した IoT Hub との通信」のページには、MQTTを使用して「デバイスツイン」（DeviceTwin）の報告されるプロパティ（reported properties)を更新する内容が記載されています
（「デバイス ツインの報告されるプロパティの更新」の項目）
　
しかし、MQTTを使用して「モジュールツイン」の報告されるプロパティを更新する方法が記載されていませんので、教えていただきたく問い合わせしました。

よろしくお願い致します。

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #15589](https://github.com/MicrosoftDocs/azure-docs/issues/15589) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@bigw00d

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/15589) を確認してください。 

 記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 ,
Microsoft DOCS International Team
