### ISSUE TITLE
Chiller (深冷器) の日本語訳 

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/azure-docs.ja-jp#744]
https://docs.microsoft.com/ja-jp/azure/time-series-insights/tutorial-create-populate-tsi-environment

3. [Simulation setup](シミュレーションのセットアップ) ページが読み込まれたら、次の必須パラメーターを入力します。
[Chiller](深冷器) を選択します。
の(深冷器)は、意味不明のため、不要または別の日本語にしてください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e3f77e0d-fa3e-855b-31a4-4799dd126a9d
* Version Independent ID: 55c70869-90ae-320b-4468-4de7ad47d56c
* Content: [Azure Time Series Insights 環境を作成する](https://docs.microsoft.com/ja-jp/azure/time-series-insights/tutorial-create-populate-tsi-environment)
* Content Source: [articles/time-series-insights/tutorial-create-populate-tsi-environment.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/time-series-insights/tutorial-create-populate-tsi-environment.md)
* Service: **time-series-insights**
* GitHub Login: @ashannon7
* Microsoft Alias: **anshan**

**Comment by LisandroSu** [comment]
こんにちは、@ahidaka

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@ahidaka

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by changeworld** [comment]
This is already fixed (#745).

**Comment by LisandroSu** [comment]
こんにちは、@ahidaka

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: [Azure Time Series Insights 環境を作成する](https://docs.microsoft.com/ja-jp/azure/time-series-insights/tutorial-create-populate-tsi-environment) 

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
