### ISSUE TITLE
VHD をコピーせずにリージョン間で移行できますか?項目にリンクが設定されていない

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#752]
当該項目の＜「AzCopy コマンド ライン ユーティリティを使用してデータを転送する」＞部分にリンクが設定されていませんので修正をお願いします。

リンクすおのものは＜AzCopy＞の項目にあるものかと存じます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 6a98cba6-7267-3b45-8403-ff4138c1fec0
* Version Independent ID: e0ef9a1f-1caa-ed3a-257d-13a6e6136bd7
* Content: [Azure のクラウド ストレージ間で大量のデータを移動する](https://docs.microsoft.com/ja-jp/azure/storage/common/storage-moving-data#azcopy)
* Content Source: [articles/storage/common/storage-moving-data.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/storage/common/storage-moving-data.md)
* Service: **storage**
* GitHub Login: @tamram
* Microsoft Alias: **tamram**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16229](https://github.com/MicrosoftDocs/azure-docs/issues/16229) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@KeiroKamioka0000

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/16229) を確認してください。 

 記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 ,
Microsoft DOCS International Team
