### ISSUE TITLE
new articles + major changes "Azure portal で関数アプリを作成する" 

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/azure-docs.ja-jp#756]
There is a mistake in translation of the following articles. So, I want to correct misinterpretation and send Pull Request.

https://docs.microsoft.com/ja-jp/learn/modules/create-serverless-logic-with-azure-functions/3-create-an-azure-functions-app-in-the-azure-portal

However, I can not find the original file of the above article in this repository.
So, following the description of the Readme, I would like to create a new article.
If the original file already exists, I would like to send a pull request. Would you please let me know.

Community - new articles + major changes: If you're part of the Azure community and you want to create a new article or submit major changes, please submit an issue to start a conversation with the documentation team. Once you've agreed to a plan, you'll need to work with an employee to help bring that new content in through a combination of work in the public and private repositories.

**Comment by LisandroSu** [comment]
Hello, @changeworld 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Teamjaja

**Comment by LisandroSu** [comment]
Hello, @changeworld 

Here's the link for the [repo](https://github.com/MicrosoftDocs/learn-pr.ja-JP/blob/master/learn-pr/azure/create-serverless-logic-with-azure-functions/includes/3-create-an-azure-functions-app-in-the-azure-portal.md).

I'll be closing the issue now. Thank you again for the feedback.

Kind regards,
Microsoft DOCS International Team

**Comment by changeworld** [comment]
Thanks.
