### ISSUE TITLE
Chrome の列幅

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#757]
Chromeにおいてこのページの大部分の表の項目名では列の幅が1文字しかない状態で表示されてしまいます。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 78b601eb-a33e-cc09-8b2a-97ab496614cf
* Version Independent ID: fff6875f-6407-6db2-fe62-ad5fb0194c0d
* Content: [暗号化 - Microsoft Threat Modeling Tool - Azure](https://docs.microsoft.com/ja-jp/azure/security/azure-security-threat-modeling-tool-cryptography)
* Content Source: [articles/security/azure-security-threat-modeling-tool-cryptography.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/security/azure-security-threat-modeling-tool-cryptography.md)
* Service: **security**
* GitHub Login: @jegeib
* Microsoft Alias: **jegeib**

**Comment by dcbrown16** [comment]
![image](https://user-images.githubusercontent.com/34466884/46516929-71970a00-c821-11e8-9eeb-46816b21d86a.png)

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by DavidPrio** [comment]
Hi @ishasahni1 this is related to [Loc Issue 44717](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/44717) waiting for fix. Can you please help resolve it? Thanks!
CC @LisandroSu @CeciAc @Sara-Nicolini @SunnyDeng

**Comment by DavidPrio** [comment]
Hi @ishasahni1 this is related to[ Loc Issue 44717](https://ceapex.visualstudio.com/CEINTL/_workitems/edit/44717) waiting for fix. Can you please help resolve it? Thanks!
CC @LisandroSu @CeciAc @Sara-Nicolini @SonjaSaltzman

**Comment by ishasahni1** [comment]
@DavidPrio I am doing follow up with the engineering team on this Loc Issue

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16
フィードバックをお送りいただきありがとうございました。 
 Microsoft のエンジニア リング チームでは、ご提案いただいた内容を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: XXX  
 記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 
 敬具 
Microsoft DOCS International Team

--
@ishasahni1 closing this issue as per bug is fixed
best
