### ISSUE TITLE
Please consider of updated Japanese translation

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#761]
Such as following FAQ, please consider of update Japanese Translation document for this page.
Information regarding uplimit is very important, I believe.

以下QnAを含めた、このドキュメントの日本語版ページの更新を希望いたします。

&lt;How is Virtual WAN different from the existing Azure Virtual Network Gateway?&gt;
https://docs.microsoft.com/en-us/azure/virtual-wan/virtual-wan-faq#how-is-virtual-wan-different-from-the-existing-azure-virtual-network-gateway

Virtual Network Gateway VPN is limited to 30 tunnels. For connections, you should use Virtual WAN for large-scale VPN. You can connect up to 1000 branch connections with 2 Gbps in the hub for all regions except the West Central region. For the West Central region, 20 Gbps is available. We will be rolling out 20 Gbps to additional regions in the future. A connection is an active-active tunnel from the on-premises VPN device to the virtual hub. You can have one hub per region, which means you can connect more than 1000 branches across hubs.

&lt;Is there a network throughput limit when using Azure Virtual WAN?&gt;
Number of branches is limited to 1000 connections per hub/region and a total of 2 G in the hub. The exception is West Central US, which has a total of 20 Gbps. We will be rolling 20 Gbps out to other regions in the future.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 67c9a675-e1f5-0c17-30b7-69e33a5cf24b
* Version Independent ID: e4f9ba49-1efb-d10c-7c8b-5163226de9bd
* Content: [Azure Virtual WAN に関する FAQ](https://docs.microsoft.com/ja-jp/azure/virtual-wan/virtual-wan-faq#how-is-virtual-wan-different-from-the-existing-azure-virtual-network-gateway)
* Content Source: [articles/virtual-wan/virtual-wan-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-wan/virtual-wan-faq.md)
* Service: **virtual-wan**
* GitHub Login: @cherylmc
* Microsoft Alias: **cherylmc**

**Comment by LisandroSu** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@KeiroKamioka0000

フィードバックをお送りいただきありがとうございました。  

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/virtual-wan/virtual-wan-faq#how-is-virtual-wan-different-from-the-existing-azure-virtual-network-gateway

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。  


敬具
