### ISSUE TITLE
Incorrect transration

### ISSUE THREAD

**Issue by kei-yamazaki** [MicrosoftDocs/azure-docs.ja-jp#772]
Original document is described "Edge" however Japanese version document is translated to  "Microsoft Edge".

Please refer following link.
https://docs.microsoft.com/ja-jp/azure/iot-fundamentals/iot-services-and-technologies#edge

**Comment by CeciAc** [comment]
Hello, @kei-yamazaki,

Thank you for your feedback. 

Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/iot-fundamentals/iot-services-and-technologies#edge.  

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback. 

Kind regards, 
Microsoft DOCS International Team
