### ISSUE TITLE
Mistaken URL example

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#776]
「この属性は、.your-root-domain-here* と *.scm.your-root-domain-here を両方とも含むように設定する必要があります。」
最初のパスは正しくは *.your-root-domain-here になると思いますが、いかがでしょうか？

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b1afa49-a5b4-92db-68e8-3feeeff52eb3
* Version Independent ID: c9191775-e49c-1462-e525-a5ce549ae743
* Content: [Azure App Service Environment で内部ロード バランサーを作成して使用する](https://docs.microsoft.com/ja-jp/azure/app-service/environment/create-ilb-ase)
* Content Source: [articles/app-service/environment/create-ilb-ase.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/app-service/environment/create-ilb-ase.md)
* Service: **app-service**
* GitHub Login: @ccompy
* Microsoft Alias: **ccompy**

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16981](https://github.com/MicrosoftDocs/azure-docs/issues/16981) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/16981) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
