### ISSUE TITLE
non-supported process

### ISSUE THREAD

**Issue by KIchiyanagi** [MicrosoftDocs/azure-docs.ja-jp#780]
LINE WORKS サポートチームというメールはすでに使われていません。
LINE WORKS Developers Community で相談となっています。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 32fd0e63-c637-7a7d-9b1c-4ecfe2548553
* Version Independent ID: b5059615-9bb3-2713-1e8e-b2bec08ef62d
* Content: [チュートリアル: Azure Active Directory と LINE WORKS の統合](https://docs.microsoft.com/ja-jp/azure/active-directory/saas-apps/worksmobile-tutorial#feedback)
* Content Source: [articles/active-directory/saas-apps/worksmobile-tutorial.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/saas-apps/worksmobile-tutorial.md)
* Service: **active-directory**
* GitHub Login: @jeevansd
* Microsoft Alias: **jeedes**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #16993](https://github.com/MicrosoftDocs/azure-docs/issues/16993) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@KIchiyanagi

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/16993) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
