### ISSUE TITLE
failover translation

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#800]
現在の日本語：「フェールオーバーを即時にアクティブ化されてデータが完全に同期されます (フレンドリ フェールオーバー)。」
基の英語："it immediately activates the failover with full data synchronization (friendly failover)"
改善案：「データが完全に同期された状態で即時にフェールオーバーを開始します（フレンドリー フェールオーバー）。」

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2476aace-c2ac-4084-93d5-8bd4edbc0ea0
* Version Independent ID: fa098bb4-5c9e-0f58-cfc7-5d40eb1ce89b
* Content: [フェールオーバー グループとアクティブ geo レプリケーション - Azure SQL Database](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-geo-replication-overview)
* Content Source: [articles/sql-database/sql-database-geo-replication-overview.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-database/sql-database-geo-replication-overview.md)
* Service: **sql-database**
* GitHub Login: @anosov1960
* Microsoft Alias: **sashan**

**Comment by dcbrown16** [comment]
追加
「機能停止が検出された場合、経験的にデータの損失がゼロであれば、読み取り/書き込みのフェールオーバーが SQL によって自動的にトリガーされます。」
"If an outage is detected, SQL automatically triggers read-write failover if there is zero data loss to the best of our knowledge. "
案：「機能停止が検出された場合、こちらで確認できる限りデータの損失が発生していなければ SQL が自動的に読み取り/書き込みのフェールオーバーをトリガーします。」

**Comment by LisandroSu** [comment]
こんにちは、@dcbrown16

 ご協力に深く感謝いたします。Microsoft の担当チームがお寄せいただいたフィードバックを確認しましたところ、既にログ記録されている内容であることがわかりました。 

 問題 #802 をご確認ください。そのため、この問題は重複により終了とさせていただきます。 

 敬具 
Microsoft DOCS International Team
