### ISSUE TITLE
[フィードバック、編集、共有、黒、英語で読む]のメニュー部分をスクロールしても追従するようにして欲しい

### ISSUE THREAD

**Issue by changeworld** [MicrosoftDocs/azure-docs.ja-jp#833]
[フィードバックをこちらに入力してください]
[フィードバック、編集、共有、黒、英語で読む]のメニュー部分はとても便利です。
しかし、[このページ](https://docs.microsoft.com/ja-jp/azure/redis-cache/cache-web-app-cache-aside-leaderboard)のように縦に長いページでは、読むためにページをスクロールさせるので、途中でおかしい日本語を見つけて原文である英語を確認しようとすると、ページ最上位まで戻り、それからクリックしなければなりません。
クリックして英語にした後、おかしい日本語の英語原文を見つける必要があり、不便です。[フィードバック、編集、共有、黒、英語で読む]のメニュー部分をスクロールしても追従するようにして欲しいです。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 76d94fca-e5e5-5ca0-d5b0-2fc64148b152
* Version Independent ID: 54449bb4-cfd4-5c19-4ba3-50afe5aa082b
* Content: [キャッシュ アサイド パターンで Redis Cache を使用する Web アプリを作成するためにチュートリアル](https://docs.microsoft.com/ja-jp/azure/redis-cache/cache-web-app-cache-aside-leaderboard)
* Content Source: [articles/redis-cache/cache-web-app-cache-aside-leaderboard.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/redis-cache/cache-web-app-cache-aside-leaderboard.md)
* Service: **cache**
* GitHub Login: @wesmc7777
* Microsoft Alias: **wesmc**

**Comment by LisandroSu** [comment]
こんにちは、@changeworld

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by LisandroSu** [comment]
Hi @sunnydeng

The end user is suggesting that is very awkward to provide feedback in long documents like this one because all the necessary links are at the top. They were suggesting if it was possible to make the links float where the users are reading in order to make it easier.

Kind Regards,

**Comment by CeciAc** [comment]
Hi @SunnyDeng 
can you please get back to us with this one?

Kind Regards,

**Comment by CeciAc** [comment]
Hi @SunnyDeng 
Any updates on this one?
@DavidPrio

**Comment by CeciAc** [comment]
Hi @ishasahni1 
Any updates on this one?
@DavidPrio

**Comment by ishasahni1** [comment]
@CeciAc This is one great suggestion and I will surely pass on to the engineering team. Unfortunately at this time I am afraid that we don't have any feature like this avaialble.

**Comment by ishasahni1** [comment]
@CeciAc can you kindly confirm why this issue is reopened? As confirmed above I think this is a great suggestion, but it is more of a feature request so I am going to share with the Feature PM, but unfortunately at this time there is no ETA that I have. So can you kindly close this issue.

**Comment by ishasahni1** [comment]
@CeciAc @DavidPrio #please-translate

**Comment by DavidPrio** [comment]
@changeworld 
この度は大変貴重なご意見をいただき、まことにありがとうございます。弊社エンジニアチームと共有をさせていただきます。大変恐れ入りますが、ご提案のような機能は現在弊社製品にはございません。また実装可能な時期についても現在お答えできません。何卒よろしくお願い申し上げます。
CC @CeciAc @ishasahni1
