### ISSUE TITLE
「IoT Hub のカスタム DNS 名」の設定の説明がありません

### ISSUE THREAD

**Issue by sysartist** [MicrosoftDocs/azure-docs.ja-jp#835]
ページ最初にある「IoT Hub のカスタム DNS 名」を設定するために、リンク先の https://docs.microsoft.com/ja-jp/azure/dns/dns-custom-domain を確認しても、その設定の説明が見当たりません。仮に、CNAMEでIoTハブのhostnameを置き換えても、Http1, Mqtt, Amqp (TCP Onlyを含む）いずれもセキュリティエラー例外で実現できません。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 46282564-724c-bc0d-7c74-bb30ee8653aa
* Version Independent ID: c4f80f13-2a6a-2349-0a4a-882a873ef0ff
* Content: [Azure IoT Hub のエンドポイントについて](https://docs.microsoft.com/ja-jp/azure/iot-hub/iot-hub-devguide-endpoints#feedback)
* Content Source: [articles/iot-hub/iot-hub-devguide-endpoints.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/iot-hub/iot-hub-devguide-endpoints.md)
* Service: **iot-hub**
* GitHub Login: @dominicbetts
* Microsoft Alias: **dobett**

**Comment by LisandroSu** [comment]
こんにちは、@sysartist

 ご協力に深く感謝いたします。Microsoft の担当チームでは、ドキュメントに関するフィードバックに対してのみお答えすることができます。 

 ドキュメント ページの下部にある [製品のフィードバックを送信] ボタンを使用して、製品に関するフィードバックをログに記録してください。 

 ドキュメントに関するフィードバックがある場合は、このチャンネルをご自由に使用して、内容をログに記録してください。 

 記事の品質向上にご協力いただき誠にありがとうございました。  
 敬具 
Microsoft DOCS International Team
