### ISSUE TITLE
SkuNotAvailableエラー

### ISSUE THREAD

**Issue by Seiji-Tozaki** [MicrosoftDocs/azure-docs.ja-jp#857]
前提条件のIoTEdgeデバイスを作成するためのコマンドでタイトルのエラーが発生します。
リソースグループでリージョンをwestusに設定されていますが、westusでは利用できないSKUを指定してしまっているのでしょうか？

対応策をご教示ください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: e2289383-6ce2-a036-c710-7d1fad6e1700
* Version Independent ID: 3b902941-0876-17c3-3f0b-a4b7f7770531
* Content: [Azure IoT Edge + Linux クイック スタート](https://docs.microsoft.com/ja-jp/azure/iot-edge/quickstart-linux)
* Content Source: [articles/iot-edge/quickstart-linux.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/iot-edge/quickstart-linux.md)
* Service: **iot-edge**
* GitHub Login: @kgremban
* Microsoft Alias: **kgremban**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #17869](https://github.com/MicrosoftDocs/azure-docs/issues/17869) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@Seiji-Tozaki

 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 

 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/17869) を確認してください。 

 記事の品質向上にご協力いただき誠にありがとうございました。  

敬具 ,
Microsoft DOCS International Team
