### ISSUE TITLE
Translation of "Absolutely"

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#858]
「そして、 Azure Backup では、VM 拡張機能を使用している Azure VM には VM レベルのバックアップを提供します。 ゲスト Windows OS 上のファイルとフォルダーを保護するには、ゲスト Windows OS に Azure Backup エージェントをインストールします。」
「そして」のところは「Absolutely.」の翻訳のはずなので、「はい」とか「もちろん」に変更してください。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 02ad5c91-acc2-a50b-0b4a-8298c608df41
* Version Independent ID: 2e80d5ac-1918-61f8-87d4-8133a0250b1b
* Content: [Azure Backup エージェントの FAQ](https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-file-folder-backup-faq#can-i-install-the-azure-backup-agent-on-an-azure-vm-already-backed-by-the-azure-backup-service-using-the-vm-extension-br)
* Content Source: [articles/backup/backup-azure-file-folder-backup-faq.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/backup/backup-azure-file-folder-backup-faq.md)
* Service: **backup**
* GitHub Login: @trinadhk
* Microsoft Alias: **saurse;trinadhk**

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16
フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/backup/backup-azure-file-folder-backup-faq#can-i-install-the-azure-backup-agent-on-an-azure-vm-already-backed-by-the-azure-backup-service-using-the-vm-extension-br

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
