### ISSUE TITLE
Regarding the Audit Log

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#867]
I cannot find the Japanese translation of the following, which specifically say &lt;Audit Log cannot be enabled from database&gt;.
Current Japanese Translation does not specifically mention this, please consider of fix.

データベースのDiagnostic SettingsからではAudit Logが有効化されないと英語原文では明記されております。
日本語版では明記されていない状況であるので、修正をお願いいたします。

==========
Audit log cannot be enabled from database Diagnostics settings. To enable Audit log streaming, see Set up auditing for your database, and also see SQL Audit logs in Azure Log Analytics and Azure Event Hubs.
==========

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 57944e9d-0efa-3503-9fe8-46c91119ecc9
* Version Independent ID: 32caa5c0-aac4-75f8-42f8-b483d55a8392
* Content: [Azure SQL Database のメトリックと診断のロギング](https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-metrics-diag-logging#azure-portal)
* Content Source: [articles/sql-database/sql-database-metrics-diag-logging.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/sql-database/sql-database-metrics-diag-logging.md)
* Service: **sql-database**
* GitHub Login: @danimir
* Microsoft Alias: **v-daljep**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/sql-database/sql-database-metrics-diag-logging#azure-portal. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
