### ISSUE TITLE
Speech Serviceの名称

### ISSUE THREAD

**Issue by hatsunea** [MicrosoftDocs/azure-docs.ja-jp#893]
Azure Portalなどでは「Speech Services」となっているがdocsでは「Speech Service」となっている。
どちらが正しい名称でしょうか。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 5ab20294-c13e-b533-726f-9fde3005431d
* Version Independent ID: 0e47f11d-7656-8a6f-6e9a-ac0184ed4d15
* Content: [Speech Service を無料で試す - Azure Cognitive Services](https://docs.microsoft.com/ja-jp/azure/cognitive-services/speech-service/get-started#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/get-started.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cognitive-services/Speech-Service/get-started.md)
* Service: **cognitive-services**
* GitHub Login: @erhopf
* Microsoft Alias: **erhopf**

**Comment by CeciAc** [comment]
こんにちは、@hatsunea

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@hatsunea

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #20113](https://github.com/MicrosoftDocs/azure-docs/issues/20113) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
こんにちは、@hatsunea
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/20113) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
