### ISSUE TITLE
OK と NG が逆

### ISSUE THREAD

**Issue by naomioh** [MicrosoftDocs/azure-docs.ja-jp#894]
英語では ✔ が「OK」、X が NGだが、なぜか X が 〇 として翻訳されている

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 525c1c48-3355-bc91-b8d0-6104c1f5f098
* Version Independent ID: 0d1c6361-aeac-b0c9-016d-38d21f483396
* Content: [Azure Security Center でサポートされている機能とプラットフォーム](https://docs.microsoft.com/ja-jp/azure/security-center/security-center-os-coverage)
* Content Source: [articles/security-center/security-center-os-coverage.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/security-center/security-center-os-coverage.md)
* Service: **security-center**
* GitHub Login: @rkarlin
* Microsoft Alias: **rkarlin**

**Comment by LisandroSu** [comment]
こんにちは、@naomioh

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
