### ISSUE TITLE
Update Support OS

### ISSUE THREAD

**Issue by hermesian** [MicrosoftDocs/azure-docs.ja-jp#896]
The document should cover new OS distribution (e.g. RHEL 7.5).
RHEL 7.5 等、 新規の OS のディストリビューションでサポートされているか、ドキュメントに記載いただけたらと思います。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: f89338c0-968d-c22f-5b0d-ed3870ebc2fa
* Version Independent ID: 6daae1cc-f758-1d37-9de3-80a2832c08ef
* Content: [高速ネットワークを使った Azure 仮想マシンの作成](https://docs.microsoft.com/ja-jp/azure/virtual-network/create-vm-accelerated-networking-cli)
* Content Source: [articles/virtual-network/create-vm-accelerated-networking-cli.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/virtual-network/create-vm-accelerated-networking-cli.md)
* Service: **virtual-network**
* GitHub Login: @gsilva5
* Microsoft Alias: **gsilva**

**Comment by LisandroSu** [comment]
Issue moved to [MicrosoftDocs/azure-docs #18833](https://github.com/MicrosoftDocs/azure-docs/issues/18833) via [**ZenHub**](https://www.zenhub.com/)

**Comment by LisandroSu** [comment]
こんにちは、@hermesian
 ご協力に深く感謝いたします。お寄せいただいたフィードバックは、オリジナルのドキュメントに関係しています。 
 そのため、この問題を英語版のリポジトリに移行します。この問題の状態については、こちら (https://github.com/MicrosoftDocs/azure-docs/issues/18833) を確認してください。 
 記事の品質向上にご協力いただき誠にありがとうございました。  
敬具 ,
Microsoft DOCS International Team
