### ISSUE TITLE
更新お願いします / Please update

### ISSUE THREAD

**Issue by KeiroKamioka0000** [MicrosoftDocs/azure-docs.ja-jp#897]
アプリケーションゲートウェイの制限等が、英語原文ドキュメントにて更新されたようですので、日本語への適応をお願いします。
It seems like English document for this Document has been updated, please update the document please.

https://docs.microsoft.com/ja-jp/azure/azure-subscription-service-limits#application-gateway-limits
https://docs.microsoft.com/en-us/azure/azure-subscription-service-limits#application-gateway-limits

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 1cd57b6d-3c6f-e546-b3ea-f83892f4c23d
* Version Independent ID: 27aecc7b-f107-96d4-b044-ae026bca2727
* Content: [Azure サブスクリプションの制限とクォータ](https://docs.microsoft.com/ja-jp/azure/azure-subscription-service-limits#application-gateway-limits)
* Content Source: [articles/azure-subscription-service-limits.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/azure-subscription-service-limits.md)
* Service: **billing**
* GitHub Login: @rothja
* Microsoft Alias: **byvinyal**

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @KeiroKamioka0000
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/azure-subscription-service-limits#application-gateway-limits

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
