### ISSUE TITLE
staleness window の訳し方

### ISSUE THREAD

**Issue by takekazuomi** [MicrosoftDocs/azure-docs.ja-jp#916]
原文の
「Bounded staleness offers total global order except within the "staleness window." 」の部分の、"staleness window." の訳が、“staleness window” の訳が、"staleness 期間" と、"整合性制約期間" で混ざっている。どちらかに統一しないと意味が通らない。Bounded staleness の言葉を使うなら、“staleness window” のままにしたほうが、意味が通りやすいように思う。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 2b3fb7da-5483-160d-1781-d4abff9d798d
* Version Independent ID: d5e51b7e-7f34-c7df-ce4f-ee4bf5c8059a
* Content: [Azure Cosmos DB の一貫性レベル](https://docs.microsoft.com/ja-jp/azure/cosmos-db/consistency-levels)
* Content Source: [articles/cosmos-db/consistency-levels.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cosmos-db/consistency-levels.md)
* Service: **cosmos-db**
* GitHub Login: @aliuy
* Microsoft Alias: **andrl**

**Comment by CeciAc** [comment]
こんにちは、@takekazuomi

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/cosmos-db/consistency-levels

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
