### ISSUE TITLE
sampling_rateに対してサンプル速度という日本語訳が表示される

### ISSUE THREAD

**Issue by hatsunea** [MicrosoftDocs/azure-docs.ja-jp#920]
サンプル速度はサンプリングレートという日本語の方が一般的です。

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 50d8bb98-fbcd-7562-99ed-54211fd9afd3
* Version Independent ID: bd23e619-aee5-2b6e-b2d7-03ab5f7302af
* Content: [チュートリアル: Speech Service で音響モデルを作成する](https://docs.microsoft.com/ja-jp/azure/cognitive-services/Speech-Service/how-to-customize-acoustic-models#feedback)
* Content Source: [articles/cognitive-services/Speech-Service/how-to-customize-acoustic-models.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/cognitive-services/Speech-Service/how-to-customize-acoustic-models.md)
* Service: **cognitive-services**
* GitHub Login: @PanosPeriorellis
* Microsoft Alias: **panosper**

**Comment by CeciAc** [comment]
こんにちは、@hatsunea

フィードバックをお送りいただきありがとうございました。 

コメントを確認中で、改めてご連絡させていただきます。 

敬具 
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@hatsunea

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: XXX  

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
