### ISSUE TITLE
Old translation and incorrect explanation

### ISSUE THREAD

**Issue by ahidaka** [MicrosoftDocs/azure-docs.ja-jp#921]
Japanese version, this C IoT Edge module is not depend on .NET core 2.0.
And en-us version, it was already opened on 11/25/2018. Please tranrate this.

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: cbadb895-ea0b-0415-de1d-f40252981a5b
* Version Independent ID: f1180113-16a7-8be2-f8ca-d318160d38ce
* Content: [Azure IoT Edge C チュートリアル](https://docs.microsoft.com/ja-jp/azure/iot-edge/tutorial-c-module)
* Content Source: [articles/iot-edge/tutorial-c-module.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/iot-edge/tutorial-c-module.md)
* Service: **iot-edge**
* GitHub Login: @shizn
* Microsoft Alias: **xshi**

**Comment by CeciAc** [comment]
Hello, @ahidaka 
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @ahidaka 
 
Thank you for your feedback.
 
Our linguistic team reviewed your linguist suggestions and accepted them. We implemented your feedback and published to the updated articles on the Docs site to the following pages https://docs.microsoft.com/ja-jp/azure/iot-edge/tutorial-c-module. 

We truly appreciate your contribution to our articles and we encourage you to continue providing your valuable feedback.

Kind regards,
Microsoft DOCS International Team
