### ISSUE TITLE
Portal message

### ISSUE THREAD

**Issue by dcbrown16** [MicrosoftDocs/azure-docs.ja-jp#923]
この機能のポータル内のツールチップに誤訳があります。
ポータルのフィードバックで指摘はしましたが、もし担当チームの心当たりあったらエスカレートいただけないでしょうか？

場所：
Azure Active Directory &gt; 監査ログ &gt; データ設定のエクスポート &gt; (診断をオンにする) &gt; 
「ストレージアカウントへのアーカイブ」にチェック入れる
AuditLogs と SignInLogs の項目に「リテンション期間（日数）」に表示されるツールチップの内容

内容：
英語：「If you do not want to apply any retention policy and retain data forever, set retention (days) to 0.」
現在の日本語（不）：「保持ポリシーを適用せず、データを永続的に保持しない場合は、保有期間(日)を 0 に設定してください」
正しい訳：「保持ポリシーを適用せず、データを永続的に保持する場合は、保有期間(日)を 0 に設定してください。」

---
#### ドキュメントの詳細

⚠ *このセクションを編集しないでください。 docs.microsoft.com で必須です ➟ GitHub の問題のリンク。*

* ID: 39bd6875-8c82-02ff-5b74-86bc9ce5b902
* Version Independent ID: d9d36752-ac83-89b1-e22d-32ba6a41d7e5
* Content: [Azure Monitor での Azure Active Directory アクティビティ ログ (プレビュー)](https://docs.microsoft.com/ja-jp/azure/active-directory/reports-monitoring/concept-activity-logs-azure-monitor)
* Content Source: [articles/active-directory/reports-monitoring/concept-activity-logs-azure-monitor.md](https://github.com/MicrosoftDocs/azure-docs.ja-jp/blob/live/articles/active-directory/reports-monitoring/concept-activity-logs-azure-monitor.md)
* Service: **active-directory**
* GitHub Login: @priyamohanram
* Microsoft Alias: **priyamo**

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。

コメントを確認中で、改めてご連絡させていただきます。

敬具
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
こんにちは、@dcbrown16

フィードバックをお送りいただきありがとうございました。 

Microsoft の言語チームでは、お客様の言語担当者からのご提案を検証し、それを受け入れることになりました。お寄せいただいたフィードバックを実装し、ドキュメント サイト上の次のページの更新された記事に公開しました: https://docs.microsoft.com/ja-jp/azure/active-directory/reports-monitoring/concept-activity-logs-azure-monitor

記事の品質向上にご協力いただき誠にありがとうございました。引き続きお客様からの貴重なフィードバックをお待ちしています。 

敬具 
Microsoft DOCS International Team
